<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script src="/js/bienes-transacciones.js"></script>

<script>
$(document).ready(function() {
    $('#tabla_registroMovimientos').DataTable({
        "order": [0, 'desc'],
        "language": {
            "url": "/json/spanish.json"
        },
    });
  
});
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionProductosServicios'); ?>">Productos y Servicios</a></li>
            <li class="breadcrumb-item active" aria-current="page">Registro de Movimientos</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('herramientas'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Tipo-Evento -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                REGISTRO DE MOVIMIENTOS
                <a data-toggle="collapse" data-parent="#accordion" href="#add_tipo_evento" aria-expanded="true"
                    aria-controls="add_tipo_evento">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-menu-hamburger btn-collapse"></i></span>
                </a>
            </div>
            <div class="panel panel-body">
                <div class="collapse" id="add_tipo_evento">
                    <form method="post">
                        <div class="row form-row">
                            <div class="form-group col-md-3">
                                <label>RegistroMovimiento</label>
                                <input type="text" class="form-control" id="nombre" name="nombre"
                                    placeholder="RegistroMovimiento" required>
                            </div>
                            <div class="form-group col-md-3">
                                <label>Descripción</label>
                                <input type="text" class="form-control" name="descripcion"
                                    placeholder="Descripcion" required>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="form-group col-md-3">
                                <button type="button" class="btn btn-default" data-toggle="modal"
                                    data-target="#myModal">
                                    <span class="glyphicon glyphicon-plus"></span>
                                    RegistroMovimiento
                                </button>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Agregar RegistroMovimiento</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>¿Está seguro que desea agregar el registroMovimiento?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-default">Aceptar</button>
                                        <button type="button" class="btn btn-default"
                                            data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="tabla_registroMovimientos" class="display">
                                <thead>
                                    <tr>
                                        <th>Fecha</th>
                                        <th>Responsable</th>
                                        <th>Producto / Servicio</th>
                                        <th>Descripción</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                        if (isset($registroMovimientos)) {
                                            foreach ($registroMovimientos as $registroMovimiento) :
                                    ?>
                                    <tr>
                                        <td><?php echo ($registroMovimiento->getFecha()->format('Y/m/d')); ?></td>
                                        <td><?php echo ($registroMovimiento->getEjecutivo()->getUsuario()); ?></td>
                                        <td><?php echo ($registroMovimiento->getBien()->getNombre()); ?></td>
                                        <td><?php echo ($registroMovimiento->getDescripcion()); ?></td>
                                        <th></th>
                                    </tr>
                                    <?php endforeach;} ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('herramientas'); ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
    <!-- Fin: Panel Botones -->
</div>