<!-- scripts -->
<script src="/js/nota.js"></script>
<script src="/js/bienes-transacciones.js"></script>
<script src="/js/item.js"></script>
<script src="/js/opciones-transacciones.js"></script>


<!-- jQuery UI -->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<script language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
<script language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js">
</script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<link href="css/bootstrap.icon-large.min.css" rel="stylesheet">
<!-- <link href="http://twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet"> -->

<script type="text/javascript">
$(function() {
    $('#datetimepicker1').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker2').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker3').datetimepicker({
        format: 'DD/MM/YYYY'
    });
});
</script>


<!-- php -->
<?php
$date = date('d-m-Y');
$url1 =""; $url2=""; $url3=""; $label1=""; $label2=""; $label3=""; $label4="";
if ($persona->getTipo() =="CLIENTE"){
    $url1 = "/clientes";
    $label1="Cliente";
    $url2= "/clientes/listado";
    $label2="Listado";
    $label3="Ficha Cliente";
    $url3= "/clientes/listado/ficha/" . $persona->getId();
    $label4= "Agregar Nota Credito";
}
if ($persona->getTipo() =="PROVEEDOR"){
    $label1="Proveedores";
    $url1= "/proveedores";
    $label2="Listado";
    $url2= "/proveedores/listado";
    $label3="Ficha Proveedor";
    $url3= "/proveedores/listado/ficha/" . $persona->getId();
    $label4= "Agregar Nota Credito";

}
$responsable = $this->identity();
$tipoPersona = strtoupper($persona->getTipo());

// var_dump(json_decode($transaccionJson),true); die();
?>

<!-- json desde el controller, necesito otro con todos los bienes (nombre + valor) -->
<script>
var tipoTransaccion ="nota de credito";
var items = [];
var output;
var ivas = <?= $ivasJson ?>;
var idPersona = <?php echo ($persona->getId()); ?>;

var jsonModalTransaccion = <?= $facturasJson ?>;
var jsonRemitos = <?= $remitosConformadosJson ?>;
var jsonFacturas =  <?= $facturasJson ?>;

var transaccionPreviaNum = null;
var transaccionPreviaId = null;
var transaccionJson = null;
var empresa = <?= $empresaJson ?>;
var tipoPersona = "<?= $tipoPersona ?>";
</script>

<!-- Document -->
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $url1 ?>"><?= $label1 ?></a></li>
            <li class="breadcrumb-item"><a href="<?= $url2 ?>"><?= $label2 ?></a></li>
            <li class="breadcrumb-item"><a href="<?= $url3 ?>" ><?= $label3 ?></a></li>

            <li class="breadcrumb-item active" aria-current="page"><?= $label4 ?></li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="<?= $url3 ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<form method="post">
    <div class="container margen">
        <!-- Datos de NotaCredito -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    NOTA DE CRÉDITO
                </div>
                <div class="panel-body">
                    <!-- Fecha + Datos de Persona -->
                    <div class="row form-row">
                        <div class="form-group col-md-2">
                            <label>Fecha de Venta</label>
                            <div class='input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" name="fecha_transaccion" value="<?= $date ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Cliente</label>
                            <input type="text" class="form-control" name="persona" id="persona"
                                value="<?= $persona->getNombre() ?>" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Razón Social</label>

                            <input type="text" class="form-control" name="razon_social" id="razon_social" value="<?php if (!is_null($persona)) {
                                    echo ($persona->getRazon_social());
                                } ?>" readonly>

                        </div>
                        <div class="form-group col-md-3">
                            <label>Condición de IVA</label>
                            <input type="text" class="form-control" name="condicion_iva" id="condicion_iva" value="<?php if (!is_null($persona)) {
                                    echo ($persona->getNombreCondicionIva());
                                } ?>" readonly>
                        </div>
                    </div>
                    <!-- Datos de Transaccion -->
                    <div class="row form-row">
                        <div class="form-group col-md-2">
                            <label>Nro. de Transacción</label>
                            <input type="text" class="form-control" name="numero_transaccion" id="numero_transaccion"
                                value="<?= str_pad($numTransacciones, 5, "0", STR_PAD_LEFT) ?>" style="max-width: 250px;" readonly>
                        </div>
                        <div class="form-group col-md-2">
                            <label>Nro. Nota de Crédito</label>
                            <input type="text" class="form-control" name="numero_notaCredito" id="numero_notaCredito"
                                value="<?= str_pad($numNotaCredito, 5, "0", STR_PAD_LEFT) ?>" style="max-width: 250px;" readonly>
                        </div>
                        <div class="form-group col-md-2" id="tipos_notaCredito">
                            <label>Tipo Nota de Crédito</label>
                            <select class="form-control" name="oficial" id="oficial" require>
                                <option value="0" selected>No Oficial</option>
                                <option value="1">Oficial</option>
                            </select>
                        </div>
                        <input type="hidden" id="responsable" name="responsable" value="<?= $responsable ?>">
                        <input type="hidden" id="url" name="url" value="<?= $url3 ?>">
                        <input type="hidden" id="id_transaccion_previa" name="id_transaccion_previa">
                        <input type="hidden" id="jsonitems" name="jsonitems">

                    </div>
                </div>
            </div>
        </div>
        <!-- Listado de Detalles -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                   DESCRIPCIÓN
                </div>
                <!-- Agregar Renglon-->
                <div class="container" style="padding-top:10px;">
                    <form method="post" autocomplete="off">
                        <div class="container row">
                            <div class="form-group col-md-3 margin-padding-xs">
                                <label>Agregar transacción previa</label>
                                <div class="autocomplete input-group">
                                    <select class="form-control" id="tipoTransaccion" name="tipoTransaccion">
                                        <option value="Factura">Factura</option>
                                        <option value="Remito">Remito Conformado</option>
                                    </select>
                                    <span class="input-group-btn">
                                        <button type="button" id="btn-modal" class="btn btn-default" data-toggle="modal" 
                                            data-target="#modalTransacciones"><i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <!-- <br> -->
                        <div class="container row">
                            <input type="hidden" class="form-control" name="item_id" id="item_id">
                            <div class="form-group col-sm-8 margin-padding-xs">
                                <label>Detalle</label>
                                <input type="text" class="form-control" name="nota_detalle" id="nota_detalle"
                                    placeholder="Detalle" >
                            </div>
                            <div class="form-group col-sm-2 margin-padding-xs">
                                <label>Monto</label>
                                <input type="text" class="form-control" name="nota_monto" id="nota_monto"
                                    placeholder="Monto"  onkeypress="return justNumbers(event);">
                            </div>
                            <div class="form-group col-sm-1 margin-padding-xs">
                                <label>&nbsp;</label>
                                <button type="button" class="btn btn-default" onclick="addDetalleToTable()">
                                    <span class="glyphicon glyphicon-plus"  onkeypress="return pulsar(event)"></span> Agregar
                                </button>
                            </div>
                        </div>
                </div>
                <!-- Tabla de Detalles -->
                <div class="panel panel-body" >
                    <div class="panel panel-body" id="contenido_bienes">
                        <div id="div_table_items">
                            <script>
                            var items = <?php echo ($json); ?>;
                            // Crear Tabla
                            addDetallesNota(items, "nota de credito", idPersona);
                            </script>
                        </div>
                        <br>                     
                    </div>
                    <div class="container" hidden="true" >
                        <a href="<?= $this->url('bienes', ['action' => 'index', 'transaccion' => 'notaCredito', 'accion' => 'agregar', 'id' => $persona->getId()]); ?>"
                        type="button">
                        <span class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar Item</span> </a>
                    </div>
                </div>
            </div>
        </div>
        
     

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar Nota de Crédito</h4>
                </div>
                <div class="modal-body">
                    <p id="msjModal">¿Está seguro que desea agregar esta transacción?</p>
                </div>
                <div class="modal-footer">
                    <button id="btnModalAceptar" type="submit" class="btn btn-default">Aceptar</button>
                    <button id="btnModalCancelar" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- MODAL TRANSACCIONES -->
    <div id="modalTransacciones" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Seleccionar Transacción</h4>
                </div>
                <div class="modal-body">
                    <div class="panel panel-body" id="contenido_transacciones">
                    <div id="div_table_transacciones">
                        <script>
                        completarTransacciones(jsonModalTransaccion);
                        </script>
                    </div>
                    <br>                     
                </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                </div>
            </div>
        </div>
    </div>
      
            <!-- Datos Economicos -->
            <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    TOTAL
                </div>
                <div class="panel-body">
                    <!-- Totales -->
                    <div class="row form-row">
                        <div class="form-group col-md-3" id="monedas">
                            <label>Moneda</label>
                            <script>
                            var monedas = <?php echo ($monedasJson); ?>;
                            completarMonedas(monedas);
                            </script>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Fecha de Vencimiento</label>
                            <div class='input-group date' id='datetimepicker2'>
                                <input type='text' class="form-control" name="fecha_vencimiento" value="<?= $date ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Total ($)</label>
                            <input type="text" class="form-control" name="total_general" id="total_general"
                                value="0" readonly>
                        </div>                   
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-9">
                            <label>En concepto de</label>
                            <textarea name="concepto" id ="concepto" class="form-control" rows="2" placeholder="Ingresar concepto de la transacción" required=""></textarea>
                        </div>
                    </div>
                    <script>
                    calcularSubcampos();
                    </script>
                </div>
            </div>
        </div>
    </div>
</form>

<div id="div_transaccion">
</div> 
<div id="div_items_transaccion_previa">
</div> 
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a id="btnModalGuardar" data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $url3 ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->