<!-- scripts -->
<script src="/js/bienes-transacciones.js"></script>
<script src="/js/item.js"></script>
<script src="/js/opciones-transacciones.js"></script>
<script src="/js/transacciones.js"></script>

<!-- jQuery UI -->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<script language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
<script language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js">
</script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<link href="css/bootstrap.icon-large.min.css" rel="stylesheet">
<!-- <link href="http://twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet"> -->

<script type="text/javascript">
$(function() {
    $('#datetimepicker1').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker2').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker3').datetimepicker({
        format: 'DD/MM/YYYY'
    });
});
</script>

<!-- php -->
<?php

$date = date('d-m-Y');

if(!is_null($transaccion->getFecha_transaccion())){
    $fecha_transaccion = $transaccion->getFecha_transaccion()->format('d/m/Y');
} else {
    $fecha_transaccion = $date;
}

if(!is_null($transaccion->getTransaccionPrevia())){
    $transaccionPreviaNum = $transaccion->getTransaccionPrevia()->getNumeroTransaccionTipo();
} else {
    $transaccionPreviaNum = -1;
}
$url = "/clientes/listado/ficha/" . $persona->getId();
$responsable = $this->identity();
$tipoPersona = strtoupper($persona->getTipo());

?>

<!-- json desde el controller, necesito otro con todos los bienes (nombre + valor) -->
<script>
var tipoTransaccion ="nota de credito";
var items = [];
var json_items = <?= $json_bienes ?>;
var json_items_codigos = <?= $json_bienes ?>;
var json_items_nombres = <?= $json_bienes ?>;
var output;
var ivas = <?= $ivasJson ?>;

var jsonPresupuestos = <?= $presupuestosJson ?>;
var jsonPedidos = <?= $pedidosJson ?>;
var jsonRemitos = <?= $remitosJson ?>;
var jsonModalTransaccion = <?= $presupuestosJson ?>;
var itemsTransaccionJson = <?= $itemsTransaccionJson ?>;

items.concat(itemsTransaccionJson);
var itemsTransaccion =null;
var itemsAnteriores =null;
var transaccionPreviaNum = <?= $transaccionPreviaNum ?>;
if (transaccionPreviaNum=== -1){transaccionPreviaNum=null};
var itemsTransaccionPrevia = null;
if(transaccionPreviaNum!=null){
    getItemsTransaccionPrevia();
}
var transaccionJson = null;
var empresa = <?= $empresaJson ?>;
var tipoPersona = "<?= $tipoPersona ?>";

</script>

<!-- Document -->
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/clientes">Clientes</a></li>
            <li class="breadcrumb-item"><a href="/clientes/listado">Listado</a></li>
            <li class="breadcrumb-item"><a href="<?= $url ?>">Ficha</a></li>

            <li class="breadcrumb-item active" aria-current="page">Editar Cobro</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<form method="post">
    <div class="container margen">
        <!-- Datos de Cobro -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    COBRO
                </div>
                <div class="panel-body">
                    <!-- Fecha + Datos de Persona -->
                    <div class="row form-row">
                        <div class="form-group col-md-2">
                            <label>Fecha de Venta</label>
                            <div class='input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" name="fecha_transaccion" value="<?= $fecha_transaccion ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Cliente</label>
                            <input type="text" class="form-control" name="persona" id="persona"
                                value="<?= $persona->getNombre() ?>" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Razón Social</label>

                            <input type="text" class="form-control" name="razon_social" id="razon_social" value="<?php if (!is_null($persona)) {
                                    echo ($persona->getRazon_social());
                                } ?>" readonly>

                        </div>
                        <div class="form-group col-md-3">
                            <label>Condición de IVA</label>
                            <input type="text" class="form-control" name="condicion_iva" id="condicion_iva" value="<?php if (!is_null($persona)) {
                                    echo ($persona->getNombreCondicionIva());
                                } ?>" readonly>
                        </div>

                    </div>
                    <!-- Datos de Transaccion -->
                    <div class="row form-row">
                        <div class="form-group col-md-2">
                            <label>Número de Transacción</label>
                            <input type="text" class="form-control" name="numero_transaccion" id="numero_transaccion"
                                value="<?= $numTransacciones ?>" readonly style="max-width: 250px;">
                        </div>
                        <div class="form-group col-md-2">
                            <label>Número de Cobro</label>
                            <input type="text" class="form-control" name="numero_notaCredito" id="numero_notaCredito"
                                value="<?= $numCobro ?>" style="max-width: 250px;" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Buscar Transacción</label>
                            <div class="autocomplete input-group">
                                <select class="form-control" id="tipoTransaccion" name="tipoTransaccion">
                                    <option value="Presupuesto">Presupuesto</option>
                                    <option value="Pedido">Pedido</option>
                                    <option value="Remito">Remito</option>
                                    <!-- <option value="NotaCredito">NotaCredito</option>
                                    <option value="NotaCredito">Nota de Crédito</option>
                                    <option value="NotaCredito">Nota de Débito</option> -->
                                </select>
                                <span class="input-group-btn">                        <button type="button" id="btn-modal" class="btn btn-default" data-toggle="modal" data-target="#modalTransacciones"><i class="glyphicon glyphicon-search"></i>
                                </button></span>
                            </div>
                        </div>
                        <input type="hidden" id="responsable" name="responsable" value="<?= $responsable ?>">
                        <input type="hidden" id="url" name="url" value="<?= $url ?>">
                        <input type="hidden" id="id_transaccion_previa" name="id_transaccion_previa">
                    </div>
                </div>
            </div>
        </div>

        <!-- Listado de Items -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    LISTADO DE PRODUCTOS Y SERVICIOS
                </div>

                <!-- Form Autocompletado -->
                <div class="container" style="padding-top:10px;">
                    <form method="post" autocomplete="off">

                        <input type="hidden" class="form-control" name="item_id" id="item_id">

                        <div class="autocomplete form-group col-sm-2 margin-padding-xs">
                            <label>Código</label>
                            <input type="text" class="form-control" name="item_codigo" id="item_codigo"
                                placeholder="Código" onkeypress="return pulsar(event)" >
                        </div>
                        <div class="autocomplete form-group col-sm-4 margin-padding-xs">
                            <label>Producto / Servicio</label>
                            <input type="text" class="form-control" name="item_nombre" id="item_nombre"
                                placeholder="Producto Y Servicio"  onkeypress="return pulsar(event)" >
                        </div>
                        <div class="form-group col-sm-2 margin-padding-xs">
                            <label>Cantidad</label>
                            <input type="number" class="form-control" name="item_cantidad" id="item_cantidad" min="1"
                                max="99" value="" placeholder="Cantidad" onkeypress="return justNumbers(event)">
                        </div>
                        <div class="form-group col-sm-2 margin-padding-xs">
                            <label>Stock Disponible</label>
                            <input type="text" class="form-control" name="item_stock" id="item_stock"
                                placeholder="Stock Disponible" readonly>
                        </div>
                        <div class="form-group col-sm-1 margin-padding-xs">
                            <label>&nbsp;</label>
                            <button type="button" class="btn btn-default" onclick="addItemToTable()">
                                <span class="glyphicon glyphicon-plus"  onkeypress="return pulsar(event)"></span> Agregar
                            </button>
                        </div>
                </div>
                <!-- Detalles de Producto Y Servicio -->
                <div class="container" style="">
                    <label>
                        <input type="checkbox" value="" data-toggle="collapse" data-parent="#accordion"
                            data-target="#collapseDetalles" aria-expanded="true" aria-controls="collapseDetalles"
                            name="Detalles" id="Detalles">
                        Mostrar Detalles
                    </label>
                    <div class="container row collapse" id="collapseDetalles">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Descripción</th>
                                    <th>Categoría</th>
                                    <th>Precio</th>
                                    <th>% Descuento</th>
                                    <th>Precio c/Dto.</th>
                                    <th>% IVA (%)</th>
                                    <th>Precio c/IVA</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td id="item_descripcion"></td>
                                    <td id="item_categoria"></td>
                                    <td id="item_precio"></td>
                                    <td id="item_descuento"></td>
                                    <td id="item_descuento_precio"></td>
                                    <td id="item_iva"></td>
                                    <td id="item_iva_precio"></td>
                                    <td id="item_subtotal"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <script src="/js/autocomplete.js"></script>
                <input type="hidden" id="jsonitems" name="jsonitems" size="200">

                <!-- Tabla de Items -->
                <div class="panel panel-body">
                    <div class="panel panel-body" id="contenido_bienes">
                        <div id="div_table_items">
                            <script>
                            var items = <?php echo ($json); ?>;
                            var idPersona = <?php echo ($persona->getId()); ?>;
                            // Crear Tabla
                            addItems(items, "nota de credito", idPersona, false);
                            </script>
                        </div>
                        <br>
                    </div>
                    <div class="container" hidden="true" >
                        <a href="<?= $this->url('bienes', ['action' => 'index', 'transaccion' => 'notaCredito', 'accion' => 'agregar', 'id' => $persona->getId()]); ?>"
                        type="button">
                        <span class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar Item</span> </a>
                    </div>
                    <div class="container" >
                        <button  type="button" class="btn btn-default" onclick="actualizarPrecios()"><span class="glyphicon glyphicon-refresh"></span>
                       Actualizar Precios </button>
                    </div>
                </div>
            </div>
        </div>


        <!-- Datos Económicos -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    DATOS ECONÓMICOS
                </div>
                <div class="panel-body">
                    <!-- Totales -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Venta Bruta ($)</label>
                            <input type="text" class="form-control" name="venta_bruta" id="venta_bruta"
                                placeholder="Precio x Cantidad" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Descuento Global ($)</label>
                            <input type="text" class="form-control" name="descuento_total" id="descuento_total"
                                value="0" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>IVA Total ($)</label>
                            <input type="text" class="form-control" name="iva_total" id="iva_total" value="0" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Total ($)</label>
                            <input type="text" class="form-control" name="subtotal_general" id="subtotal_general"
                                value="0" readonly>
                        </div>
                    </div>
                    <!-- Forma de Pago + Fecha -->
                    <div class="row form-row">
                        <div class="form-group col-md-3" id="monedas">
                            <label>Moneda</label>
                            <script>
                            var monedas = <?php echo ($monedasJson); ?>;
                            completarMonedas(monedas);
                            </script>
                        </div>
                        <div class="form-group col-md-3" id="formasPago">
                            <label>Forma de Pago</label>
                            <script>
                            var formasPago = <?php echo ($formasPagoJson); ?>;
                            var transaccionJson = <?php echo ($transaccionJson); ?>;
                            completarFormasPago(formasPago, transaccionJson);
                            </script>
                        </div>
                        <div id="div_bonificacion" class="form-group col-md-3">
                            <label>% Bonificación</label>
                            <input type="text" class="form-control" name="bonificacion_general"
                                id="bonificacion_general" value="0.00" onkeypress="return justNumbers(event);"
                                onkeyup="calcularSubcampos()">
                        </div>
                        <div id="div_recargo" class="form-group col-md-3">
                            <label>% Recargo</label>
                            <input type="text" class="form-control" name="recargo_general" id="recargo_general"
                                value="0.00" onkeypress="return justNumbers(event);" onkeyup="calcularSubcampos()">
                        </div>
                        <script>
                        setBonificacionRecargo();
                        </script>
                    </div>
                    <!-- Total -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Importe de Bonificación ($)</label>
                            <input type="text" class="form-control" name="bonificacion_importe" id="bonificacion_importe" value="<?php if (!is_null($transaccion->getBonificacionImporte())){echo $transaccion->getBonificacionImporte();} else {echo(0);} ?>"
                                readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Importe de Recargo ($)</label>
                            <input type="text" class="form-control" name="recargo_importe" id="recargo_importe" value="<?php if (!is_null($transaccion->getRecargoImporte())){echo $transaccion->getRecargoImporte();} else {echo(0);} ?>" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Importe Total ($)</label>
                            <input type="text" class="form-control" name="total_general" id="total_general" value="0"
                                readonly>
                        </div>
                        <div class="form-group col-md-2" hidden>
                            <label>Fecha de Vencimiento</label>
                            <div class='input-group date' id='datetimepicker2'>
                                <input type='text' class="form-control" name="fecha_vencimiento" value="<?= $fecha_vencimiento ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script>
                    calcularSubcampos();
                    </script>
                </div>
            </div>
        </div>


    </div>
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Editar Nota de Débito</h4>
                </div>
                <div class="modal-body">
                    <p id="msjModal">¿Está seguro que desea guardar esta transacción?</p>
                </div>
                <div class="modal-footer">
                    <button id="btnModalAceptar" type="submit" class="btn btn-default">Aceptar</button>
                    <button id="btnModalCancelar" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <div id="modalTransacciones" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Seleccionar Transaccion </h4>
                </div>
                <div class="modal-body">
                    <div class="panel panel-body" id="contenido_transacciones">
                    <div id="div_table_transacciones">
                        <script>
                        // completarTransacciones(jsonPrespuestos);
                        </script>
                    </div>
                    <br>                     
                </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" onclick="completeItems()" data-dismiss="modal">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>    

</form>

<div id="div_transaccion">
</div> 
<div id="div_items_transaccion_previa">
</div> 
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a id="btnModalGuardar" data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $url ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->