<script src="/js/transacciones.js"></script>
<script>
    itemsAnteriores = itemsTransaccion;
    itemsTransaccion = <?= $itemsTransaccionJson ?>;
    transaccionJson = <?= $transaccionJson ?>;
    addTransaccionItems();
    completarFormasPago(formasPago, transaccionJson);
    completarMonedas(monedas, transaccionJson);

    bonificacion = transaccionJson["Bonificacion general"];
    recargo = transaccionJson["Recargo general"];
    setBonificacionRecargo();
</script>