<?php
$this->headTitle('Servicios');

?>
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
          
            <li class="breadcrumb-item active" aria-current="page">Listado</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
        style="margin:0px;">
            <li class="pull-right"><a href="/productospresupuestos/presupuestos" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<script src="js/functions.js"> </script>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                SERVICIOS DE LA EMPRESA
            </div>
            <div class="panel panel-body">
                <div class="col-md-12">
                    <div class="table-responsive">
                            <table id="tabla_presupuestos" class="table table-bordred table-striped">
                            <thead>
                                <tr>
                                    <th class="th-sm">Nombre</th>
                                    <th class="th-sm">Categoria</th>
                                    <th class="th-sm">Precio</th>
                                    <th class="th-sm">Descuento</th>
                                    <th class="th-sm">Precio final IVA</th>
                                    <th class="th-sm">Precio final IVA DTO</th>
                                    <th></th>
                                </tr>
                            
                            </thead>

                            <?php foreach ($presupuestos as $presupuesto) :
                                $bien = $presupuesto->getBien();
                            ?>
                                <tr>
                                    <td><?php echo ($bien->getNombre()); ?></td>
                                    <td><?php echo ($bien->getCategoriaNombre()); ?></td>
                                    <td><?php echo  money_format("$ %n",($bien->getPrecio())); ?></td>
                                    <td><?php echo ($bien->getDescuento()); ?></td>
                                    <td><?php echo  money_format("$ %n",($bien->getPrecio_final_iva())); ?></td>
                                    <td><?php echo  money_format("$ %n",($bien->getPrecio_final_iva_dto())); ?></td>
                                    <td class="table-items-right"> 
                                    <a class="btn btn-default" href="<?= $this->url('gestionProductosServicios/gestionServicios/editar', ['action' => 'edit', 'tipo'=>'presupuesto','id' => $presupuesto->getId()]); ?>">
                                        <span class="glyphicon glyphicon-pencil" ></span> 
                                    </a>
                                    <button name="<?= $presupuesto->getId() ?>" id="<?= $presupuesto->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $presupuesto->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                                </td>
                                <!-- Modal -->
                                <div id="myModal<?= $presupuesto->getId() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Borrar presupuesto</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Estas seguro de borrar el presupuesto?
                                                    "<?= $this->escapeHtml($presupuesto->getNombre()) ?>"

                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/eliminar', ['action' => 'remove', 'id' => $presupuesto->getId()]); ?>" class="btn btn-default">Borrar</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>  
            </div>
        </div>
    </div>
    <?php
        echo $this->paginationControl($presupuestos, 'Sliding', // All, Elastic, Jumping, Sliding
                    'search_pagination_presupuesto.phtml', $this->url('presupuesto/page', ['action' => 'index', 'id' => 1]));    ?>
</div>




<!-- Fin: Datos de la empresa -->
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/agregar', ['tipo'=>'presupuesto']); ?>">
                    <img src="<?= $this->basePath('img/crm/presupuesto_add_n.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Agregar</label><br>
                <label>Servicio</label>
            </div>
        </div>
        
        <div class="col ficha-cliente-p img-centrar">
            <div>
            <a href="<?= $volver ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha zoom">
            </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->