
<?php
$this->headTitle('Editar Profesión');

$form->get('nombre')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Editar Profesión <?= $this->escapeHtml($profesioncliente->getId()) ?></h1>

            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>
                   <div class="form-group">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <?= $this->formElement($form->get('nombre')); ?>
                        <?= $this->formElementErrors($form->get('nombre')); ?>                  
                    </div>
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <?= $this->form()->closeTag(); ?>
                </div>    
            </div>   
        </div>
    </div>
</div>
    

