<?php 
header("Pragma: public");
header("Expires: 0");
$filename = "Backup_Servicios.xls";
//header("Content-type: application/x-msdownload; charset=utf8");
header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=$filename");
header("Pragma: no-cache");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
?>

<table>
    <tbody>
        <?php foreach ($resultado as $servicio): 
        ?>
            <tr>
                <td><?php echo(utf8_decode($servicio->getNombre())); ?></td>
                <td><?php echo(utf8_decode($servicio->getDescripcion()));?></td>
                <td><?php echo(utf8_decode($servicio->getCategoriaServicio()));?></td>
                <td><?php echo(utf8_decode($servicio->getPrecio()));?></td>
                <td><?php echo(utf8_decode($servicio->getIva_gravado()));?></td>
                <td><?php echo(utf8_decode($servicio->getPrecio_final_iva()));?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>

