<!-- scripts -->
<script src="/js/servicio.js"></script>
<?php
$bien = $servicio->getBien();
$categoria = $bien->getCategoria();
$iva = $bien->getIva();
$proveedor = $bien->getProveedor();
?>
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios">Productos y Servicios</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios/productos">Servicio</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios/servicios/listado">Listado</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Servicio</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
        style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios/listado" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<form method="post">
<div class="container margen">
    <!-- Datos del Servicio -->
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS PARTICULARES DEL SERVICIO
            </div>
            <div class="panel-body">
                <input hidden="" name="ejecutivo" value="<?= $this->identity() ?>">
                <!-- 1ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre *</label>
                        <input type="text" required="true" class="form-control requerido" name="nombre" placeholder="Ingresar nombre"
                            value="<?php echo($bien->getNombre());?>" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Descripción</label>
                        <input type="text" class="form-control" name="descripcion" placeholder="Ingresar descripción" value="<?php echo($bien->getDescripcion());?>">
                    </div>
                </div>
                <!-- 2da fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Código de Servicio *</label>
                        <input type="text" class="form-control requerido" name="codigo"
                            value="<?= $bien->getCodigo(); ?>" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Marca</label>
                        <input type="text" class="form-control" name="marca" placeholder="Ingresar marca" 
                            value="<?php echo($bien->getMarca()); ?>">
                    </div>
                </div>
                <!-- 3ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Código de Barras</label>
                        <input type="text" class="form-control" name="codigo_barras" id="codigo_barras"
                            value="<?= $bien->getCodigo_barras(); ?>">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Unidad de Medida</label>
                        <input type="text" class="form-control" name="unidad" value="<?= $bien->getUnidad_medida() ?>">
                    </div>
                </div>
                <!-- 4ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Categoría</label>
                        <select class="form-control place_holder dropdown" id="categoria" name="categoria">
                             <option value="<?php if(isset($categoria)){ echo ($categoria->getId()); } else{echo (-1);}?>" hidden="">  
                                <?php if(isset($categoria)){ echo $categoria->getNombre(); } else {echo ("Seleccionar Categoría");}?>
                            </option>
                            <option value="-1">No definido</option>
                            <?php foreach ($categorias as $categoria) : ?>
                                <option value="<?= $categoria->getId(); ?>">
                                    <?= $categoria->getNombre(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Proveedor</label>
                        <select class="form-control place_holder dropdown" id="proveedor" name="proveedor">
                            <option value="<?php if(isset($proveedor)){ echo ($proveedor->getId()); }?>" hidden="">  
                                <?php if(isset($proveedor)){ echo $proveedor->getPersona()->getNombre(); } else {echo ("Seleccionar Proveedor");}?>
                            </option>
                            <option value="-1">No definido</option>
                            <?php foreach ($proveedores as $proveedor) : ?>
                                <option value="<?= $proveedor->getId(); ?>">
                                    <?= $proveedor->getPersona()->getNombre(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>   
    </div>

    <!-- Fin Datos del Servicio -->

    <!-- Precios del Servicio -->
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS ECONÓMICOS DEL SERVICIO
            </div>
            <div class="panel-body">
                <!-- 1ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Precio</label>
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="precio_venta" id="precio_venta" 
                                value="<?php echo($bien->getPrecio());?>" onkeypress="return justNumbers(event);" 
                                onkeyup="calcularPrecios()">
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <label>Descuento</label>
                        <div class="input-group">
                            <span class="input-group-addon">%</span>
                            <input type="text" class="form-control" name="descuento" id="descuento" 
                                value="<?php echo($bien->getDescuento());?>"
                                onkeypress="return justNumbers(event);" onkeyup="calcularPrecios()">
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <label>IVA</label>
                        <div class="input-group">
                            <span class="input-group-addon">%</span>
                            <select class="form-control" name="iva" id="iva"
                                onkeypress="return justNumbers(event);" onchange="calcularPrecios()">
                                <option value="<?php if(isset($iva)){ echo ($iva->getId()); }?>" hidden="">  
                                        <?php if(isset($iva)){ echo $iva->getValor(); } else {echo ("Seleccionar Iva");}?>
                                </option>
                                <?php foreach ($ivas as $iva) : ?>
                                    <option value="<?php  echo  ($iva->getId()); ?>">
                                    <?php echo ($iva->getValor()) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Importe IVA</label>
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="iva_total" id="iva_total" 
                                value="<?php echo($bien->getIva_gravado());?>">
                        </div>
                    </div>
                </div>
                <!-- 2ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Precio Público con Dto</label>
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="precio_publico_dto" id="precio_publico_dto" 
                                readonly value="<?php echo($bien->getPrecio_final_dto());?>" >
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio Público + IVA</label>
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="precio_publico_iva" id="precio_publico_iva"
                                readonly value="<?php echo($bien->getPrecio_final_iva());?>">
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio Público +IVA con Dto.</label>
                        <div class="input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="precio_publico_iva_dto" id="precio_publico_iva_dto"
                                readonly value="<?php echo($bien->getPrecio_final_iva_dto());?>" >
                        </div>
                    </div>
                </div>
            </div>
        </div>   
    </div>
    <!-- Fin Precios del Servicio -->

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar servicio</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea agregar este servicio?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin Modal -->
</div>

<!-- Fin: Cliente Nuevo -->

</form>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar"> 
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>                   
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>       
</div>
<!-- Fin: Panel Botones -->

<?= $this->form()->closeTag(); ?>

