
<?php
$this->headTitle('Editar datos de la servicio');

$form->get('descripcion')->setAttributes([
    'class' => 'form-control',
    'value' => $servicio->getDescripcion()
]);

$form->get('costo')->setAttributes([
    'class' => 'form-control',
    'value' => $servicio->getCosto()

]);

$form->get('cant_animales')->setAttributes([
    'class' => 'form-control',
    'value' => $servicio->getCant_animales()

]);


$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">Editar los datos de la servicio</div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="row form-row">
            <?= $this->form()->openTag($form); ?>

            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('descripcion')); ?>
                <?= $this->formElement($form->get('descripcion')); ?>
                <?= $this->formElementErrors($form->get('descripcion')); ?> 
            </div>
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('costo')); ?>
                <?= $this->formElement($form->get('costo')); ?>
                <?= $this->formElementErrors($form->get('costo')); ?> 
            </div>
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('cant_animales')); ?>
                <?= $this->formElement($form->get('cant_animales')); ?>
                <?= $this->formElementErrors($form->get('cant_animales')); ?> 
            </div>
            
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

             Modal content
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Editar datos del servicio</h4>
                </div>
                <div class="modal-body">
                    <p>
                        ¿Estas seguro de guardar los cambios?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-defaul">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a data-toggle="modal" data-target="#myModal"><img src="<?= $this->basePath('img/crm/Aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>

                        </div>
                        <div class="ficha-cliente-label">
                            <label>Guardar</label>
                        </div>
                    </div>

                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('servicio', ['action' => 'index']) ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->

<?= $this->form()->closeTag(); ?>

