<?php
$this->headTitle('Servicios');

?>
<script src="js/functions.js"> </script>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                SERVICIOS DE LA EMPRESA
            </div>
            <div class="panel panel-body">
                <div class="col-md-12">
                    <div class="table-responsive">
                            <table id="tabla_servicios" class="table table-bordred table-striped">
                            <thead>
                                <tr>
                                    <th class="th-sm">Nombre</th>
                                    <th class="th-sm">Categoria</th>
                                    <th class="th-sm">Precio</th>
                                    <th class="th-sm">Descuento</th>
                                    <th class="th-sm">Precio final IVA</th>
                                    <th class="th-sm">Precio final IVA DTO</th>
                                    <th></th>
                                </tr>
                            
                            </thead>

                            <?php foreach ($servicios as $servicio) : ?>
                                <tr>
                                    <td><?php echo ($servicio->getNombre()); ?></td>
                                    <td><?php echo ($servicio->getCategoriaNombre()); ?></td>
                                    <td><?php echo  money_format("$ %n",($servicio->getPrecio())); ?></td>
                                    <td><?php echo ($servicio->getDescuento()); ?></td>
                                    <td><?php echo  money_format("$ %n",($servicio->getPrecio_final_iva())); ?></td>
                                    <td><?php echo  money_format("$ %n",($servicio->getPrecio_final_iva_dto())); ?></td>
                                    <td class="table-items-right"> 
                                    <a class="btn btn-default" href="<?= $this->url('gestionProductosServicios/gestionServicios/editar', ['action' => 'edit', 'tipo'=>'servicio','id' => $servicio->getId()]); ?>">
                                        <span class="glyphicon glyphicon-pencil" ></span> 
                                    </a>
                                    <button name="<?= $servicio->getId() ?>" id="<?= $servicio->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $servicio->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                                </td>
                                <!-- Modal -->
                                <div id="myModal<?= $servicio->getId() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Borrar cliente</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Estas seguro de borrar el servicio?
                                                    "<?= $this->escapeHtml($servicio->getNombre()) ?>"

                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/eliminar', ['action' => 'remove', 'id' => $servicio->getId()]); ?>" class="btn btn-default">Borrar</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>  
            </div>
        </div>
    </div>
    <?php
        echo $this->paginationControl($servicios, 'Sliding', // All, Elastic, Jumping, Sliding
                    'search_pagination_servicio.phtml', $this->url('servicio/page', ['action' => 'index', 'id' => 1]));    ?>
</div>




<!-- Fin: Datos de la empresa -->
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/agregar', ['tipo'=>'servicio']); ?>">
                    <img src="<?= $this->basePath('img/crm/servicio_add_n.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Agregar</label><br>
                <label>Servicio</label>
            </div>
        </div>
        
        <div class="col ficha-cliente-p img-centrar">
            <div>
            <a href="<?= $this->url('gestionProductosServicios/gestionServicios') ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha zoom">
            </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->