<?php
$this->headTitle('Servicios');
?>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script>
    $(document).ready(function() {
        $('#tabla_servicios').DataTable({
            "order": [0, 'desc'],

            "language": {
                "url": "/json/spanish.json"
            }
        });
    });
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios">Productos y Servicios</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios/servicios">Servicios</a></li>
            <li class="breadcrumb-item active" aria-current="page">Listado</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
        style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<script src="js/functions.js"> </script>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO SERVICIOS
            </div>
            <div class="panel panel-body">
                <div class="col-md-12">
                    <div class="table-responsive">
                            <table id="tabla_servicios" class="display">
                            <thead>
                                <tr>
                                    <th class="th-sm">Código</th>
                                    <th class="th-sm">Nombre</th>
                                    <th class="th-sm">Categoria</th>
                                    <th class="th-sm">Precio</th>
                                    <th class="th-sm">Descuento</th>
                                    <th class="th-sm">Precio final IVA</th>
                                    <th class="th-sm">Precio final IVA DTO</th>
                                    <th class="col-btn-width"></th>
                                </tr>
                            </thead>

                            <?php foreach ($servicios as $servicio) :
                                $bien = $servicio->getBien();
                            ?>
                                <tr>
                                    <td><?php echo ($bien->getCodigo()); ?></td>
                                    <td><?php echo ($bien->getNombre()); ?></td>
                                    <td><?php echo ($bien->getCategoriaNombre()); ?></td>
                                    <td align="right"><?php echo "$ " . number_format($bien->getPrecio(), 2, ",", "."); ?></td>
                                    <td align="center"><?php echo ($bien->getDescuento() . " %"); ?></td>
                                    <td align="right"><?php echo "$ " . number_format($bien->getPrecio_final_iva(), 2, ",", "."); ?></td>
                                    <td align="right"><?php echo "$ " . number_format($bien->getPrecio_final_iva_dto(), 2, ",", "."); ?></td>
                                    <td>
                                        <div class="pull-right">
                                            <a class="btn btn-default btn-sm" href="<?= $this->url('gestionProductosServicios/gestionServicios/editar', ['action' => 'edit', 'tipo'=>'servicio','id' => $servicio->getId()]); ?>">
                                                <span class="glyphicon glyphicon-pencil" ></span> 
                                            </a>
                                            <button name="<?= $servicio->getId() ?>" id="<?= $servicio->getId() ?>" type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal<?= $servicio->getId() ?>"><span class="glyphicon glyphicon-trash" ></span></button>
                                        </div>
                                    </td>
                                <!-- Modal -->
                                <div id="myModal<?= $servicio->getId() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Borrar servicio</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Estas seguro de borrar el servicio?
                                                    "<?= $this->escapeHtml($servicio->getNombre()) ?>"

                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/eliminar', ['action' => 'remove', 'id' => $servicio->getId()]); ?>" class="btn btn-default">Borrar</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/agregar', ['tipo'=>'servicio']); ?>">
                    <img src="<?= $this->basePath('img/crm/servicio_add_n.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Agregar</label><br>
                <label>Servicio</label>
            </div>
        </div>
        
        <div class="col ficha-cliente-p img-centrar">
            <div>
            <a href="<?= $volver ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha zoom">
            </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->