<?php
$this->headTitle('Edit Usuario');

$form->get('nombre')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Ingresar Usuario'
]);

$form->get('telefono')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Ingresar Teléfono'
]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
]);

$form->get('skype')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Ingresar skype'
]);

$form->get('submit')
        ->setAttributes(['class' => 'btn btn-info'])
        ->setValue('Guardar');

$form->prepare();
?>


<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">Usuario Nuevo</div>
        </div>
    </div>
</div>

<?= $this->form()->openTag($form); ?>
<div class="container">
    <div class="row">
        <div class="row form-row">
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('nombre')); ?>
                <?= $this->formElement($form->get('nombre')); ?>
                <?= $this->formElementErrors($form->get('nombre')); ?>
            </div>
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('telefono')); ?>
                <?= $this->formElement($form->get('telefono')); ?>
                <?= $this->formElementErrors($form->get('telefono')); ?>
            </div>
        </div>
        <div class="row form-row">
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('skype')); ?>
                <?= $this->formElement($form->get('skype')); ?>
                <?= $this->formElementErrors($form->get('skype')); ?>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Editar usuario</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea editar los datos de este usuario?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>   
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal"><img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                class="img-rounded img-responsive img-texto-derecha img-submenu-sm" role="button"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('clientes/ficha', ['action' => 'ficha', 'id' => $id]) ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->
<?= $this->form()->closeTag(); ?>
