<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <script type="text/javascript" src="crm/ejecutivo.js"></script>
    </head>

    <div class="container">
        <div class="row">
            <h2>Listado de Ejecutivos</h2><br>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="input-group">
                    <input type="text" name="usuario" class="form-control" placeholder="Buscar ejecutivo">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-hover table-condensed" id="t-ejecutivos">
                        <thead>
                            <tr>
                                <th class="th-sm" onclick="sortTableString(1, 'tabla_evento')">
                                    <i class="fa fa-sort float-right" aria-hidden="true"></i> Apellido
                                </th>
                                <th class="th-sm">Nombre
                                </th>
                                <th class="th-sm">Email
                                </th>
                                <th class="th-sm">Usuario
                                </th>
                                <th class="th-sm"">Clave
                                </th>
                                <th><h4></h4></th>    
                            </tr>
                        </thead>
                        <tbody> 
                            <?php
                            if (isset($ejecutivos)) {
                                foreach ($ejecutivos as $ejecutivo) {
                                    echo ('<tr>');
                                    echo ('<td>');
                                    echo ($ejecutivo->getApellido());
                                    echo ('</td>');
                                    echo ('<td>');
                                    echo ($ejecutivo->getNombre());
                                    echo ('</td>');
                                    echo ('<td>');
                                    echo ($ejecutivo->getMail());
                                    echo ('</td>');
                                    echo ('<td>');
                                    echo ($ejecutivo->getUsuario());
                                    echo ('</td>');
                                    echo ('<td>');
                                    echo ($ejecutivo->getClave());
                                    echo ('</td>');
                                    ?>    
                                <td> 
                                    <a class="btn btn-default" href="<?= $this->url('ejecutivos', ['action' => 'edit', 'id' => $ejecutivo->getId_ejecutivo()]); ?>">
                                        <span class="glyphicon glyphicon-pencil" ></span> 
                                    </a>
                                    <button name="<?= $ejecutivo->getId_ejecutivo() ?>" id="<?= $ejecutivo->getId_ejecutivo() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $ejecutivo->getId_ejecutivo() ?>">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>
                                </td>
                                <!-- Modal -->
                                <div id="myModal<?= $ejecutivo->getId_ejecutivo() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Borrar cliente</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    ¿Está seguro de eliminar el ejecutivo:
                                                    "<?= $this->escapeHtml($ejecutivo->getNombre()) ?>
                                                    <?= $this->escapeHtml($ejecutivo->getApellido()) ?>"
                                                    de forma permanente?
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a class="btn btn-default" href="<?= $this->url('ejecutivos', ['action' => 'delete', 'id' => $ejecutivo->getId_ejecutivo()]); ?>">
                                                    Aceptar
                                                </a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                </td>
                                <?php
                                echo ('</tr>');
                            }
                            ?>
                            </tbody>
                        </table>
                        <?php
                        echo $this->paginationControl($ejecutivos, 'Sliding', // All, Elastic, Jumping, Sliding
                                'search_pagination.phtml', $this->url('ejecutivos/page', ['action' => 'index', 'id' => 1]));
                    }
                    ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <a class="btn btn-default" href="<?= $this->url('home') ?>">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </a>
                <a class="btn btn-default" href="<?= $this->url('ejecutivos', ['action' => 'add']); ?>">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo Ejecutivo
                </a>
            </div>
        </div>

    </div>