<?php
$this->headTitle('View Ejecutivo');


?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View Ejecutivo</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Apellido:</th>
                <td><?= $this->escapeHtml($ejecutivo->getApellido()) ?></th>
            </tr>
            <tr>
                <th>Nombre:</th>
                <td><?= $this->escapeHtml($ejecutivo->getNombre()) ?></th>
            </tr>
            <tr>
                <th>E-email:</th>
                <td><?= $this->escapeHtml($ejecutivo->getMail()) ?></th>
            </tr>
            <tr>
                <th>Usuario:</th>
                <td><?= $this->escapeHtml($ejecutivo->getUsuario()) ?></th>
            </tr>
            <tr>
                <th>Clave:</th>
                <td><?= $this->escapeHtml($ejecutivo->getClave()) ?></th>
            </tr>
        </table>
    </div>
</div>