<?php
$this->headTitle('Editar Pais');

$form->get('nombre_pais')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Editar Pais <?= $this->escapeHtml($pais->getId()) ?></h1>
            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('nombre_pais')); ?>
                        <?= $this->formElement($form->get('nombre_pais')); ?>
                        <?= $this->formElementErrors($form->get('nombre_pais')); ?>                  
                    </div>

                    <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
