<script src="js/functions.js"></script>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">Listado de países</div>
        </div>
    </div>
</div>
<div class="container">
    <form method="post">
        <div class="row form-row">
            <div class="form-group col-md-4">
                <input type="text" class="form-control" name="nombre_pais" placeholder="Ingresar País">
            </div>
            <div class="form-group col-md-4">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                    <span class="glyphicon glyphicon-plus" ></span> Agregar País
                </button>
            </div>
        </div>
        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Agregar país</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Está seguro que desea agregar este país?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default">Aceptar</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="tabla_pais" class="table table-bordred table-striped">
                    <thead>
                        <tr>
                            <th>País</th>
                            <th></th>
                        </tr>
                    </thead>
                    <?php foreach ($paises as $pais) : ?>
                        <tr>
                            <td><?php echo ($pais->getNombre()); ?></td>
                            <td> <a class="btn btn-default" href="<?= $this->url('pais', ['action' => 'edit', 'id' => $pais->getId()]); ?>"> <span class="glyphicon glyphicon-pencil" ></span> </a>                            
                                <button name="<?= $pais->getId() ?>" id="<?= $pais->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $pais->getId() ?>">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>
                            </td>
                            <!-- Modal -->
                        <div id="myModal<?= $pais->getId() ?>" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Borrar cliente</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                           ¿Está seguro que desea eliminar el pais: 
                                            "<?= $this->escapeHtml($pais->getNombre()) ?>"?
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="<?= $this->url('pais', ['action' => 'remove', 'id' => $pais->getId()]); ?>" class="btn btn-default">Aceptar</a>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>  
    </div>
</div>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->