<?php
$this->headTitle('Editar Profesión');
$form->get('nombre')->setAttributes([
    'class' => 'form-control'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                EDITAR PROFESIÓN
            </div>
            <div class="panel panel-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-4">
                                    <?= $this->form()->openTag($form); ?>
                                     <div class="form-group">
                                        <?= $this->formLabel($form->get('nombre')); ?>
                                        <?= $this->formElement($form->get('nombre')); ?>
                                        <?= $this->formElementErrors($form->get('nombre')); ?>                  
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <?= $this->formLabel($form->get('descripcion')); ?>
                                        <?= $this->formElement($form->get('descripcion')); ?>
                                        <?= $this->formElementErrors($form->get('descripcion')); ?>                  
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <button type="submit" class="btn btn-default">Aceptar</button>
                                <a href="<?= $this->url('profesion', ['action' => 'index']);?>" type="button">
                                    <span class="btn btn-default">Cancelar</span></a>
                                <?= $this->form()->closeTag(); ?>
                            </div>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    

