<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script>
    $(document).ready(function() {
        $('#tabla_profesiones').DataTable({
            "order": [0, 'desc'],

            "language": {
                "url": "/json/spanish.json"
            }
        });
    });
</script>

<?php
if (isset($_SESSION['MENSAJES']['profesion_cliente'])) {
    if ($_SESSION['MENSAJES']['profesion_cliente']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['profesion_cliente_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['profesion_cliente_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['profesion_cliente'] = null;
    $_SESSION['MENSAJES']['profesion_cliente_msj'] = null;
}
?>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionClientes'); ?>">Clientes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Profesiones</li>
        </ol>
    </nav>
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
    style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('gestionClientes/profesion'); ?>" id="volver">Volver</a></li>
    </ol>
</div>

<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Profesion -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO PROFESIONES
                <a data-toggle="collapse" data-parent="#accordion" href="#add_profesion" 
                    aria-expanded="true" aria-controls="add_profesion">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
            <div class="panel panel-body">
                <div class="collapse" id="add_profesion">
                    <form method="post">
                        <div class="row form-row">
                            <div class="form-group col-md-4">
                                <label>Nombre de Profesión</label>
                                <input type="text" class="form-control form-margen" name="nombre" placeholder="Ingresar Profesión">
                            </div>
                            <div class="form-group col-md-4">
                                <label>Descripción</label>
                                <input type="text" class="form-control form-margen" name="descripcion" placeholder="Descripción">
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="form-group col-md-4">
                                <button type="button" class="btn btn-default form-margen" data-toggle="modal" data-target="#myModal">
                                    <span class="glyphicon glyphicon-plus" ></span> Agregar Profesión
                                </button>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Agregar profesión</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>¿Está seguro que desea agregar esta profesión?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-default">Aceptar</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table id="tabla_profesiones" class="display">
                                <thead>
                                    <tr>
                                        <th>Nombre de Profesión</th>
                                        <th>Descripción</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    if (isset($profesiones)) {
                                        foreach ($profesiones as $profesion):
                                            ?>
                                            <tr>
                                                <td><?php echo ($profesion->getNombre()); ?></td>
                                                <td><?php echo ($profesion->getDescripcion()); ?></td>
                                                <td class="table-items-right">
                                                    <a class="btn btn-default" href="<?= $this->url('profesion/editar', ['action' => 'edit', 'id' => $profesion->getId()]); ?>">
                                                        <span class="glyphicon glyphicon-pencil" ></span> 
                                                    </a>
                                                    <button name="<?= $profesion->getId() ?>" id="<?= $profesion->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $profesion->getId() ?>">
                                                        <span class="glyphicon glyphicon-remove" ></span>
                                                    </button>
                                                </td>
                                                <!-- Modal -->
                                        <div id="myModal<?= $profesion->getId() ?>" class="modal fade" role="dialog">
                                            <div class="modal-dialog">
                                                <!-- Modal content-->
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title">Eliminar profesión</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>
                                                            ¿Está seguro que desea eliminar la profesión: 
                                                            "<?= $this->escapeHtml($profesion->getNombre()) ?>"?
                                                        </p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <a href="<?= $this->url('profesion/borrar', ['action' => 'remove', 'id' => $profesion->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                                                        <span class="btn btn-default">Aceptar</span></a>
                                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        </tr>
                                    <?php endforeach;} ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        </div>                
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->