<?php
//var_dump(json_decode($json), true); die();

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

	// Page footer
	public function Footer() {
		// Position at 15 mm from bottom
        $this->SetY(-15);
        
		// Set font
        $this->SetFont('helvetica', '', 8);
        
		// Page number
        $this->Cell(0, 10, 'Pag '.$this->getPageNumGroupAlias().'/'.$this->getPageGroupAlias(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
     
}

// pdf object
// $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf = new MYPDF('P','mm','A4');

// remove default header and footer
// $pdf->setPrintHeader(false);
// $pdf->setPrintFooter(false);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 20);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Generates Original / Duplicate / Triplicate
for ($i=1; $i <= 1; $i++) {  
    switch ($i){
        case 1:
            $copia = "ORIGINAL";
            // Start First Page Group
            $pdf->startPageGroup();
        break;
        // case 2:
        //     $copia = "DUPLICADO";
        //     // Start First Page Group
        //     $pdf->startPageGroup();
        // break;
        // case 3;
        //     $copia = "TRIPLICADO";
        //     // Start First Page Group
        //     $pdf->startPageGroup();
        // break;
        default :
        break;
    }
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */


    // add a page
    $pdf->AddPage();

    // start html document
    $htmlData = '
        <head>

        </head
        <body>';
    $pdf->writeHTML($htmlData, true, false, false, false, '');

    // set font
    $pdf->SetFont('helvetica', '', 8);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    // Titulo
    $html = '
        <table border="0" cellspacing="0" cellpadding="3">
            <tbody>
                <tr>
                    <td><strong style="font-size: 12px; text-align: center;">&nbsp;'. $copia .'</strong></td>
                </tr>
            </tbody>
        </table>
    ';
    // output the HTML content
    $pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
    $pdf->Ln(1);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */


    // Datos Empresa y Comprobante
    $html = '
        <table border="0" cellspacing="0" cellpadding="4">
            <thead>
                <tr style="font-size: 14px; font-weight: bold;">
                    <th align="center" width="45%">'. $empresa->getNombre() .'</th>
                    <th width="2%"></th>
                    <th align="center" width="6%" border="0.5">&nbsp;R</th>
                    <th width="2%"></th>
                    <th align="left" width="45%">RECIBO</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="45%"><strong>Razón Social: </strong>'. $empresa->getRazon_social() .'</td>
                    <th width="2%"></th>
                    <td width="3%" style="border-right: 0.5px solid black;"></td>
                    <td width="3%"></td>
                    <th width="2%"></th>
                    <td width="45%"><strong>Punto de Venta: </strong>'. str_pad($empresa->getPunto_venta(), 5, "0", STR_PAD_LEFT) .'&nbsp;<strong> Comp. Nro: </strong>'. str_pad($numCobro, 6, "0", STR_PAD_LEFT) .'</td>
                </tr>
                <tr>
                    <td width="45%"><strong>Domicilio Comercial: </strong>'. $empresa->getDireccion() .'</td>
                    <th width="2%"></th>
                    <td width="3%" style="border-right: 0.5px solid black;"></td>
                    <td width="3%"></td>
                    <th width="2%"></th>
                    <td width="45%"><strong>Fecha de Emisión: </strong>'. $transaccion->getFecha_transaccion()->format('d/m/Y') .'</td>
                </tr>
                <tr>
                    <td width="45%"><strong>Condición frente al IVA: </strong>'. $empresa->getNombreCondicionIva() .'</td>
                    <th width="2%"></th>
                    <td width="3%" style="border-right: 0.5px solid black;"></td>
                    <td width="3%"></td>
                    <th width="2%"></th>
                    <td width="45%"><strong>CUIT: </strong>'. $empresa->getCuit_cuil() .'</td>
                </tr>
                <tr>
                    <td width="45%"></td>
                    <th width="2%"></th>
                    <td width="3%" style="border-right: 0.5px solid black;"></td>
                    <td width="3%"></td>
                    <th width="2%"></th>
                    <td width="45%"><strong>Ingresos Brutos: </strong>'. $empresa->getIngresos_brutos() .'</td>
                </tr>
                <tr>
                    <td width="45%"></td>
                    <th width="2%"></th>
                    <td width="3%" style="border-right: 0.5px solid black;"></td>
                    <td width="3%"></td>
                    <th width="2%"></th>
                    <td width="45%"><strong>Fecha de Inicio de Actividades: </strong>'. $empresa->getFecha_inicio_actividades_formato() .'</td>
                </tr>
            </tbody>
        </table>
    ';
    // output the HTML content
    $pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
    $pdf->Ln(1);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    if( (is_null($persona->getRazon_social())) || ($persona->getRazon_social() == "") ){
        $nombre_razonsocial = $persona->getNombre();
    } else {
        $nombre_razonsocial = $persona->getRazon_social();
    };

    // Datos del Comprador
    $html = '
        <table border="0" cellspacing="0" cellpadding="3">
            <tbody>
                <tr>
                    <td><strong>CUIT: </strong>'. $persona->getCuit_cuil() .'</td>
                    <td><strong>Apellido y Nombre / Razón Social: </strong>'. $nombre_razonsocial .'</td>
                </tr>
                <tr>
                    <td><strong>Condición frente al IVA: </strong>'. $persona->getNombreCondicionIva() .'</td>
                    <td><strong>Domicilio Comercial: </strong>'. $persona->getDireccion_facturacion() .'</td>
                </tr>
                <tr>
                    <td><strong>Condición de Venta: </strong>'. $transaccion->getNombreFormaPago() .'</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    ';
    // output the HTML content
    $pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
    $pdf->Ln(1);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    // make the table items
    $html = '
        <table border="0.1" cellspacing="0" cellpadding="3">
            <thead>
                <tr bgcolor="silver" style="font-weight: bold;" nobr="true">
                    <th border="0.5" align="center" width="30%">Valores</th>
                    <th border="0.5" align="center" width="30%">Entidad</th>
                    <th border="0.5" align="center" width="10%">Nro</th>
                    <th border="0.5" align="center" width="15%">Importe</th>
                    <th border="0.5" align="center" width="15%">Fecha Acred</th>
                </tr>
            </thead>
            <tbody>
    ';

    // load json data
    $data = json_decode($json);
    $subtotal = 0; $imp_dto = 0;

    $count = 0;
    foreach($data as $item){
        $subtotal = $subtotal + $item->Totales;
        $imp_dto = $item->Bien->Precio * ($item->Dto/100);
        $html .= '
                <tr nobr="true">
                    <td align="center" width="30%">' . "" . '</td>
                    <td align="center" width="30%">' . "" .'</td>
                    <td align="center" width="10%">' . "" .'</td>
                    <td align="center" width="15%">' . "" .'</td>
                    <td align="center" width="15%">' . "" .'</td>
                </tr>
        ';
    };

    // end of table items
    $html .= '
            </tbody>
        </table>
    ';

    // output the HTML content
    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->Ln(1);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    // $pdf->writeHTML($pdf->getY(), true, false, true, false, '');

    // Position in mm from bottom
    if($pdf->getY() > 206 ){
        // $pdf->writeHTML($pdf->getY(), true, false, true, false, '');
        $pdf->AddPage();
    }
    
    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    $pdf->SetY(-90);

    // TOTAL EN LETRAS
    $html = '
        <table border="0" cellspacing="0" cellpadding="3">
            <tbody>
                <tr>
                    <td style="font-size: 14px;"><strong>Total: $ </strong>'. number_format($transaccion->getMonto(), 2, ",", ".") .'</td>
                </tr>
                <tr>
                    <td style="font-size: 9px;"><strong>Recibí/mos la suma de: </strong>'. $cobro->getImporte_letras() .'</td>
                </tr>
                <tr>
                    <td style="font-size: 9px;"><strong>Por concepto de: </strong>'. $cobro->getConcepto() .'</td>
                </tr>
            </tbody>
        </table>
    ';
    // output the HTML content
    $pdf->writeHTMLCell(0, 0, '', '', $html, '', 1, 0, true, '', true);
    $pdf->Ln(20);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    // TOTAL + FIRMA
    $html = '
        <table border="0" cellspacing="0" cellpadding="3">
            <tbody>
                <tr>
                    <td>'. "" .'</td>
                    <td>'. "" .'</td>
                    <td style="border-bottom: 0.5px solid black;">'. "" .'</td>
                </tr>
                <tr>
                    <td>'. "" .'</td>
                    <td>'. "" .'</td>
                    <td align="center">'. "Firma y Aclaración" .'</td>
                </tr>
            </tbody>
        </table>
    ';
    // output the HTML content
    $pdf->writeHTMLCell(0, 0, '', '', $html, '', 1, 0, true, '', true);
    $pdf->Ln(10);

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    // DOCUMENTO NO OFICIAL
    $html = '<i style="font-size: 8px;">Documento no Oficial</i>';
    // output the HTML content
    if(!$transaccion->getOficial()){
        $pdf->writeHTMLCell(0, 0, '', '', $html, '', 1, 0, true, 'C', true);
        $pdf->Ln(1);
    }

    /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

    $htmlData = '</body></html>';
    $pdf->writeHTML($htmlData, true, false, false, false, '');

    // reset pointer to the last page
    $pdf->lastPage();

} // end foreach



//Close and output PDF document
$pdf->Output('example_006.pdf', 'I');

?>
