<?php
$this->headTitle('Agregar Evento');
$id_cliente = $this->cliente->getId();

date_default_timezone_set('America/Argentina/Buenos_Aires');

$date = date('d-m-Y');

$form->get('fecha_evento')->setAttributes([
    'class' => 'form-control',
    'disabled' => 'disabled',
    'value' => $date,
]);

$form->get('tipo_evento')->setAttributes([
    'class' => 'form-control',
    'value' => '',
]);


$form->get('id_cliente')->setAttributes([
    'class' => 'form-control',
    'value' => $id_cliente,
    'placeholder' => $id_cliente
]);

$form->get('id_ejecutivo')->setAttributes([
    'class' => 'form-control',
    'disabled' => 'disabled',
    'value' => $this->identity(),
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-danger']);

$form->prepare();
?>

<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>

<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">
                AGREGAR ACTIVIDAD
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <input hidden="" name="id_cliente" value="<?= $id_cliente ?>">
                <input hidden="" name="ejecutivo" value="<?= $this->identity() ?>">
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>Fecha</label>
                        <div class='input-group date' id='datetimepicker3'>
                            <input type='text' class="form-control" name="fecha_evento" value="<?= $date ?>"/>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('id_ejecutivo')); ?>
                        <?= $this->formElement($form->get('id_ejecutivo')); ?>
                        <?= $this->formElementErrors($form->get('id_ejecutivo')); ?> 
                    </div>
                    <div class="form-group col-md-3">
                        <label>Acción Comercial</label>
                        <select class="form-control" id="accion_comercial" name="accion_comercial">
                            <option value="" hidden="">Seleccionar</option>
                            <option value="-1">NO DEFINIDO</option>
                            <?php foreach ($transacciones as $tipo) : ?>
                                <option value="<?php echo ($tipo->getId()); ?>"><?php echo ($tipo->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label>Detalle</label>
                        <textarea name="detalle" class="form-control detalle-width" rows="4" placeholder="Ingresar detalle de actividad" required=""></textarea>
                    </div>
                </div>

                <!-- Modal -->
                <div id="myModal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Agregar actividad</h4>
                            </div>
                            <div class="modal-body">
                                <p>
                                    ¿Estas seguro de que quieres agregar la actividad?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-default">Aceptar</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>             
            </div>   
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                     class="img-rounded img-responsive img-texto-derecha img-submenu-sm" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('clientes/ficha', ['action' => 'ficha', 'id' => $id_cliente]) ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                     class="img-rounded img-responsive img-texto-derecha">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->