<?php
$this->headTitle('Agregar Evento');
$id_persona = $this->persona->getId();

date_default_timezone_set('America/Argentina/Buenos_Aires');
$date = date('d-m-Y');

$form->get('fecha_evento')->setAttributes([
    'class' => 'form-control',
    'disabled' => 'disabled',
    'value' => $date,
]);

$form->get('tipo_evento')->setAttributes([
    'class' => 'form-control',
    'value' => '',
]);

$form->get('id_cliente')->setAttributes([
    'class' => 'form-control',
    'value' => $id_persona,
    'placeholder' => $id_persona
]);

$form->get('id_ejecutivo')->setAttributes([
    'class' => 'form-control',
    'disabled' => 'disabled',
    'value' => $this->identity(),
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-danger']);
$form->prepare();
?>

<!-- Datetime Picker -->
<script language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
<script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">

<script type="text/javascript">
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>
<!-- Fin -> Datetime Picker -->

<?php

// print_r($tipoPersona); die();

$url =""; $label="";
if ($tipoPersona == "cliente"){
    $url = "/clientes";
    $url2= "/clientes/listado";
    $url3= "/clientes/ficha";
    $label = "Clientes";
    $label2 = "Listado";
    $label3 = "Ficha Cliente";
}
else {
    $url = "/proveedores";
    $url2 = "/proveedores/listado";
    $url3= "/proveedores/ficha";
    $label = "Proveedores";
    $label2 = "Listado";
    $label3 = "Ficha Cliente";
}

?>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="<?php echo ($url);?>"><?php echo ($label);?></a></li>
            <li class="breadcrumb-item"><a href="<?php echo ($url2);?>"><?php echo ($label2);?></a></li>
            <li class="breadcrumb-item <?php if($tipoPersona != 'cliente'){echo 'hidden';} ?>"><a href="<?= $this->url('clientes/ficha', ['tipo' => 'cliente', 'id' => $id_persona]) ?>">Ficha Cliente</a></li>
            <li class="breadcrumb-item <?php if($tipoPersona != 'proveedor'){echo 'hidden';} ?>"><a href="<?= $this->url('proveedores/ficha', ['tipo' => 'proveedor', 'id' => $id_persona]) ?>">Ficha Proveedor</a></li>
            <li class="breadcrumb-item active" aria-current="page">Acción Comercial</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?php echo ($url);?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                AGREGAR EVENTO
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <input hidden="" name="id_cliente" value="<?= $id_persona ?>">
                <input hidden="" name="ejecutivo" value="<?= $this->identity() ?>">
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>Fecha</label>
                        <div class='input-group date' id='datetimepicker3'>
                            <input type='text' class="form-control" name="fecha_evento" value="<?= $date ?>"/>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <?= $this->formLabel($form->get('id_ejecutivo')); ?>
                        <?= $this->formElement($form->get('id_ejecutivo')); ?>
                        <?= $this->formElementErrors($form->get('id_ejecutivo')); ?> 
                    </div>
                    <div class="form-group col-md-3">
                        <label>Acción Comercial</label>
                        <select class="form-control" id="accion_comercial" name="accion_comercial" required>
                            <option value="" hidden="">Seleccionar</option>
                            <!-- <option value="-1">No definido</option> -->
                            <?php foreach ($tipos as $tipo) : ?>
                                <option value="<?php echo ($tipo->getId()); ?>"><?php echo ($tipo->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="row form-row">
                        <div class="form-group col-md-8">
                            <label>Detalle</label>
                            <textarea name="detalle" id ="detalle" class="form-control" rows="4" placeholder="Ingresar detalle de la acción comercial" required=""></textarea>
                        </div>
                    </div>
                <!-- Modal -->
                <div id="myModal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Agregar evento</h4>
                            </div>
                            <div class="modal-body">
                                <p>¿Está seguro que desea agregar este evento?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-default">Aceptar</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>             
            </div>   
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                     class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
               <a href="<?= $volver?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                     class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->