
<?php
$this->headTitle('Editar Evento');

$form->get('fecha_evento')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);

$form->get('tipo_evento')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);

$form->get('id_cliente')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);

$form->get('id_ejecutivo')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Editar Evento <?= $this->escapeHtml($evento->getId()) ?></h1>

            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('fecha_evento')); ?>
                        <?= $this->formElement($form->get('fecha_evento')); ?>
                        <?= $this->formElementErrors($form->get('fecha_evento')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('tipo_evento')); ?>
                        <?= $this->formElement($form->get('tipo_evento')); ?>
                        <?= $this->formElementErrors($form->get('tipo_evento')); ?>                  
                    </div>


                    <div class="form-group">
                        <?= $this->formLabel($form->get('id_cliente')); ?>
                        <?= $this->formElement($form->get('id_cliente')); ?>
                        <?= $this->formElementErrors($form->get('id_cliente')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('id_ejecutivo')); ?>
                        <?= $this->formElement($form->get('id_ejecutivo')); ?>
                        <?= $this->formElementErrors($form->get('id_ejecutivo')); ?>                  
                    </div>

                    <?= $this->formElement($form->get('submit')); ?>

                    <?= $this->form()->closeTag(); ?>
                </div>    
            </div>  
        </div>
    </div>
</div>


