
<?php
$this->headTitle('Editar Licencia');

$form->get('nombre_tipoevento')->setAttributes([
    'class' => 'form-control'
]);

$form->get('version_tipoevento')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Editar Licencia <?= $this->escapeHtml($tipoevento->getId()) ?></h1>

            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>
                   <div class="form-group">
                        <?= $this->formLabel($form->get('nombre_tipoevento')); ?>
                        <?= $this->formElement($form->get('nombre_tipoevento')); ?>
                        <?= $this->formElementErrors($form->get('nombre_tipoevento')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('version_tipoevento')); ?>
                        <?= $this->formElement($form->get('version_tipoevento')); ?>
                        <?= $this->formElementErrors($form->get('version_tipoevento')); ?>                  
                    </div>

                    <?= $this->formElement($form->get('submit')); ?>

                    <?= $this->form()->closeTag(); ?>
                </div>    
            </div>   
        </div>
    </div>
</div>
    

