<script src="js/functions.js"> </script>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <h3>Listado de tipoeventos</h3>

                <table id="tabla_tipoevento" class="table table-bordred table-striped">

                    <thead>

                        <tr>
                            <th class="th-sm"  onclick="sortTableNumeric(0, 'tabla_tipoevento')">Id
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-sm" onclick="sortTableString(1,'tabla_tipoevento')">Nombre
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-sm" onclick="sortTableNumeric(2,'tabla_tipoevento')">Version
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th></th>
                            
                        </tr>
                    </thead>
                        <?php foreach ($tipoeventos as $tipoevento) : ?>
                        <tr>
                            <td><?php echo($tipoevento->getId()); ?></td>
                                <td><?php echo ($tipoevento->getNombre()); ?></td>
                                <td><?php echo ($tipoevento->getVersion()); ?></td>
                                <td> <a class="btn btn-info" href="<?= $this->url('tipoevento', ['action' => 'edit', 'id' => $tipoevento->getId()]); ?>">
                                        <span class="glyphicon glyphicon-pencil" ></span> 
                                </a>

                                  <button name="<?= $tipoevento->getId() ?>" id="<?= $tipoevento->getId() ?>" type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal<?= $tipoevento->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                                <!-- Modal -->
                        <div id="myModal<?= $tipoevento->getId() ?>" class="modal fade" role="dialog">
                            <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Borrar cliente</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                            Estas seguro de borrar la tipoevento?
                                            "<?= $this->escapeHtml($tipoevento->getNombre()) ?>"
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="<?= $this->url('tipoevento', ['action' => 'remove', 'id' => $tipoevento->getId()]); ?>" class="btn btn-primary">Borrar</a>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </tr>

                    <?php endforeach; ?>
                </table>
            </div>
            <p>
                <a class="btn btn-default" href="
                   <?= $this->url('tipoevento', ['action' => 'add']); ?>">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Licencia
                </a>
            </p>

        </div>  
    </div>
</div>
