<form method="post">
    <div class="container margen">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading titulo-espaciado">
                    DATOS PARTICULARES DE LICENCIA
                </div>
                <div class="panel-body">
                    <!-- 1ra fila -->
                    <div class="row form-row">
                        <div class="form-group col-md-6">
                            <label>Nombre</label>
                            <input type="text" required="true" class="form-control" name="nombre" 
                                placeholder="Ingresar nombre">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Descripción</label>
                            <input type="text" class="form-control" name="descripcion" 
                                placeholder="Ingresar descripcion">
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-6">
                            <label>Código de Licencia</label>
                            <input type="text" class="form-control" name="codigo_licencia"
                                placeholder="Ingresar código de producto">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Código de Barras</label>
                            <input type="text" class="form-control" name="codigo_barras" 
                                placeholder="Ingresar código de barras">
                        </div>
                    </div>
                    <!-- 2da fila -->
                    <div class="row form-row">
                        <div class="form-group col-md-6">
                        <label>Categoría</label>
                            <select class="form-control" id="categoria" name="categoria">
                                <option value="" hidden="">Seleccionar Categoría</option>
                                <option value="-1">NO DEFINIDO</option>
                                <?php foreach ($categorias as $categoria) : ?>
                                    <option value="<?= $categoria->getId(); ?>">
                                        <?= $categoria->getNombre(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Proveedor</label>
                            <select class="form-control" id="proveedor" name="proveedor">
                                <option value="" hidden="">Seleccionar Proveedor</option>
                                <option value="1">...</option>
                                <option value="2">...</option>
                                <option value="-1">NO DEFINIDO</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>   
        </div>

        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading titulo-espaciado">
                    DATOS ECONÓMICOS DE LICENCIA
                </div>
                <div class="panel-body">
                    <!-- 1ra fila -->
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <label>Precio</label>
                            <input type="text" class="form-control" name="precio" id="precio_venta" 
                                value=0 onkeypress="return justNumbers(event);" onkeyup="calcularPrecios()">
                        </div>
                        <div class="form-group col-md-2">
                            <label>% Descuento</label>
                            <input type="text" class="form-control" name="descuento" id="descuento" value=0
                                onkeypress="return justNumbers(event);" onkeyup="calcularPrecios()">
                        </div>
                        <div class="form-group col-md-2">
                        <label>% IVA</label>
                            <select class="form-control" name="iva" id="iva"
                            onkeypress="return justNumbers(event);" onchange="calcularPrecios()">
                            <option value="0" hidden="">Seleccionar IVA</option>
                            <?php foreach ($ivas as $iva) : ?>
                                <option value="<?php  echo  ($iva->getValor()); ?>">
                                <?php if ($iva->getId()==1){echo ("Excento");} 
                                    else {echo ($iva->getValor());} ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Total IVA $</label>
                            <input type="text" class="form-control" name="iva_gravado" id="iva_total" value=0 readonly>
                        </div>
                    
                    </div>
                    <!-- 3ra fila -->
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <label>Precio Público con Dto.</label>
                            <input type="text" class="form-control" name="precio_final_dto" id="precio_publico_dto" value=0 readonly>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Precio Público + IVA</label>
                            <input type="text" class="form-control" name="precio_final_iva" id="precio_publico_iva" value=0 readonly>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Precio Público +IVA con Dto.</label>
                            <input type="text" class="form-control" name="precio_final_iva_dto" id="precio_publico_iva_dto" value=0 readonly>
                        </div>
                    </div>
                </div>
            </div>   
        </div>

        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Agregar servicio</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Está seguro que desea agregar este servicio?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default">Aceptar</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Fin Modal -->
    </div>
</form>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar"> 
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>                   
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionEmpresa/gestionLicencias') ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" 
                class="img-rounded img-responsive img-texto-derecha"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>       
</div>
<!-- Fin: Panel Botones -->