<?php 
header("Pragma: public");
header("Expires: 0");
$filename = "Backup_Licencias.xls";
//header("Content-type: application/x-msdownload; charset=utf8");
header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=$filename");
header("Pragma: no-cache");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
?>

<table>
    <tbody>
        <tr>
            <td><?php echo(utf8_decode("Licencia")); ?></td>
            <td><?php echo(utf8_decode("Precio"));?></td>
            <td><?php echo(utf8_decode("IVA (%)"));?></td>
            <td><?php echo(utf8_decode("Precio final con iva"));?></td>
            <td><?php echo(utf8_decode("Descuento (%)"));?></td>
            <td><?php echo(utf8_decode("Precio final con Iva y Dto."));?></td>
        </tr>
        <?php foreach ($resultado as $licencia): 
        ?>
            <tr>
                <td><?php echo(utf8_decode($licencia->getNombre())); ?></td>
                <td><?php echo(utf8_decode($licencia->getPrecio()));?></td>
                <td><?php echo(utf8_decode($licencia->getValorIva()));?></td>
                <td><?php echo(utf8_decode($licencia->getPrecio_final_iva()));?></td>
                <td><?php echo(utf8_decode($licencia->getDescuento()));?></td>
                <td><?php echo(utf8_decode($licencia->getPrecio_final_iva_dto()));?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>