<?php 
header("Pragma: public");
header("Expires: 0");
$filename = "Backup_Licencias.xls";
//header("Content-type: application/x-msdownload; charset=utf8");
header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=$filename");
header("Pragma: no-cache");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
?>

<table>
    <tbody>
        <?php foreach ($resultado as $licencia): 
        ?>
            <tr>
                <td><?php echo(utf8_decode($licencia->getNombre())); ?></td>
                <td><?php echo(utf8_decode($licencia->getPrecio_local()));?></td>
                <td><?php echo(utf8_decode($licencia->getPrecio_extranjero()));?></td>
                <td><?php echo(utf8_decode($licencia->getIva()));?></td>
                <td><?php echo(utf8_decode($licencia->getDescuento()));?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>