<?php
$this->headTitle('Editar Licencia');
$nombre_licencia = $form->get('nombre_licencia');
$form->get('nombre_licencia')->setAttributes([
    'class' => 'form-control',
    'value' => $licencia->getNombre(),
    'required' => '',  
]);
$form->get('precio_local')->setAttributes([
    'class' => 'form-control',
    'value' => $licencia->getPrecio_local(),
]);
$form->get('precio_extranjero')->setAttributes([
    'class' => 'form-control',
    'value' => $licencia->getPrecio_extranjero(),
]);
$form->get('descuento')->setAttributes([
    'class' => 'form-control',
    'value' => $licencia->getDescuento(),
]);
$form->get('iva')->setAttributes([
    'class' => 'form-control',
    'value' => $licencia->getIva(),
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>

<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">EDITAR LICENCIA</div>
        </div>
    </div>
</div>

<?= $this->form()->openTag($form); ?>
<div class="container">
    <div class="row form-row">
        <div class="form-group col-md-4">
            <label>Nombre de Licencia</label>
            <input type="text" class="form-control" value="<?= $licencia->getNombre() ?>" name="nombre_licencia" placeholder="Ingresar Licencia" required="">
        </div>
    </div>
    <div class="row form-row">
        <div class="form-group col-md-3">
            <label>Precio Local</label>
            <div class="form-inline">
                <input type="text" class="form-control licencia-md" value="<?= $licencia->getPrecio_local(); ?>" name="precio_local" placeholder="Ingresar precio" required=""> ARG
            </div>
        </div>
    </div>
    <div class="row form-row">
        <div class="form-group col-md-3">
            <label>Precio Extranjero</label>
            <div class="form-inline">
                <input type="text" class="form-control licencia-md" value="<?= $licencia->getPrecio_extranjero(); ?>" name="precio_extranjero" placeholder="Ingresar precio" required=""> USD
            </div>
        </div>
    </div>
    <div class="row form-row">
        <div class="form-group col-md-2">
            <label>IVA</label>
            <div class="form-inline">
                <input type="text" class="form-control licencia-sm" value="<?= $licencia->getIva(); ?>" name="iva" placeholder="IVA" required=""> %
            </div>
        </div>
    </div>
    <div class="row form-row">
        <div class="form-group col-md-2">
            <label>Dto.</label>
            <div class="form-inline">
                <input type="text" class="form-control licencia-sm" value="<?= $licencia->getDescuento(); ?>" name="descuento" placeholder="Dto." required=""> %
            </div>
        </div>
    </div>
                     
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Editar datos de Licencia</h4>
                </div>
                <div class="modal-body">
                    <p>
                        ¿Está seguro que desea modificar esta licencia?
                    </p>
                </div>
                <div class="modal-footer">
                    
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>                  
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                     class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionEmpresa/gestionLicencias') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->


