<script src="js/functions.js"></script>
<!-- Inicio: Tabla Licencias -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">Listado Licencias</div>
        </div>
        <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
            <thead>
                <tr>
                    <th class="th-sm"> Licencia</th>
                    <th class="">Precio Local</th>
                    <th class="">Precio Extranjero</th>
                    <th class="">IVA</th>
                    <th class="">Desc</th>
                    <th class="">Total Local</th>
                    <th class="">Total Extranjero</th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($licencias as $licencia) : ?>
                <tr>
                        <td><?php echo ($licencia->getNombre()); ?></td>
                        <td><?php echo($licencia->getPrecio_local()); ?></td>
                        <td><?php echo($licencia->getPrecio_extranjero()); ?></td>
                        <td><?php echo($licencia->getIva()); ?></td>
                        <td><?php echo($licencia->getDescuento()); ?></td>
                        <td><?php echo($licencia->getTotal_local()); ?></td>
                        <td><?php echo($licencia->getTotal_extranjero()); ?></td>


                        <td> <a class="btn btn-default" href="<?= $this->url('licencia', ['action' => 'edit', 'id' => $licencia->getId()]); ?>">
                                <span class="glyphicon glyphicon-pencil" ></span> 
                            </a>
                            <button name="<?= $licencia->getId() ?>" id="<?= $licencia->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $licencia->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                        <!-- Modal -->
                <div id="myModal<?= $licencia->getId() ?>" class="modal fade" role="dialog">
                    <div class="modal-dialog">

                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Eliminar licencia</h4>
                            </div>
                            <div class="modal-body">
                                <p>
                                    Está seguro que desea eliminar la licencia: 
                                    "<?= $this->escapeHtml($licencia->getNombre()) ?>"
                                    de forma permanente?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <a href="<?= $this->url('licencia', ['action' => 'remove', 'id' => $licencia->getId()]); ?>" class="btn btn-default">Aceptar</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!-- Fin: Tabla Licencias -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('licencia', ['action' => 'add']); ?>">
                                <img src="<?= $this->basePath('img/crm/ProductoAgregar.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Agregar</label><br>
                            <label>Producto</label>
                        </div>
                    </div>
                    
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->