<?php
if (isset($_SESSION['MENSAJES']['licencia'])) {
    if ($_SESSION['MENSAJES']['licencia']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['licencia_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['licencia_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['licencia'] = null;
    $_SESSION['MENSAJES']['licencia_msj'] = null;
}
?>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Licencias -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO LICENCIAS
            </div>
            
            <div class="container margen">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
                            <thead>
                                <tr>
                                    <th class="th-sm"> Licencia</th>
                                    <th class="">Descripcion</th>
                                    <th class="">Categoria</th>
                                    <th class="">Precio</th>
                                    <th class="">Precio +IVA</th>
                                    <th class="">Precio +IVA con Dto</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($licencias)) {
                                    foreach ($licencias as $licencia) : ?>
                                    <tr>
                                        <td><?php echo ($licencia->getNombre()); ?></td>
                                        <td><?php echo ($licencia->getDescripcion()); ?></td>
                                        <td><?php echo ($licencia->getNombreCategoria()); ?></td>
                                        <td><?php echo money_format("$ %n", $licencia->getPrecio()); ?></td>
                                        <td><?php echo money_format("$ %n", $licencia->getPrecio_final_iva()); ?></td>
                                        <td><?php echo money_format("$ %n", $licencia->getPrecio_final_iva_dto()); ?></td>
                                        <td class="table-items-right"> 
                                            <a class="btn btn-default" href="<?= $this->url('licencia/editar', ['tipo' => 'licencia', 'id' => $licencia->getId()]); ?>">
                                                <span class="glyphicon glyphicon-pencil" ></span> 
                                            </a>
                                            <button name="<?= $licencia->getId() ?>" id="<?= $licencia->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $licencia->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                                        </td>
                                    <!-- Modal -->
                                    <div id="myModal<?= $licencia->getId() ?>" class="modal fade" role="dialog">
                                        <div class="modal-dialog">

                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Eliminar licencia</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        Está seguro que desea eliminar la licencia: 
                                                        "<?= $this->escapeHtml($licencia->getNombre()) ?>"
                                                        de forma permanente?
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="<?= $this->url('licencia/borrar', ['action' => 'remove', 'id' => $licencia->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                                                        <span class="btn btn-default">Aceptar</span>
                                                    </a>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    echo $this->paginationControl(
        $licencias,
        'Sliding', // All, Elastic, Jumping, Sliding
        'search_pagination5.phtml',
        $this->url('licencia/page', ['action' => 'index', 'id' => 1])
    );
}
?>
</div>
<!-- Fin: Tabla Licencias -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionEmpresa/gestionLicencias/agregar') ?>">
                    <img src="<?= $this->basePath('img/crm/billete_add_n.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu">
                    </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Agregar</label><br>
                <label>Licencia</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionEmpresa/gestionLicencias') ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha">
                    </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->