<?php
if (isset($_SESSION['MENSAJES']['licencia'])) {
    if ($_SESSION['MENSAJES']['licencia']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['licencia_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['licencia_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['licencia'] = null;
    $_SESSION['MENSAJES']['licencia_msj'] = null;
}
?>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Licencias -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
                LISTADO LICENCIAS
                <a data-toggle="collapse" data-parent="#accordion" href="#add_licencia" 
                    aria-expanded="true" aria-controls="add_licencia">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
        </div>

        <!-- Inicio: Agregar Licencia -->
        <div class="container collapse" id="add_licencia">
            <form method="post">
                <div class="row form-row">
                    <div class="form-group form-inline">
                        <input type="text" class="form-control licencia-lg form-margen" name="nombre_licencia" placeholder="Nombre de Licencia" required="">
                        <input type="text" class="form-control licencia-md form-margen" name="precio_local" placeholder="Precio ARG" required="">
                        <input type="text" class="form-control licencia-md form-margen" name="precio_extranjero" placeholder="Precio USD" required="">
                        <input type="text" class="form-control licencia-sm form-margen" name="iva" placeholder="% IVA" required="">
                        <input type="text" class="form-control licencia-sm form-margen" name="descuento" placeholder="% Dto." required="">
                        <button type="button" class="btn btn-default form-margen" data-toggle="modal" data-target="#myModal">
                            <span class="glyphicon glyphicon-plus" ></span> Agregar Licencia
                        </button>
                    </div>
                </div>

                <!-- Modal -->
                <div id="myModal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Agregar licencia</h4>
                            </div>
                            <div class="modal-body">
                                <p>
                                    ¿Está seguro que desea agregar esta licencia?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-default">Aceptar</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>   
            </form>
        </div>

        <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
            <thead>
                <tr>
                    <th class="th-sm"> Licencia</th>
                    <th class="">Precio Local</th>
                    <th class="">Precio Extranjero</th>
                    <th class="">% IVA</th>
                    <th class="">% Dto</th>
                    <th class="">Total Local</th>
                    <th class="">Total Extranjero</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    if (isset($licencias)) {
                    foreach ($licencias as $licencia) : ?>
                    <tr>
                        <td><?php echo ($licencia->getNombre()); ?></td>
                        <td><?php echo money_format("$ %n", $licencia->getPrecio_local()); ?></td>
                        <td><?php echo money_format("USD %i", $licencia->getPrecio_extranjero()); ?></td>
                        <td><?php echo ($licencia->getIva()); ?> %</td>
                        <td><?php echo ($licencia->getDescuento()); ?> %</td>
                        <td><?php echo money_format("$ %n", $licencia->getTotal_local()); ?></td>
                        <td><?php echo money_format("USD %i", $licencia->getTotal_extranjero()); ?></td>
                        <td class="table-items-right"> 
                            <a class="btn btn-default" href="<?= $this->url('licencia/editar', ['action' => 'edit', 'id' => $licencia->getId()]); ?>">
                                <span class="glyphicon glyphicon-pencil" ></span> 
                            </a>
                            <button name="<?= $licencia->getId() ?>" id="<?= $licencia->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $licencia->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                        </td>
                    <!-- Modal -->
                    <div id="myModal<?= $licencia->getId() ?>" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Eliminar licencia</h4>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        Está seguro que desea eliminar la licencia: 
                                        "<?= $this->escapeHtml($licencia->getNombre()) ?>"
                                        de forma permanente?
                                    </p>
                                </div>
                                <div class="modal-footer">
                                    <a href="<?= $this->url('licencia/borrar', ['action' => 'remove', 'id' => $licencia->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                <span class="btn btn-default">Aceptar</span></a>
                                    
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
            <?php
                echo $this->paginationControl($licencias, 'Sliding', // All, Elastic, Jumping, Sliding
                            'search_pagination5.phtml', $this->url('licencia/page', ['action' => 'index', 'id' => 1]));
                }
                ?>
    </div>
</div>
<!-- Fin: Tabla Licencias -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->