<!-- scripts -->
<script src="/js/iva.js"></script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('herramientas'); ?>">Herramientas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Tipos de IVA</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('herramientas'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Licencias -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO DE TIPOS DE IVA
                <a data-toggle="collapse" data-parent="#accordion" href="#add_tipo_evento" 
                    aria-expanded="true" aria-controls="add_tipo_evento">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
            <div class="panel panel-body">
                <div class="collapse" id="add_tipo_evento">
                    <form method="post">
                        <div class="row form-row">
                            <div class="form-group col-md-4">
                                <label>Tipo de IVA</label>
                                <input type="text" class="form-control" name="nombre" placeholder="Tipo de IVA">
                            </div>
                            <div class="form-group col-md-4">
                                <label>Descripción</label>
                                <input type="text" class="form-control" name="descripcion" placeholder="Descripción">
                            </div>
                            <div class="form-group col-md-2">
                                <label>Valor</label>
                                <input type="text" class="form-control" name="valor"
                                    onkeypress="return justNumbers(event);" placeholder="Valor" required="True">
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="form-group col-md-3">
                                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                                    <span class="glyphicon glyphicon-plus" ></span> Agregar Tipo de IVA
                                </button>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Agregar Tipo IVA</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>¿Está seguro que desea agregar el tipo de IVA?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-default">Aceptar</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="container margen">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
                            <thead>
                                <tr>
                                    <th class="th-sm"> Tipo de IVA</th>
                                    <th class="">Descripción</th>
                                    <th class="">Valor</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($ivas)) {
                                    foreach ($ivas as $iva) : ?>
                                    <tr>
                                        <td><?php echo ($iva->getNombre()); ?></td>
                                        <td><?php echo ($iva->getDescripcion()); ?></td>
                                        <td><?php echo ($iva->getValor()); ?> %</td>
                                        <td>
                                            <div class="pull-right"> 
                                                <a class="btn btn-default btn-sm" href="<?= $this->url('tipoIva/editar', ['id' => $iva->getId()]); ?>">
                                                    <span class="glyphicon glyphicon-pencil" ></span> 
                                                </a>
                                                <button name="<?= $iva->getId() ?>" id="<?= $iva->getId() ?>" type="button" 
                                                    class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal<?= $iva->getId() ?>">
                                                    <span class="glyphicon glyphicon-trash" ></span>
                                                </button>
                                            </div>
                                        </td>
                                    <!-- Modal -->
                                    <div id="myModal<?= $iva->getId() ?>" class="modal fade" role="dialog">
                                        <div class="modal-dialog">

                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Eliminar tipo de IVA</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        Está seguro que desea eliminar el tipo de IVA: 
                                                        "<?= $this->escapeHtml($iva->getNombre()) ?>"
                                                        de forma permanente?
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="<?= $this->url('tipoIva/borrar', ['action' => 'remove', 'id' => $iva->getId()]); ?>" 
                                                        onclick="bloqueaPantalla()" type="button">
                                                        <span class="btn btn-default">Aceptar</span>
                                                    </a>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    echo $this->paginationControl(
        $ivas,
        'Sliding', // All, Elastic, Jumping, Sliding
        'search_pagination_iva.phtml',
        $this->url('tipoIva/page', ['action' => 'index', 'id' => 1])
    );
}
?>
</div>
<!-- Fin: Tabla Licencias -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('herramientas') ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom">
                    </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->