<?php
if (!is_null($empresa->getParametro_elementos_pagina())){  $elemsPag= $empresa->getParametro_elementos_pagina();}
else {$elemsPag= 5;}
$this->headTitle('Editar datos de la empresa');
$form->get('nombre')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getNombre()
]);
$form->get('direccion')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getDireccion()
]);
$form->get('telefono')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getTelefono()
]);
$form->get('mail')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getMail()
]);
$form->get('movil')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getMovil()
]);
$form->get('fax')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getFax()
]);
$form->get('web')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getWeb()
]);
$form->get('cuit_cuil')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getCuit_cuil()
]);
$form->get('vencimiento_cai')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getVencimiento_cai()
]);
$form->get('razon_social')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getRazon_social()
]);
$form->get('tipo_iva')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getTipo_iva()
]);
$form->get('localidad')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getLocalidad()
]);
$form->get('provincia')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getProvincia()
]);
$form->get('pais')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getPais()
]);
$form->get('CP')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getCP()
]);
$form->get('parametro_vencimiento')->setAttributes([
    'class' => 'form-control',
    'value' => $empresa->getParametro_vencimiento(),
    'style' => 'width: 50px;'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

?>
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb secondary-color navbar-menu-font">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionEmpresa'); ?>">Empresa</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionEmpresa/configuracion'); ?>">Configuración</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Empresa</li>
        </ol>
    </nav>
</div>

<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading titulo-espaciado">
            EDITAR DATOS DE EMPRESA
        </div>

        <div class="panel-body">  
            <div class="row form-row">
                <?= $this->form()->openTag($form); ?>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('nombre')); ?>
                    <?= $this->formElement($form->get('nombre')); ?>
                    <?= $this->formElementErrors($form->get('nombre')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('direccion')); ?>
                    <?= $this->formElement($form->get('direccion')); ?>
                    <?= $this->formElementErrors($form->get('direccion')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('telefono')); ?>
                    <?= $this->formElement($form->get('telefono')); ?>
                    <?= $this->formElementErrors($form->get('telefono')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('mail')); ?>
                    <?= $this->formElement($form->get('mail')); ?>
                    <?= $this->formElementErrors($form->get('mail')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('movil')); ?>
                    <?= $this->formElement($form->get('movil')); ?>
                    <?= $this->formElementErrors($form->get('movil')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('fax')); ?>
                    <?= $this->formElement($form->get('fax')); ?>
                    <?= $this->formElementErrors($form->get('fax')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('web')); ?>
                    <?= $this->formElement($form->get('web')); ?>
                    <?= $this->formElementErrors($form->get('web')); ?> 
                </div>
                
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('cuit_cuil')); ?>
                    <?= $this->formElement($form->get('cuit_cuil')); ?>
                    <?= $this->formElementErrors($form->get('cuit_cuil')); ?> 
                </div>
                
                <div class="form-group col-md-4">
                    <label>Vencimiento CAI</label>
                    <div class='input-group date' id='datetimepicker3'>
                        <input type='text' class="form-control" name="vencimiento_cai" value="<?php if(!is_null($empresa->getVencimiento_cai())) {echo ($empresa->getVencimiento_cai()->format('d/m/Y'));}?>"/>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
                
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('razon_social')); ?>
                    <?= $this->formElement($form->get('razon_social')); ?>
                    <?= $this->formElementErrors($form->get('razon_social')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('tipo_iva')); ?>
                    <?= $this->formElement($form->get('tipo_iva')); ?>
                    <?= $this->formElementErrors($form->get('tipo_iva')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('localidad')); ?>
                    <?= $this->formElement($form->get('localidad')); ?>
                    <?= $this->formElementErrors($form->get('localidad')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('provincia')); ?>
                    <?= $this->formElement($form->get('provincia')); ?>
                    <?= $this->formElementErrors($form->get('provincia')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('pais')); ?>
                    <?= $this->formElement($form->get('pais')); ?>
                    <?= $this->formElementErrors($form->get('pais')); ?> 
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($form->get('CP')); ?>
                    <?= $this->formElement($form->get('CP')); ?>
                    <?= $this->formElementErrors($form->get('CP')); ?> 
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Parametros Empresa -->
<div class="container margen">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">EDITAR PARÁMETROS DE EMPRESA</div>
            <div class="panel-body">
                <div class="row form-row">
                    <div class="col-md-4">
                        <label>Vigencia del soporte</label>
                    </div>
                    <div class="col-md-4"> 
                        <label>Elementos por página</label>
                    </div>
                    <div class="col-md-4"> 
                        <label>Moneda</label>
                    </div>
                </div>

                <div class="row form-inline">
                    <div class="form-group col-sm-4">
                        <input type="number" class="form-control" style="width:60px;" name="parametro_vencimiento" min="1" max="12" placeholder="Mes" value="<?php echo($empresa->getParametro_vencimiento()); ?>"> meses                       
                    </div>
                    <div class="form-group col-sm-4">
                        <select class="form-control" name="elems_pagina" id="elems_pagina">  
                            <option value="<?= $elemsPag ?>" hidden="" > <?= $elemsPag ?> </option>
                            <option value="5" >5</option>
                            <option value="10" >10</option>
                            <option value="20" >20</option>
                            <option value="50" >50</option>
                            <option value="100" >100</option>
                        </select>  
                    </div>
                    <div class="form-group col-sm-2">
                        <select class="form-control" name="moneda" id="moneda">
                            <option value="0" hidden="">Seleccionar Moneda</option>
                            <?php foreach ($monedas as $moneda) : ?>
                                <option value="<?php echo ($moneda->getId());?>"> <?php echo ($moneda->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>          
</div>
<!-- Fin: Parametros Empresa -->

<div class="container">   
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            Modal content
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Editar datos de la empresa</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea guardar los cambios?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->
<?= $this->form()->closeTag(); ?>

