<?php
$this->headTitle('Detalles de la empresa');
if (isset($_SESSION['MENSAJES']['empresa'])) {
    if ($_SESSION['MENSAJES']['empresa']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['empresa_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['empresa_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['empresa'] = null;
    $_SESSION['MENSAJES']['empresa_msj'] = null;
}
?>

<!-- Inicio: Datos de Empresa -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">DATOS DE EMPRESA</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6 ficha-empresa-p">
                        <p><label>Nombre:</label> <?php echo ($empresa->getNombre()); ?></p>
                        <p><label>Dirección:</label> <?php echo ($empresa->getDireccion()); ?></p>
                        <p><label>Teléfono:</label> <?php echo ($empresa->getTelefono()); ?></p>
                        <p><label>Email:</label> <?php echo ($empresa->getMail()); ?></p>
                        <p><label>Movil:</label> <?php echo ($empresa->getMovil()); ?></p> 
                        <p><label>Fax:</label> <?php echo ($empresa->getFax()); ?></p>
                        <p><label>Página web:</label> <?php echo ($empresa->getWeb()); ?></p>
                        <p><label>CUIT/CUIL:</label> <?php echo ($empresa->getCuit_cuil()); ?></p>
                    </div>
                    <div class="col-md-6 ficha-empresa-p">
                        <p><label>Vencimiento CAI:</label> <?php echo ($empresa->getVencimiento_cai()->format('d/m/Y')); ?></p>
                        <p><label>Razón social</label> <?php echo ($empresa->getRazon_social()); ?></p>
                        <p><label>Tipo IVA:</label> <?php echo ($empresa->getTipo_iva()); ?></p>
                        <p><label>Localidad:</label> <?php echo ($empresa->getLocalidad()); ?></p>
                        <p><label>Provincia:</label> <?php echo ($empresa->getProvincia()); ?></p>
                        <p><label>Pais:</label> <?php echo ($empresa->getPais()); ?></p>
                        <p><label>Código postal:</label> <?php echo ($empresa->getCP()); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos de Empresa -->
<!-- Parametros de Empresa-->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">PARÁMETROS DE EMPRESA</div>
            <div class="panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <p><label>Vigencia del Soporte:</label> <?php echo ($empresa->getParametro_vencimiento()); ?> meses</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Parametros de Empresa -->
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('editarempresa', ['action' => 'edit', 'id' => $empresa->getId()]) ?>">
                    <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Editar</label>
            </div>
        </div>
            <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->
