<!-- scripts -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script>
$(document).ready(function() {
    $('#tabla_formaspago').DataTable({
        "order": [0, 'desc'],
        "language": {
            "url": "/json/spanish.json"
        },
    });
  
});
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('herramientas'); ?>">Herramientas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Tipos de Facturas</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('herramientas'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>


<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Facturas -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                TIPOS DE FACTURA
                <a data-toggle="collapse" data-parent="#accordion" href="#add_tipo_evento" aria-expanded="true"
                    aria-controls="add_tipo_evento">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
            <div class="panel panel-body">
                <div class="collapse" id="add_tipo_evento">
                    <form method="post">
                        <div class="row form-row">
                            <div class="form-group col-md-3">
                                <label>Tipo de Factura</label>
                                <input type="text" class="form-control" id="nombre" name="nombre"
                                    placeholder="Forma de Pago" required>
                            </div>
                            <div class="form-group col-md-3">
                                <label>Descripción</label>
                                <input type="text" class="form-control" name="descripcion"
                                    placeholder="Descripcion" >
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="form-group col-md-3">
                                <button type="button" class="btn btn-default" data-toggle="modal"
                                    data-target="#myModal">
                                    <span class="glyphicon glyphicon-plus"></span>
                                    Tipo de Factura
                                </button>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Agregar Tipo de Factura </h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>¿Está seguro que desea agregar este tipo de factura?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-default">Aceptar</button>
                                        <button type="button" class="btn btn-default"
                                            data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="container margen">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tabla_evento" class="table table-bordred table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th class="th-sm"> Tipo de Factura</th>
                                    <th class="">Descripción</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    foreach ($tipoFacturas as $tipoFactura) : ?>
                                    <tr>
                                        <td><?php echo ($tipoFactura->getNombre()); ?></td>
                                        <td><?php echo ($tipoFactura->getDescripcion()); ?></td>                  
                                        <td id="<?= $tipoFactura->getId() ?>" class="">
                                            <div class="pull-right">
                                                <a href="<?= $this->url('tipofactura/editar', ['id' =>$tipoFactura->getId()]) ?>"
                                                    type="button" class="btn btn-default btn-sm">
                                                    <span class="glyphicon glyphicon-pencil"></span>
                                                </a>
                                                <button name="<?= $tipoFactura->getId() ?>" id="<?= $tipoFactura->getId() ?>" type="button" 
                                                    class="btn btn-default btn-sm" data-toggle="modal" 
                                                    data-target="#myModal<?= $tipoFactura->getId() ?>">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </div>
                                        </td>   
                                        <!-- Modal -->
                                        <div id="myModal<?= $tipoFactura->getId() ?>" class="modal fade" role="dialog">
                                            <div class="modal-dialog">
                                                <!-- Modal content-->
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close"
                                                            data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title">Eliminar Forma de Pago</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>
                                                            ¿Está seguro que desea eliminar el tipo de factura: 
                                                            "<?= $this->escapeHtml($tipoFactura->getNombre()) ?>"?
                                                        </p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <a href="<?= $this->url('tipofactura/borrar', ['action' => 'remove', 'id' => $tipoFactura->getId()]); ?>"
                                                            onclick="bloqueaPantalla()" type="button">
                                                            <span class="btn btn-default">Aceptar</span></a>
                                                        <button type="button" class="btn btn-default"
                                                            data-dismiss="modal">Cancelar</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>            
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Tabla -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('herramientas') ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom">
                    </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->