<!-- MODULE CLIENTES -->
<script src="js/functions.js"></script>
<!-- Inicio: Tabla Clientes -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">Listado Clientes</div>
            <div class="panel-body">
                <form method="post">
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="apellido" placeholder="Apellido">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="nombre" placeholder="Nombre">
                        </div>
                        <div class="form-group col-md-2">
                            <button type="submit" class="btn btn-default"> 
                                <i class="glyphicon glyphicon-search"></i> Buscar
                            </button>                      
                        </div>

                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="pais" placeholder="País">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="provincia" placeholder="Provincia">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="email" placeholder="Email">
                        </div>
                    </div>   

            </div>
            </form>
        </div>
    </div>
    <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
        <thead>
            <tr> 
                <th class="th-sm" onclick="sortTableString(1, 'tabla_evento')">
                    <i class="fa fa-sort float-right" aria-hidden="true"></i> Apellido
                </th>
                <th class="th-sm">Nombre</th>
                <th class="th-sm">Categoria</th>
                <th class="th-sm">Licencia</th>
                <th class="th-sm">Cantidad de clientes <?php echo(count($clientes)); ?></th>   
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (isset($clientes)) {
                foreach ($clientes as $cliente) {

                    echo('<tr>');
                    echo ('<td>');
                    echo ($cliente->getApellido());
                    echo ('</td>');
                    echo ('<td>');
                    echo ($cliente->getNombre());
                    echo ('</td>');
                    echo ('<td>');
                    echo ($cliente->getNombreCategoriaCliente());
                    echo ('</td>');
                    echo ('<td>');
                    echo ($cliente->getLicencia());
                    echo ('</td>');
                    ?>
                <td></td>
                <td>
                    <a class="btn btn-default" href="<?= $this->url('clientes/ficha', ['action' => 'ficha', 'id' => $cliente->getId()]); ?>">
                        <span class="glyphicon glyphicon-share-alt" ></span>
                    </a>
                </td>
                <?php }
            ?>
            </tr>
            </tbody>
        </table>
    <?php
    echo $this->paginationControl($clientes, 'Sliding', // All, Elastic, Jumping, Sliding
            'search_pagination_2.phtml', $this->url('clientes/pageinactivos', ['action' => 'index', 'id' => 1]));
}
?>
</div>
</div>
<!-- Fin: Tabla Clientes -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href='<?= $this->url("clientes") ?>'><img src="<?= $this->basePath('img/crm/ClienteAgregar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Clientes</label><br>
                            <label>Activos</label>
                        </div>
                    </div>

                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->