<!-- scripts -->
<script src="/js/clientes.js"></script>

<?php
$title = 'Agregar Cliente';
$this->headTitle($title);
?>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionClientes'); ?>">Clientes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar Cliente</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('gestionClientes'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<form method="post">
<!-- Inicio: Datos Generales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS GENERALES
            </div>
            <div class="panel-body">
                <!-- Fila 1 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Nombre y Apellido *</label>
                        <input type="text" class="form-control requerido" name="nombre" placeholder="Ingresar Nombre y Apellido" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Teléfono</label>
                        <input type="text" class="form-control" name="telefono" placeholder="Ingresar Teléfono">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Email</label>
                        <input type="text" class="form-control" name="email" placeholder="Ingresar Email">
                    </div>
                </div>
                <!-- Fila 2 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>País</label>
                        <select class="form-control place_holder dropdown" id="pais" name="pais" onchange="actualizarDatosProvincias(this.value)">
                            <option value="-1" hidden="" selected>Seleccionar País</option>
                            <?php foreach ($paises as $pais) : ?>
                                <option value="<?php echo ($pais->getId()); ?>"><?php echo ($pais->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Provincia</label>
                        <div id="div_provincias">
                            <select class="form-control place_holder dropdown" id="ops_provincias" name="provincia">
                                <option value="-1" hidden="" selected></option>
                            </select>
                        </div>
                    </div> 
                    <div class="form-group col-md-4">
                        <label>Ciudad</label>
                        <input type="text" class="form-control" name="ciudad" placeholder="Ingresar Ciudad">
                    </div>

                    
                </div>
                <!-- Fila 3 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Categoria de Servicio</label>
                        <select class="form-control place_holder dropdown" id="categoria_servicio" name="categoria_servicio" onchange="actualizarServicios(this.value)">
                            <option value="-1" hidden="" selected>Seleccionar Categoría</option>
                            <option value="-1">No definido</option>
                            <?php foreach ($categoriasServicio as $c) : ?>
                                <option value="<?php echo ($c->getId()); ?>"><?php echo ($c->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Servicio</label>
                        <div id="div_servicios">
                            <select class="form-control place_holder dropdown" id="servicio" name="servicio">
                                <option value="-1" hidden="" selected></option>
                            </select>
                        </div>
                    </div> 
                    
                    <div class="form-group col-md-4">
                        <label>Versión</label>
                        <select class="form-control place_holder dropdown" id="version" name="version">
                            <option value="-1" hidden="">Seleccionar Versión</option>
                            <option value="Productores">Productores</option>
                            <option value="Veterinarios">Veterinarios</option>
                            <option value="-1">No definido</option>
                        </select>
                    </div>
                </div>
                <!-- Fila 4 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Skype</label>
                        <input type="text" class="form-control" name="skype" placeholder="Ingresar Skype">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Categoría de Cliente *</label>
                        <select class="form-control requerido place_holder dropdown" id="categoria" name="categoria" required>
                            <option value="" hidden="">Seleccionar Categoría</option>
                            <?php foreach ($categorias as $categoria) : ?>
                            <option value="<?php echo ($categoria->getId()); ?>"><?php echo ($categoria->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>
<!-- Fin: Datos Generales -->

<!-- Inicio: Datos Laborales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS LABORALES
            </div>
            <div class="panel panel-body">
                <!-- Fila 1 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Empresa</label>
                        <input type="text" class="form-control" name="empresa" placeholder="Ingresar Empresa">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Profesión</label>
                        <select class="form-control place_holder dropdown" id="profesion" name="profesion">
                            <option value="" hidden="">Seleccionar Profesión</option>
                            <option value="-1">No definido</option>
                            <?php foreach ($profesiones as $profesion) : ?>
                                <option value="<?php echo ($profesion->getId()); ?>"><?php echo ($profesion->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <!-- Fila 2 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Cargo</label>
                        <input type="text" class="form-control" name="cargo" placeholder="Ingresar Cargo">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Tipo de Nogocio</label>
                        <input type="text" class="form-control" name="actividad" placeholder="Ingresar Actividad">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos Laborales -->

<!-- Inicio: Datos de Facturacion -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS DE FACTURACIÓN
            </div>
            <div class="panel panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Razón Social</label>
                        <input type="text" class="form-control" name="razon_social" placeholder="Ingresar Razón Social">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Condición de IVA</label>
                        <select class="form-control place_holder dropdown" id="condicion_iva" name="condicion_iva">
                            <option value="-1" hidden="">Seleccionar</option>
                            <option value="-1">No definido</option>
                            <?php foreach ($condiciones_iva as $condicion_iva) : ?>
                                <option value="<?php echo ($condicion_iva->getId()); ?>"><?php echo ($condicion_iva->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Tipo de Factura</label>
                        <select class="form-control place_holder dropdown" id="tipo_factura" name="tipo_factura">
                            <option value="" hidden="">Seleccionar</option>
                            <option value="-1">No definido</option>
                            <?php foreach ($tiposFactura as $tipo_factura) : ?>
                                <option value="<?php echo ($tipo_factura->getId()); ?>"><?php echo ($tipo_factura->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>                   
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>Banco</label>
                        <input type="text" class="form-control" name="banco" placeholder="Ingresar Banco">
                    </div>
                    <div class="form-group col-md-2">
                        <label>CUIT/CUIL</label>
                        <input type="text" class="form-control" name="cuit_cuil" placeholder="Ingresar CUIT/CUIL">
                    </div>
                    <div class="form-group col-md-4">
                        <label>CBU</label>
                        <input type="text" class="form-control" name="cbu" placeholder="Ingresar CBU">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Dirección de Facturación</label>
                        <input type="text" class="form-control" name="direccion_facturacion" placeholder="Ingresar Dirección de Facturación">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos de Facturacion -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Agregar cliente</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea agregar este cliente?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default">Aceptar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Fin: Cliente Nuevo -->
</form>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar"> 
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>                   
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>       
</div>
<!-- Fin: Panel Botones -->


