<!-- scripts -->
<script src="/js/clientes.js"></script>

<?php
$title = 'Editar Cliente';
$this->headTitle($title);
$id = $cliente->getPersona()->getId();
$nombre = $persona->getNombre();
$telefono = $persona->getTelefono();
$email = $persona->getEmail();
$skype = $cliente->getSkype();
$pais = $cliente->getPais();
$provincia = $cliente->getProvincia();
$ciudad = $cliente->getCiudad();
$empresa = $cliente->getEmpresa();
$cargo = $cliente->getCargo();
$categoria = $cliente->getCategoria();
$servicio = $cliente->getServicio();
$version = $cliente->getVersion();
$profesion = $cliente->getProfesion();
$condicion_iva = $persona->getCondicion_iva();
$actividad = $cliente->getActividad();
$animales = $cliente->getAnimales();
$establecimientos = $cliente->getEstablecimientos();
$raza_manejo = $cliente->getRazaManejo();
?>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionClientes'); ?>">Clientes</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionClientes/listado'); ?>">Listado</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('clientes/ficha', ['tipo' => 'cliente', 'id' => $id]) ?>">Ficha Cliente</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Cliente</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('clientes/ficha', ['tipo' => 'cliente', 'id' => $id]) ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<!-- Inicio: Datos Generales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS PARTICULARES
            </div>
            <div class="panel panel-body">
                <form method="post">
                <!-- Fila 1 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Nombre y Apellido *</label>
                        <input type="text" class="form-control requerido" name="nombre" value="<?= $nombre ?>" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Teléfono</label>
                        <input type="text" class="form-control" name="telefono"value="<?= $telefono ?>" >
                    </div>
                    <div class="form-group col-md-4">
                        <label>Email</label>
                        <input type="text" class="form-control" name="email" value="<?= $email ?>" >
                    </div>
                </div>
                <!-- Fila 2 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>País</label>
                        <select class="form-control place_holder dropdown" id="pais" name="pais" onchange="actualizarDatosProvincias(this.value)" >
                            <option value="<?php if(!is_null($pais)){echo $pais->getId();} else {echo (-1);} ?>" hidden=""> <?php if (isset($pais)){echo $pais->getNombre();} else{echo ("Seleccionar País");} ?></option>
                            <?php foreach ($paises as $pais) : ?>
                                <option value="<?php echo ($pais->getId()); ?>"><?php echo ($pais->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Provincia</label>
                        <div id="div_provincias">
                        <select class="form-control place_holder dropdown" id="ops_provincias" name="provincia">
                            <option value="<?php if(isset($provincia)){ echo ($provincia->getId()); } else {echo (-1);}?>" hidden=""> 
                                   <?php if(isset($provincia)){ echo($provincia->getNombre_provincia()); } else {echo ("Seleccionar Provincia");}?>
                            </option>
                        </select>
                        </div>
                    </div> 
                    <div class="form-group col-md-4">
                        <label>Ciudad</label>
                        <input type="text" class="form-control" name="ciudad" value="<?= $ciudad ?>">
                    </div>
                </div>
                    <!-- 3ra fila -->
                    <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Categoria de Servicio</label>
                        <select class="form-control place_holder dropdown" id="categoria_servicio" name="categoria_servicio" onchange="actualizarServicios(this.value)">
                            <option value="<?php if (isset($servicio)) 
                            {echo $servicio->getIdCategoria();} else{echo (-1);} ?> " hidden=""><?php if (isset($servicio))
                            {echo($servicio->getNombreCategoria());} else{echo ("Seleccionar Categoria");}?></option>
                            <?php foreach ($categoriasServicio as $c) : ?>
                                <option value="<?php echo ($c->getId()); ?>"><?php echo ($c->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Servicio</label>
                        <div id="div_servicios">
                        <select class="form-control place_holder dropdown" id="servicio" name="servicio">
                        <option value="<?php if(isset($servicio)){ echo ($servicio->getId()); }else{echo (-1);}?>" hidden=""> 
                                   <?php if(isset($servicio)){ echo($servicio->getNombre()); } else {echo ("Seleccionar Servicio");}?>
                            </option>
                        </select>
                        </div>
                    </div> 
                    <div class="form-group col-md-4">
                        <label>Versión</label>
                        <select class="form-control place_holder dropdown" id="version" name="version">
                            <option value="<?php if (isset($version)) {echo $version;} else{echo (-1);} ?>" hidden=""><?php if (isset($version)) {echo ($version);} else{echo ("Seleccionar Versión");} ?></option>
                            <option value="Productores">Productores</option>
                            <option value="Veterinarios">Veterinarios</option>
                            <option value="-1">No definido</option>
                        </select>
                    </div>
                </div>
                <!-- Fila 4 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Skype</label>
                        <input type="text" class="form-control" name="skype" value="<?= $skype ?>" >
                    </div>
                    <div class="form-group col-md-4">
                        <label>Categoría de Cliente *</label>
                        <select class="form-control requerido place_holder dropdown" id="categoria" name="categoria" required>
                        <option value="<?php if (isset($categoria)) {echo $categoria->getId();} else{echo (-1);} ?>" hidden=""> <?php if (isset($categoria)){echo($categoria->getNombre());} else {echo ("Seleccionar Categoría");} ?> </option>
                            <?php foreach ($categorias as $categoria) : ?>
                            <option value="<?php echo ($categoria->getId()); ?>"><?php echo ($categoria->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>
<!-- Fin: Datos Generales -->

<!-- Inicio: Datos Laborales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS LABORALES
            </div>
            <div class="panel panel-body">
                <!-- Fila 1 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Empresa</label>
                        <input type="text" class="form-control" name="empresa"
                            value="<?php echo($empresa); ?>" placeholder="Ingresar Empresa">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Profesión</label>
                        <select class="form-control place_holder dropdown" id="profesion" name="profesion">
                            <option value="<?php if(isset($profesion)){ echo ($profesion->getId()); }else{echo (-1);}?>" hidden="">  
                                <?php if(isset($profesion)){ echo($profesion->getNombre()); } else {echo ("Seleccionar Profesión");}?>
                            </option>
                            <option value="-1">No definido</option>
                            <?php foreach ($profesiones as $profesion) : ?>
                                <option value="<?php echo ($profesion->getId()); ?>"><?php echo ($profesion->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <!-- Fila 2 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Cargo</label>
                        <input type="text" class="form-control" name="cargo"
                            value="<?php echo($cargo); ?>" placeholder="Ingresar Cargo">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Tipo de Negocio</label>
                        <input type="text" class="form-control" name="actividad" 
                            value="<?php echo($actividad); ?>" placeholder="Ingresar Actividad">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos Laborales -->

<!-- Inicio: Datos de Facturacion -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS DE FACTURACIÓN
            </div>
            <div class="panel panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Razón Social</label>
                        <input type="text" class="form-control" name="razon_social" 
                            value="<?= $persona->getRazon_social(); ?>" placeholder="Ingresar Razón Social">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Condición de IVA</label>
                        <select class="form-control place_holder dropdown" id="condicion_iva" name="condicion_iva">
                            <option value="<?php if(isset($condicion_iva)){ echo ($condicion_iva->getId()); }else{echo (-1);}?>" hidden="">  
                                <?php if(isset($condicion_iva)){ echo($condicion_iva->getNombre()); } else {echo ("Seleccionar");}?>
                            </option>
                            <option value="-1">No definido</option>
                            <?php foreach ($condiciones_iva as $condicion_iva) : ?>
                                <option value="<?php echo ($condicion_iva->getId()); ?>"><?php echo ($condicion_iva->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Banco</label>
                        <input type="text" class="form-control" name="banco" 
                            value="<?= $persona->getBanco(); ?>" placeholder="Ingresar Banco">
                    </div>
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Dirección de Facturación</label>
                        <input type="text" class="form-control" name="direccion_facturacion" 
                            value="<?= $persona->getDireccion_facturacion(); ?>" placeholder="Ingresar Dirección de Facturación">
                    </div>
                    <div class="form-group col-md-4">
                        <label>CUIT/CUIL</label>
                        <input type="text" class="form-control" name="cuit_cuil"
                        value="<?= $persona->getCuit_cuil(); ?>" placeholder="Ingresar CUIT/CUIL">
                    </div>
                    <div class="form-group col-md-4">
                        <label>CBU</label>
                        <input type="text" class="form-control" name="cbu"
                            value="<?= $persona->getCbu(); ?>" placeholder="Ingresar CBU">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos de Facturacion -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modificar cliente</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea modificar los datos este cliente?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default">Aceptar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>

    </div>
</div>

</form>

<!-- Fin: Cliente Nuevo -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal"><img src="<?= $this->basePath('img/crm/aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('clientes/ficha', ['action' => 'ficha', 'id' => $id]) ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->
