<?php
$this->headTitle('Detalles del Cliente');
$id_cliente = $this->cliente->getId();

if (isset($_SESSION['MENSAJES']['ficha_cliente'])) {
    if ($_SESSION['MENSAJES']['ficha_cliente']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['ficha_cliente_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['ficha_cliente_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['ficha_cliente'] = null;
    $_SESSION['MENSAJES']['ficha_cliente_msj'] = null;
}
?>

<!-- Inicio: Datos de Cliente -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">DATOS PARTICULARES</div>
            <div class="panel-body">
                <!-- Header -->
                <div class="row ficha-cliente-titulo">
                    <div class="form-group col-md-5">
                        <h3>
                            <?php echo($cliente->getApellido() . ", " . $cliente->getNombre()); ?>
                        </h3>
                    </div>
                    <div class="form-group col-md-3">
                        <h3>
                            <?php echo ($cliente->getNombreCategoriaCliente()); ?>
                        </h3>
                    </div>
                    <div class="form-group col-md-4">
                        <h3>
                            <?php
                            echo ($cliente->getNombreLicenciaCliente());
                            if (!is_null($cliente->getVersion())) {
                                echo (" - " . $cliente->getVersion());
                            }
                            ?>
                        </h3>
                    </div>
                </div>
                <!-- Datos de Cliente -->
                <div class="row">
                    <div class="col-md-5 ficha-cliente-p">
                        <p><label>País:</label> <?php echo ($cliente->getNombrePaisCliente()); ?></p>
                        <p><label>Provincia:</label> <?php echo ($cliente->getNombreProvinciaCliente()); ?></p>
                        <p><label>Ciudad:</label> <?php echo ($cliente->getCiudad()); ?></p>
                        <p><label>Teléfono:</label> <?php echo ($cliente->getTelefono()); ?></p>
                        <p><label>Email:</label> <?php echo ($cliente->getEmail()); ?></p>
                        <p><label>Skype:</label> <?php echo ($cliente->getSkype()); ?></p>
                    </div>
                    <div class="col-md-3 ficha-cliente-p">
                        <p><label>Profresíon:</label> <?php echo ($cliente->getNombreProfesionCliente()); ?></p>
                        <p><label>Actividad:</label> <?php echo ($cliente->getActividad()); ?></p>
                        <p><label>Empresa:</label> <?php echo ($cliente->getEmpresa()); ?></p>
                        <p><label>Nro. Animales:</label> <?php echo ($cliente->getAnimales()); ?></p>
                        <p><label>Nro. Establecimientos:</label> <?php echo ($cliente->getEstablecimientos()); ?></p>
                        <p><label>Raza de Manejo:</label> <?php echo ($cliente->getRazaManejo()); ?></p>
                    </div>
                    <div class="col-md-4 ficha-cliente-p">
                        <p><label>Fecha de Compra:</label> <?php
                            if (!is_null($cliente->getFechaCompra())) {
                                echo ($cliente->getFechaCompra()->format('d/m/Y'));
                            }
                            ?></p>
                        <p><label>Último Pago:</label> <?php
                            if (!is_null($cliente->getFechaUltimoPago())) {
                                echo ($cliente->getFechaUltimoPago()->format('d/m/Y'));
                            }
                            ?></p>
                        <p><label>Fecha Vencimiento:</label> <?php
                            if (!is_null($cliente->getVencimiento())) {
                                echo ($cliente->getVencimiento()->format('d/m/Y'));
                            }
                            ?></p>
                        <p><label>Último Contacto:</label> <?php
                            if (!is_null($cliente->getFechaUltimoContacto())) {
                                echo ($cliente->getFechaUltimoContacto()->format('d/m/Y'));
                            }
                            ?></p>
                        <p><label>Estado:</label> <?php echo ($cliente->getEstadoNombre()); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading text-center">USUARIOS Y DATOS ADICIONALES</div>
        </div>
        <!-- Datos de Usuarios Adicionales -->
        <table id="tabla_evento" class="table table-condensed">            
            <thead>
                <tr> 
                    <th class="th-sm">U/Dato Adicional</th>
                    <th class="th-sm">Teléfono</th>
                    <th class="th-sm">Email</th>
                    <th class="th-sm">Skype</th>
                    <th></th>      
                </tr>
            </thead>
            <tbody>
                <?php foreach ($usuarios as $usuario) : ?>
                    <tr>
                        <td><?php echo($usuario->getNombre()); ?></td>
                        <td><?php echo($usuario->getTelefono()); ?></td>
                        <td><?php echo($usuario->getMail()); ?></td>
                        <td><?php echo($usuario->getSkype()); ?></td>
                        <td> <a class="btn btn-default" href="<?= $this->url('usuarios', ['action' => 'edit', 'id' => $usuario->getId()]); ?>">
                                <span class="glyphicon glyphicon-pencil" ></span> 
                            </a>
                            <button name="<?= $usuario->getId() ?>" id="<?= $usuario->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#usuarioModal<?= $usuario->getId() ?>">
                                <span class="glyphicon glyphicon-remove" ></span
                            </button>
                        </td>
                        <!-- Modal Usuario Adicional -->
                <div id="usuarioModal<?= $usuario->getId() ?>" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Eliminar usuario</h4>
                            </div>
                            <div class="modal-body">
                                <p>
                                    ¿Está seguro que desea eliminar el usuario:
                                    "<?= $this->escapeHtml($usuario->getNombre()) ?>"
                                    de forma permanente?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <a href="<?= $this->url('usuarios', ['action' => 'delete', 'id' => $usuario->getId()]); ?>" type="button">
                                <span class="btn btn-default">Aceptar</span></a>
                               
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td>
                    <a href="<?= $this->url('usuarios', ['action' => 'add', 'id' => $cliente->getId()]); ?>" type="button">
                        <span class="btn btn-default">
                            <span class="glyphicon glyphicon-plus" ></span> Agregar
                        </span>
                    </a> 
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- Fin: Datos de Cliente -->

<!-- Inicio: Actividades -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">REGISTRO DE ACTIVIDADES</div>
        </div>
        <!-- Datos de Usuarios Adicionales -->
        <table id="tabla_evento" class="table table-bordered table-zebra table-bot">            
            <thead class="table-scroll-head">
                <tr> 
                    <th class="" id="fila">Fecha</th>
                    <th class="">Responsable</th>
                    <th class="">Tipo</th>
                    <th class="detalle-width">Detalle</th>     
                </tr>
            </thead>
        </table>
        <table id="tabla_evento" class="table table-bordered table-zebra table-scroll table-top">            
            <tbody role="button" class="">
                <?php foreach ($eventos as $evento): ?>
                <tr id="<?= $evento->getId() ?>" onclick="seleccionarFila(event)">
                        <td id="<?= $evento->getId() ?>" class=""><?php
                            if (!is_null($evento->getFecha())) {
                                echo($evento->getFecha()->format('d/m/Y'));
                            }
                            ?></td>
                        <td id="<?= $evento->getId() ?>" class=""><?php echo($evento->getUsuarioEjecutivo()); ?></td>
                        <td id="<?= $evento->getId() ?>" class=""><?php
                            if (!is_null($evento->getTipo())) {
                                echo($evento->getTipo());
                            } else {
                                echo('No definido');
                            }
                            ?></td>
                        <td id="<?= $evento->getId() ?>" class="table-scroll-description"><?php echo(nl2br($evento->getDescripcion())); ?></td>
                    </tr> 
                <?php endforeach; ?>    
            </tbody>
        </table>
    </div>
</div>
<!-- Fin: Actividades -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a role="button" href="<?= $this->url('evento', ['action' => 'add', 'id' => (int) $cliente->getId()]) ?>">
                                <img src="<?= $this->basePath('img/crm/ActividadAgregar.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Agregar</label><br>
                            <label>Actividad</label>
                        </div>
                    </div>
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a role="button" data-toggle="modal" data-target="#actividadModal">
                                <img src="<?= $this->basePath('img/crm/ActividadEliminar.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Eliminar</label><br>
                            <label>Actividad</label>
                        </div>
                    </div>
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('clientes/editar', ['action' => 'edit', 'id' => (int) $cliente->getId()]) ?>" role="button">
                                <img src="<?= $this->basePath('img/crm/ClienteModificar.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Modificar</label><br>
                            <label>Datos</label>
                        </div>
                    </div>
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a role="button" name="<?= $cliente->getId() ?>" id="<?= $cliente->getId() ?>" data-toggle="modal" data-target="#exampleModal<?= $cliente->getId() ?>">
                                <img src="<?php
                                if ($cliente->getEstado() == "S") {
                                    echo($this->basePath('img/crm/ClienteEliminar.png'));
                                } else {
                                    echo($this->basePath('img/crm/ClienteAgregar.png'));
                                }
                                ?>" class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <?php
                            if ($cliente->getEstado() == "S") {
                                echo('<label>Eliminar</label><br>'
                                . '<label>Cliente</label>');
                            } else {
                                echo('<label>Agregar</label><br>'
                                . '<label>Cliente</label>');
                            }
                            ?>
                        </div>
                    </div>
                    <div class="col ficha-cliente-p img-centrar">
                        <div>   
                            <?php
                            $ruta = "";
                            if ($cliente->getEstado() == "S") {
                                $ruta = 'clientes';
                            } else {
                                $ruta = 'clientes/inactivos';
                            }
                            ?>
                            <a href="<?= $this->url($ruta) ?>" role="button">
                                <img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->

<!-- Modal Ciente -->
<div class="modal fade" id="exampleModal<?= $cliente->getId() ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Eliminar cliente</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    ¿Está seguro que desea eliminar el cliente:
                    "<?= $this->escapeHtml($cliente->getNombre()) ?>
                    <?= $this->escapeHtml($cliente->getApellido()) ?>"
                    ?<br>
                    <?php
                    if ($cliente->getEstado() == "S") {
                        echo('Se establecerá como Inactivo.');
                    } else {
                        echo('Se establecerá como Activo.');
                    }
                    ?>
                </p>
            </div>
            <div class="modal-footer">
                <a href="<?= $this->url('clientes/modificarEstado', ['action' => 'modificarEstado', 'id' => (int) $cliente->getId()]) ?>" type="button">
                <span class="btn btn-default">Aceptar</span></a>
               
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Actividad -->
<div class="modal fade" id="actividadModal" tabindex="-1" role="dialog" aria-labelledby="actividadModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="actividadModalLabel">Eliminar actividad</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar las actividades seleccionadas?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" onclick="eliminaEventos()">Aceptar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
