<!-- scripts -->
<script src="/js/clientes.js"></script>

<select class="form-control place_holder dropdown" id="ops_provincias" name="provincia">
    <option value="<?php if(isset($provincia)){ echo ($provincia->getId()); } else {echo (-1);} ?>" hidden="">  
        <?php if(isset($provincia)){ echo($provincia->getNombre_provincia()); } else {echo ("Seleccionar Provincia");}?>
    </option> 
    <?php foreach ($provincias as $provincia ) : ?>
        <option value="<?php echo ($provincia->getId()); ?>"><?php echo ($provincia->getNombre_provincia()); ?></option>
    <?php endforeach; ?>
</select>

