<!-- MODULE CLIENTES -->
<script src="js/functions.js"></script>
<!-- Inicio: Tabla Clientes -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">Listado Clientes</div>
            <div class="panel-body">
                <form method="post">
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="apellido" placeholder="Apellido" value="<?php if (count($parametros)>0){echo($parametros['apellido']);} ?>">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="nombre" placeholder="Nombre" value="<?php if (count($parametros)>0){echo($parametros['nombre']);} ?>">
                        </div>
                        <div class="form-group col-md-2">
                            <button type="submit" class="btn btn-default"> 
                                <i class="glyphicon glyphicon-search"></i> Buscar
                            </button>                      
                        </div>

                        </div>
                   
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="pais" placeholder="País" value="<?php if (count($parametros)>0){echo($parametros['pais']);} ?>">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="provincia" placeholder="Provincia" value="<?php if (count($parametros)>0){echo($parametros['provincia']);} ?>">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="email" placeholder="Email" value="<?php if (count($parametros)>0){echo($parametros['email']);} ?>">
                        </div>
                      </div>   
                         
                    </div>
                </form>
            </div>
        </div>
        <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
            <thead>
                <tr> 
                    <th class="th-sm">Apellido</th>
                    <th class="th-sm">Nombre</th>
                    <th class="th-sm">Categoria</th>
                    <th class="th-sm">Licencia</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                <?php
                if (isset($clientes)) {
                    foreach ($clientes as $cliente) {
                        if ($cliente->getEstado()!='N'){
                        
                            echo('<tr>');
                            echo ('<td>');
                            echo ($cliente->getApellido());
                            echo ('</td>');
                            echo ('<td>');
                            echo ($cliente->getNombre());
                            echo ('</td>');
                            echo ('<td>');
                            echo ($cliente->getNombreCategoriaCliente());
                            echo ('</td>');
                            echo ('<td>');
                            echo ($cliente->getLicencia());
                            echo ('</td>');
                        
                        ?>
               <td></td>
                
                    <td>
                        <a class="btn btn-default" href="<?= $this->url('clientes/ficha', ['action' => 'ficha', 'id' => $cliente->getId()]); ?>">
                            <span class="glyphicon glyphicon-share-alt" ></span>
                        </a>
                    </td>
                <?php 
                        }   
                        
                } ?>
                    
                </tr>
                </tbody>
            </table>
            <?php
            echo $this->paginationControl($clientes, 'Sliding', // All, Elastic, Jumping, Sliding
                    'search_pagination_2.phtml', $this->url('clientes/page', ['action' => 'index', 'id' => 1]));
        }
        ?>
    </div>
</div>
<!-- Fin: Tabla Clientes -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href='<?= $this->url("clientes/agregar", ["action" => "add"]) ?>'><img src="<?= $this->basePath('img/crm/ClienteAgregar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Cliente</label><br>
                            <label>Nuevo</label>
                        </div>
                    </div>
                    
                     <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href='<?= $this->url("clientes/inactivos") ?>'><img src="<?= $this->basePath('img/crm/ClienteEliminar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Clientes</label><br>
                            <label>Inactivos</label>
                        </div>
                    </div>
                    
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->