<script>
$(document).ready(function() {
    $('#tabla_eventos').DataTable({
        "order": [0, 'desc'],

        "language": {
            "url": "/json/spanish.json"
        }
    });
});
</script>

<table id="tabla_eventos" class="display">
    <thead>
        <tr>
            <th class="" id="fila">Fecha</th>
            <th class="">Responsable</th>
            <th class="">Tipo</th>
            <th class="detalle-width">Detalle</th>
            <th class=""></th>
        </tr>
    </thead>
    <tbody id="cuerpo_eventos" role="button" class="">
        <?php foreach ($eventos as $evento) : ?>
        <tr id="<?= $evento->getId() ?>" onclick="seleccionarFila(event)" class="vpEvento">
            <td id="<?= $evento->getId() ?>" class=""><?php
                                                        if (!is_null($evento->getFecha())) {
                                                            echo ($evento->getFecha()->format('Y/m/d'));
                                                        }
                                                        ?></td>
            <td id="<?= $evento->getId() ?>" class="">
                <?php echo ($evento->getUsuarioEjecutivo()); ?></td>
            <td id="<?= $evento->getId() ?>" class=""><?php
                                                        if (!is_null($evento->getTipo())) {
                                                            echo ($evento->getTipo());
                                                        } else {
                                                            echo ('No definido');
                                                        }
                                                        ?></td>
            <td id="<?= $evento->getId() ?>" class="table-scroll-description">
                <?php echo (nl2br($evento->getDescripcion())); ?></td>
            <td id="<?= $evento->getId() ?>" class="">
                <button name="<?= $evento->getId() ?>" id="<?= $evento->getId() ?>" type="button"
                    class="btn btn-default btn-sm" data-toggle="modal"
                    data-target="#vpEventoModal<?= $evento->getId() ?>">
                    <span class="glyphicon glyphicon-eye-open"></span>
                </button>
            </td>

            <!-- Modal Vista Previa Evento -->
            <div id="vpEventoModal<?= $evento->getId() ?>" class="modal fade" role="dialog">
                <div class="modal-dialog modal-lg">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"> <?php 
                                                    if (!is_null($evento->getFecha())) {
                                                        echo ($evento->getFecha()->format('Y/m/d') . " - "
                                                            . $evento->getTipo());
                                                    } ?>
                            </h4>
                        </div>
                        <div class="modal-body">
                            <?php echo (nl2br($evento->getDescripcion())); ?>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>