
<script src="/js/cuenta-corriente.js"></script>
<!-- Datetime Picker -->
<!-- <script language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
<script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css"> -->

<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
    $('#datetimepicker2').datetimepicker({
        format: 'DD/MM/YYYY'
    });
</script>
<!-- Fin -> Datetime Picker -->

<script>
   $.fn.dataTable.ext.search.push(
    function( settings, data, dataIndex ) {
        var min = ( $('#min').val());
        var max = ( $('#max').val());

        var date = ( data[0] ); // use data for the date column
        console.log("min "+min);
        console.log("max "+max);
        console.log("date" +date);
        // if ( ( isNaN( min ) && isNaN( max ) ) ||
        //      ( isNaN( min ) && date <= max ) ||
        //      ( min <= date   && isNaN( max ) ) ||
        //      ( min <= date   && date <= max ) )
        // {
        //     return true;
        // }
        // return false;
        return true;
    }
);

$(document).ready(function() {
    var table1 = $('#tabla_ventas').DataTable({
        "order": [0, 'desc'],
        "language": {
            "url": "/json/spanish.json"
        }
    });
    // $('#min, #max').keyup( function() {
    //     alert("cambio");
    //     table1.draw();
    // } );
    $('#filtroFecha').click( function() {
        alert("cambio");
        table1.draw();
    } );

    var table2 = $('#tabla_cobros').DataTable({
        "order": [0, 'desc'],
        "language": {
            "url": "/json/spanish.json"
        }
    });
    // $('#min, #max').keyup( function() {
    //     table2.draw();
    // } );
});

var idPersona = <?= $id_persona ?>;
</script>

<div class="row">
    <!-- * * * * * * * * * * * * * * * DATATABLE VENTAS * * * * * * * * * * * * * * * -->
    <div class="col-lg-6">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                VENTAS
            </div>
            <div class="panel-body">
                <div class="row form-row">
                    <div class="form-inline col-sm-12">
                        <div class="form-group">
                            <label>Filtrar desde:&nbsp;</label>
                            <div class='input-group date width-fecha' id='datetimepicker1'>
                            <input type='text' class="form-control" name="min" id="min" value="" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        <!-- </div> -->
                        <!-- <div class="form-group"> -->
                            <label>&nbsp;hasta:&nbsp;</label>
                            <div class='input-group date width-fecha' id='datetimepicker2'>
                                <input type='text' class="form-control" name="max" id="max" value="" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        <!-- </div> -->
                        <!-- <div class="form-group"> -->
                            <button type="button" class="form-control btn btn-default" name="filtroFecha" id="filtroFecha" value="">
                                    <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <br>
                <table id="tabla_ventas" class="display">
                    <thead>
                        <tr>
                            <th class="">Fecha</th>
                            <th class="">Tipo</th>
                            <th class="">Nro</th> 
                            <th class="">Importe</th>
                        </tr>
                    </thead>
                    <tbody id="cuerpo_eventos" role="button" class="">
                        <?php foreach ($ventas as $venta) :
                            $idTransaccion = $venta->getId();
                            $tipoTransaccion = $venta->getTipoActividad();
                        ?>
                        <tr id="<?= $venta->getId() ?>" class="vpEvento">
                            <!-- FECHA -->
                            <td id="<?= $venta->getId() ?>">
                                <?php
                                if (!is_null($venta->getFecha())) {
                                    echo ($venta->getFecha()->format('Y/m/d'));
                                }
                                ?></td>
                            <!-- TIPO -->
                            <td><?= ucfirst($venta->getTipoActividad()) ?></td>
                            <!-- NRO -->
                            <td><?= str_pad($venta->getNroTipoTransaccion(), 4, "0", STR_PAD_LEFT) ?></td>
                            <!-- IMPORTE -->
                            <td><?= ("$ " . number_format($venta->getMonto(), 2, ",", ".")); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- * * * * * * * * * * * * * * * DATATABLE COBROS * * * * * * * * * * * * * * * -->
    <div class="col-lg-6">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                COBROS
            </div>
            <div class="panel-body">
                <table id="tabla_cobros" class="display">
                    <thead>
                        <tr>
                            <th class="">Fecha</th>
                            <th class="">Tipo</th>
                            <th class="">Nro</th> 
                            <th class="">Importe</th>
                        </tr>
                    </thead>
                    <?php foreach ($cobros as $cobro) :
                            $idTransaccion = $cobro->getId();
                            $tipoTransaccion = $cobro->getTipoActividad();
                        ?>
                        <tr id="<?= $cobro->getId() ?>" class="vpEvento">
                            <!-- FECHA -->
                            <td id="<?= $cobro->getId() ?>">
                                <?php
                                if (!is_null($cobro->getFecha())) {
                                    echo ($cobro->getFecha()->format('Y/m/d'));
                                }
                                ?>
                            </td>
                            <!-- TIPO -->
                            <td id="<?= $cobro->getId() ?>" class="">
                                <?php
                                    if (!is_null($cobro->getTipoActividad())) {
                                        echo (ucfirst($cobro->getTipoActividad()));
                                    } else {
                                        echo ('No definido');
                                    }
                                ?>
                            </td>
                            <!-- NRO -->
                            <td><?= str_pad($cobro->getNroTipoTransaccion(), 4, "0", STR_PAD_LEFT) ?></td>
                            <!-- IMPORTE -->
                            <td><?= ("$ " . number_format($cobro->getMonto(), 2, ",", ".")); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- * * * * * * * * * * * * * * * RESUMEN * * * * * * * * * * * * * * * -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                RESUMEN
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- TOTAL VENTAS -->
    <div class="col-md-4">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-12">
                        <label>Total en Ventas</label>
                        <input type="text" class="form-control" name="total_ventas" id="total_ventas" value="$ 0.00" readonly>
                    </div>
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-12">
                        <label>Total Facturado</label>
                        <input type="text" class="form-control" name="total_facturado" id="total_facturado" value="$ 0.00" readonly>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- TOTAL CC -->
    <div class="col-md-4">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-12">
                        <label id="titulo_saldo">Saldo del cliente</label>
                        <input type="text" class="form-control" name="saldo_pendiente_cobro" id="saldo_pendiente_cobro" value="$ 0.00" readonly>
                    </div>
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-12">
                        <label>Pendiente a Facturar</label>
                        <input type="text" class="form-control" name="saldo_pendiente_factura" id="saldo_pendiente_factura" value="$ 0.00" readonly>
                    </div>
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-12">
                        <label id="titulo_gral">Cuenta Corriente Global</label>
                        <input type="text" class="form-control" name="cuenta_corriente_global" id="cuenta_corriente_global" value="$ 0.00" readonly>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- TOTAL COBROS -->
    <div class="col-md-4">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-12">
                        <label>Total en Cobros</label>
                        <input type="text" class="form-control" name="total_cobros" id="total_cobros" value="$ 0.00" readonly>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>

<script>
    calcularCuentaCorriente("CLIENTE");
</script>
