<?php

// pdf object
$pdf = new TCPDF('P','mm','A4');

// remove default header and footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// add a page
$pdf->AddPage();

// set font
$pdf->SetFont('helvetica', '', 7);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Titulo
// Print some HTML Cells
$html = '<strong style="font-size: 12px;">ORIGINAL</strong>';
$pdf->writeHTMLCell(0, '', '', '', $html, 'LRBT', 1, 0, true, 'C', true);
// $pdf->Ln(2);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Datos Personales y de Comprobante
$html = '
    <table border="0" cellspacing="0" cellpadding="4">
        <thead>
            <tr style="font-size: 14px; font-weight: bold;">
                <th align="center" width="45%">NOMBRE</th>
                <th align="center" width="10%" border="1">A</th>
                <th align="left" width="45%">TIPO COMPROBANTE</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td width="45%"><strong>Razón Social: </strong></td>
                <td align="center" width="10%">|</td>
                <td width="45%"><strong>Punto de Venta: </strong><strong>Comp Nro: </strong></td>
            </tr>
            <tr>
                <td width="45%"><strong>Domicilio Comercial: </strong></td>
                <td align="center" width="10%">|</td>
                <td width="45%"><strong>Fecha de Emisión: </strong></td>
            </tr>
            <tr>
                <td width="45%"><strong>Condición frente al IVA: </strong></td>
                <td align="center" width="10%">|</td>
                <td width="45%"><strong>CUIT: </strong></td>
            </tr>
            <tr>
                <td width="45%"></td>
                <td align="center" width="10%">|</td>
                <td><strong>Ingresos Brutos: </strong></td>
            </tr>
            <tr>
                <td width="45%"></td>
                <td align="center" width="10%">|</td>
                <td width="45%"><strong>Fecha de Inicio de Actividades: </strong></td>
            </tr>
        </tbody>
    </table>
';
// output the HTML content
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
$pdf->Ln(1);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Periodo de Facturacion y Fechas
$html = '
    <table border="0" cellspacing="0" cellpadding="3">
        <tbody>
            <tr>
                <td><strong>Período Facturado Desde: </strong></td>
                <td><strong>Hasta: </strong></td>
                <td><strong>Fecha de Vto. para el pago: </strong></td>
            </tr>
        </tbody>
    </table>
';
// output the HTML content
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
$pdf->Ln(1);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Datos del Comprador
$html = '
    <table border="0" cellspacing="0" cellpadding="3">
        <tbody>
            <tr>
                <td><strong>CUIT: </strong></td>
                <td><strong>Apellido y Nombre / Razón Social: </strong></td>
            </tr>
            <tr>
                <td><strong>Condición frente al IVA: </strong></td>
                <td><strong>Domicilio Comercial: </strong></td>
            </tr>
            <tr>
                <td><strong>Condición de Venta: </strong></td>
                <td></td>
            </tr>
        </tbody>
    </table>
';
// output the HTML content
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
$pdf->Ln(1);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// make the table items
$html = '
    <table border="0.5" cellspacing="0" cellpadding="3">
        <thead>
            <tr style="font-weight: bold;">
                <th align="center" width="8%"> Código</th>
                <th align="center" width="23%">Producto / Servicio</th>
                <th align="center" width="9%">Cantidad</th>
                <th align="center" width="10%">U. Medida</th>
                <th align="center" width="11%">Precio Unit.</th>
                <th align="center" width="8%">% Bonif</th>
                <th align="center" width="11%">Subtotal</th>
                <th align="center" width="9%"> Alicuota IVA</th>
                <th align="center" width="11%">Subtotal c/IVA</th>
            </tr>
        </thead>
';

// load json data


$html .= '
        <tbody>
            <tr>
                <td align="center" width="8%">. . .</td>
                <td align="center" width="23%">. . .</td>
                <td align="center" width="9%">. . .</td>
                <td align="center" width="10%">. . .</td>
                <td align="center" width="11%">. . .</td>
                <td align="center" width="8%">. . .</td>
                <td align="center" width="11%">. . .</td>
                <td align="center" width="9%">. . .</td>
                <td align="center" width="11%">. . .</td>
            </tr>
        </tbody>
    </table>
';
// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Ln(1);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Otros tributos
$html = '
    <table border="0" cellspacing="0" cellpadding="3">
        <thead>
            <tr>
                <th width="65%">  Otros Tributos</th>
                <th width="35%"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td width="65%">
                    <table border="0.5" cellspacing="0" cellpadding="3">
                        <thead>
                            <tr>
                                <th align="left" width="45%">Descripción</th>
                                <th align="left" width="30%">Detalle</th>
                                <th align="center" width="11%"> Alíc. %</th>
                                <th align="right" width="14%">Importe</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Per./Ret. de Impuesto a las Ganancias</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Per./Ret. de IVA</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Per./Ret. Ingresos Brutos</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Impuestos Internos</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Impuestos Municipales</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
                <td width="35%">
                    <table border="0" cellspacing="0" cellpadding="3">
                        <tbody>
                            <tr>
                                <td align="right" width="70%"><strong>Importe Neto Gravado: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>IVA 27%: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>IVA 21%: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>IVA 10.5%: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>IVA 5%: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>IVA 2.5%: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>IVA 0%: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>Importe Otros Tributos: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                            <tr>
                                <td align="right" width="70%"><strong>Importe Total: $</strong></td>
                                <td align="right" width="30%">...</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
';
// output the HTML content
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, '', true);
$pdf->Ln(1);

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

// Print some HTML Cells
$html = '<p> "SOFTWARE HUELLA" </p>';
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, 'C', true);

// reset pointer to the last page
$pdf->lastPage();

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

//Close and output PDF document
$pdf->Output('example_006.pdf', 'I');
