<?php 
$url1 =""; $url2=""; $url3=""; $label=""; $label3="";
if ($tipo == "cliente"){
    $url1 = "/clientes";
    $url2= "/clientes/categoria/cliente";
    $label = "Clientes";
}
if ($tipo == "proveedor"){
    $url1 = "/proveedores";
    $url2= "/proveedores/categoria/proveedor";
    $label = "Proveedores";
}
if ($tipo== "iva"){
    $url1 ="/herramientas";
    $label = "Herramientas";
    $url2= "/herramientas/categorias/iva";
}
if ($tipo== "producto"){
    $url1 ="/productosservicios";
    $label = "Productos y Servicios";
    $url3= "/productosservicios/productos";
    $label3="Productos";
    $url2= "/productosservicios/productos/categorias/producto";
}if ($tipo== "servicio"){
    $url1 ="/productosservicios";
    $label = "Productos y Servicios";
    $url3= "/productosservicios/servicios";
    $label3="Servicios";
    $url2= "/productosservicios/servicios/categorias/servicio";
}
// if ($tipo== "licencia"){
//     $url1 ="/productosservicios";
//     $label = "Productos y Servicios";
//     $url3= "/productosservicios/licencias";
//     $label3="Licencias";
//     $url2= "/productosservicios/licencias/categorias/licencia";
// }
?>
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="<?php echo ($url1);?>"><?php echo ($label);?></a></li>
            <?php if ($url3 !=""){ ?>
                <li class="breadcrumb-item"><a href="<?php echo ($url3);?>"><?php echo ($label3);?></a></li>
            <?php } ?>
            <li class="breadcrumb-item"><a href="<?php echo ($url2);?>">Categorias</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?php echo ($url2);?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<form method="post">
    <div class="container margen">
        <div class="row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                EDITAR CATEGORÍA
                </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label>Nombre de Categoría</label>
                            <input type="text" class="form-control" name="nombre"
                                value="<?= $categoriaevento->getNombre(); ?>">
                        </div>
                        <div class="form-group col-md-4">
                            <label>Descripción</label>
                            <input type="text" class="form-control" name="descripcion"
                                value="<?= $categoriaevento->getDescripcion(); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Inicio: Modal -->
    <div class="container">   
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel">Editar categoría</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>¿Está seguro que desea editar los datos de esta categoría?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default">Aceptar</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>    
    </div>
    <!-- Fin: Modal -->

    <!-- Inicio: Panel Botones -->
    <div class="container margen">
        <div class="row img-centrar">
            <div class="col ficha-cliente-p img-centrar">
                <div>
                    <a data-toggle="modal" data-target="#myModal">
                        <img role="button" src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                            class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom">
                    </a>
                </div>
                <div class="ficha-cliente-label">
                    <label>Guardar</label>
                </div>
            </div>

            <div class="col ficha-cliente-p img-centrar">
                <div>
                   
                        <a href="<?= $volver ?>">
                        <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom">
                    </a>
                </div>
                <div class="ficha-cliente-label">
                    <label>Volver</label>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin: Panel Botones -->
</form>