<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script>
    $(document).ready(function() {
        $('#tabla_tipoevento').DataTable({
            "order": [0, 'desc'],

            "language": {
                "url": "/json/spanish.json"
            }
        });
    });
</script>

<?php
if (isset($_SESSION['MENSAJES']['tipo_evento'])) {
    if ($_SESSION['MENSAJES']['tipo_evento']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['tipo_evento_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['tipo_evento_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['tipo_evento'] = null;
    $_SESSION['MENSAJES']['tipo_evento_msj'] = null;
}
$titulo="LISTADO DE CATEGORÍAS";
if ($tipo == "iva"){$titulo= "LISTADO DE CONDICIÓN DE IVA";}
$url =""; $url2=""; $label=""; $label2 ="";
if ($tipo == "cliente"){
    $url = "/clientes";
    $label = "Clientes";
}
if ($tipo == "proveedor"){
    $url = "/proveedores";
    $label = "Proveedores";
}

if ($tipo== "producto"){
    $url ="/productosservicios/productos";
    $label = "Productos";
    $url2="/productosservicios";
    $label2="Productos y Servicios";
}
if ($tipo== "servicio"){
    $url ="/productosservicios/servicios";
    $label = "Servicios";
    $url2="/productosservicios";
    $label2="Productos y Servicios";
}
if ($tipo== "iva"){
    $url="/herramientas";
    $label="Herramientas";
}
?>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <?php if ($url2!=""){?>
                <li class="breadcrumb-item"><a href="<?php echo ($url2);?>"><?php echo ($label2);?></a></li>
            <?php }?>
            <li class="breadcrumb-item"><a href="<?php echo ($url);?>"><?php echo ($label);?></a></li>
            <li class="breadcrumb-item active" aria-current="page">Categorias</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?php echo ($url);?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Tipo-Evento -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                <?php echo ($titulo)?>
                <a data-toggle="collapse" data-parent="#accordion" href="#add_tipo_evento" 
                    aria-expanded="true" aria-controls="add_tipo_evento">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-menu-hamburger btn-collapse"></i></span>
                </a>
            </div>
        <div class="panel panel-body">
            <div class="collapse" id="add_tipo_evento">
                <form method="post">
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <label>Nombre de Categoria</label>
                            <input type="text" class="form-control" name="nombre" placeholder="Nombre de Categoría" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Descripción</label>
                            <input type="text" class="form-control" name="descripcion" placeholder="Descripción">
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                                <span class="glyphicon glyphicon-plus" ></span> Agregar categoría
                            </button>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Agregar categoría</h4>
                                </div>
                                <div class="modal-body">
                                    <p>¿Está seguro que desea agregar esta categoría?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-default">Aceptar</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="container">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table id="tabla_tipoevento" class="display">
                        <thead>
                            <tr>
                                <th class="th-sm" onclick="sortTableString(1, 'tabla_tipoevento')" style="width:35%;">
                                    Nombre de Categoría <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                </th>
                                <th class="th-sm" onclick="sortTableString(1, 'tabla_tipoevento')" style="width:55%;">
                                    Descripción <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                </th>
                                <th style="width:10%;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if (isset($categorias)) {
                                foreach ($categorias as $categoria) :
                                ?>
                                    <tr>
                                        <td><?php echo ($categoria->getNombre()); ?></td>
                                        <td><?php echo ($categoria->getDescripcion()); ?></td>
                                        <td>
                                            <div class="pull-right">
                                                <a class="btn btn-default btn-sm" href="<?= $this->url('categoria/editar', ['action' => 'edit', 'tipo' => $tipo, 'id' => $categoria->getId()]); ?>">
                                                    <span class="glyphicon glyphicon-pencil" ></span> 
                                                </a>
                                                <button name="<?= $categoria->getId() ?>" id="<?= $categoria->getId() ?>" type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal<?= $categoria->getId() ?>">
                                                    <span class="glyphicon glyphicon-trash" ></span>
                                                </button>
                                            </div>
                                        </td>
                                        <!-- Modal -->
                                <div id="myModal<?= $categoria->getId() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Borrar cliente</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    ¿Está seguro que desea eliminar el tipo de actividad: 
                                                    "<?= $this->escapeHtml($categoria->getNombre()) ?>"?
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="<?= $this->url('categoria/borrar', ['action' => 'remove', 'id' => $categoria->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                                                <span class="btn btn-default">Aceptar</span></a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </tr>
                            <?php endforeach; } ?>
                        </tbody>
                    </table> 
                </div>
            </div> 
        </div>         
    </div>
</div>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
            <a href="<?= $volver ?>">

                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->