<!-- scripts -->
<script src="/js/proveedores.js"></script>

<?php
$title = 'Agregar Proveedor';
$this->headTitle($title);
?>
<form method="post">
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/proveedores">Proveedores</a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar Proveedor</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="/proveedores" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Inicio: Datos Generales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS GENERALES
            </div>
            <div class="panel-body">
                <!-- Fila 1 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Nombre y Apellido *</label>
                        <input type="text" class="form-control requerido" name="nombre" placeholder="Ingresar Nombre y Apellido" required>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Teléfono</label>
                        <input type="text" class="form-control" name="telefono" placeholder="Ingresar Teléfono">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Email</label>
                        <input type="text" class="form-control" name="email" placeholder="Ingresar Email">
                    </div>
                   
                    
                </div>
                <!-- Fila 2 -->
                <div class="row form-row">
                     <div class="form-group col-md-4">
                        <label>País</label>
                        <select class="form-control place_holder dropdown" id="pais" name="pais" onchange="actualizarDatosProvincias(this.value)" >
                            <option value="-1" hidden="">Seleccionar País</option>
                            <?php foreach ($paises as $pais) : ?>
                                <option value="<?php echo ($pais->getId()); ?>"><?php echo ($pais->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Provincia</label>
                        <div id="div_provincias">
                            <option value="-1" hidden=""></option>
                            <select class="form-control place_holder dropdown" id="ops_provincias" name="provincia">
                            </select>
                        </div>
                    </div> 
                    <div class="form-group col-md-4">
                        <label>Ciudad</label>
                        <input type="text" class="form-control" name="ciudad" placeholder="Ingresar Ciudad">
                    </div>
                    
                </div>
                <!-- Fila 3 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Categoría</label>
                        <select class="form-control place_holder dropdown" id="categoria" name="categoria">
                            <option value="-1" hidden="">Seleccionar Categoría</option>
                            <?php foreach ($categorias as $categoria) : ?>
                            <option value="<?php echo ($categoria->getId()); ?>"><?php echo ($categoria->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Skype</label>
                        <input type="text" class="form-control" name="skype" placeholder="Ingresar Skype">
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>
<!-- Fin: Datos Generales -->

<!-- Inicio: Datos Laborales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS LABORALES
            </div>
            <div class="panel panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Empresa</label>
                        <input type="text" class="form-control" name="empresa" placeholder="Ingresar Empresa">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Cargo</label>
                        <input type="text" class="form-control" name="cargo" placeholder="Ingresar Cargo">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Tipo de Nogocio</label>
                        <input type="text" class="form-control" name="actividad" placeholder="Ingresar Tipo de Negocio">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
<!-- Fin: Datos Laborales -->

<!-- Inicio: Datos de Facturacion -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS DE FACTURACIÓN
            </div>
            <div class="panel panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Razón Social</label>
                        <input type="text" class="form-control" name="razon_social" placeholder="Ingresar Razón Social">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Condición de IVA</label>
                        <select class="form-control place_holder dropdown" id="condicion_iva" name="condicion_iva">
                            <option value="-1" hidden="">Seleccionar</option>
                            <option value="-1">No definido</option>
                            <?php foreach ($condiciones_iva as $condicion_iva) : ?>
                                <option value="<?php echo ($condicion_iva->getId()); ?>"><?php echo ($condicion_iva->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Tipo de Factura</label>
                        <select class="form-control  place_holder dropdown" id="tipo_comprobante" name="tipo_comprobante">
                            <option value="" hidden="">Seleccionar</option>
                            <option value="-1">No definido</option>
                            <?php foreach ($tiposFactura as $tipo_comprobante) : ?>
                                <option value="<?php echo ($tipo_comprobante->getId()); ?>"><?php echo ($tipo_comprobante->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>          
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>Banco</label>
                        <input type="text" class="form-control" name="banco" placeholder="Ingresar Banco">
                    </div>
                    <div class="form-group col-md-2">
                        <label>CUIT/CUIL</label>
                        <input type="text" class="form-control" name="cuit_cuil" placeholder="Ingresar CUIT/CUIL">
                    </div>
                    <div class="form-group col-md-4">
                        <label>CBU</label>
                        <input type="text" class="form-control" name="cbu" placeholder="Ingresar CBU">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Dirección de Facturación</label>
                        <input type="text" class="form-control" name="direccion_facturacion" placeholder="Ingresar Dirección de Facturación">
                    </div>         
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos de Facturacion -->


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Agregar Proveedor</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea agregar este Proveedor?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default">Aceptar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Fin: Proveedor Nuevo -->
</form>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar"> 
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>                   
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>       
</div>
<!-- Fin: Panel Botones -->


