<?php
$title = 'Editar Proveedor';
$this->headTitle($title);
$id = $proveedor->getPersona()->getId();
$nombre = $persona->getNombre();
$telefono = $persona->getTelefono();
$email = $persona->getEmail();
$pais = $proveedor->getPais();
$provincia = $proveedor->getProvincia();
$ciudad = $proveedor->getCiudad();
$empresa = $proveedor->getEmpresa();
$categoria = $proveedor->getCategoria();
$licencia = $proveedor->getLicencia();
$version = $proveedor->getVersion();
$profesion = $proveedor->getProfesion();
$condicion_iva = $proveedor->getCondicion_iva();
$actividad = $proveedor->getActividad();
$cargo = $proveedor->getCargo();
$skype = $proveedor->getSkype();
?>

<!-- Inicio: Datos Generales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">
                DATOS PARTICULARES
            </div>
            <div class="panel panel-body">
                <form method="post">
                    <!-- 1ra fila -->
                    <div class="row form-row">  
                        <input type="hidden" name="id" value="<?= $id ?>">
                        <div class="form-group col-md-4">
                            <label>Nombre</label>
                            <input type="text" class="form-control" name="nombre" value="<?php echo($nombre); ?>" placeholder="Ingresar Nombre">
                        </div>
                        <div class="form-group col-md-4">
                            <label>País</label>
                            <select class="form-control" id="pais" name="pais" onchange="actualizarDatosProvincias(this.value)">
                                <option value="<?php if(isset($pais)){ echo ($pais->getId()); }?>" hidden="">  
                                    <?php if(isset($pais)){ echo($pais->getNombre()); } else {echo ("Seleccionar País");}?>
                                </option>
                                <?php foreach ($paises as $pais) : ?>
                                    <option value="<?php echo ($pais->getId()); ?>"><?php echo ($pais->getNombre()); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Categoría</label>
                            <select class="form-control" id="categoria" name="categoria">
                                <option value="<?php if(isset($categoria)){ echo ($categoria->getId()); }?>" hidden="">  
                                    <?php if(isset($categoria)){ echo($categoria->getNombre()); } else {echo ("Seleccionar Categoría");}?>
                                </option>                           
                                <?php foreach ($categorias as $categoria) : ?>
                                    <option value="<?php echo ($categoria->getId()); ?>"><?php echo ($categoria->getNombre()); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div> 
                    </div>
                    <!-- 2da fila -->
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <label>Teléfono</label>
                            <input type="text" class="form-control" name="telefono" value="<?php echo($telefono); ?>" placeholder="Ingresar Teléfono">
                        </div>
                        <div class="form-group col-md-4" id="div_provincias">
                            <label>Provincia</label>
                            <select class="form-control" id="ops_provincias" name="provincia" required="">
                                <option value="<?php if(isset($provincia)){ echo ($provincia->getId()); }?>" hidden="">  
                                    <?php if(isset($provincia)){ echo($provincia->getNombre_provincia()); } else {echo ("Seleccionar Provincia");}?>
                                </option>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Skype</label>
                            <input type="text" class="form-control" name="skype" value="<?php echo($skype); ?>" placeholder="Ingresar Skype">
                        </div> 
                    </div>
                    <!-- 3ra fila -->
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <label>Email</label>
                            <input type="text" class="form-control" name="email" 
                                value="<?php echo($email); ?>" placeholder="Ingresar Email">
                        </div>
                        <div class="form-group col-md-4">
                            <label>Ciudad</label>
                            <input type="text" class="form-control" name="ciudad" value="<?php echo($ciudad); ?>" placeholder="Ingresar Ciudad">
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos Generales -->

<!-- Inicio: Datos Laborales -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">
                DATOS LABORALES
            </div>
            <div class="panel panel-body">
                <!-- Fila 1 -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Empresa</label>
                        <input type="text" class="form-control" name="empresa"
                            value="<?php echo($empresa); ?>" placeholder="Ingresar Empresa">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Cargo</label>
                        <input type="text" class="form-control" name="cargo"
                            value="<?php echo($cargo); ?>" placeholder="Ingresar Actividad">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Tipo de Negocio</label>
                        <input type="text" class="form-control" name="actividad" 
                            value="<?php echo($actividad); ?>" placeholder="Ingresar Actividad">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos Laborales -->

<!-- Inicio: Datos de Facturacion -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">
                DATOS DE FACTURACIÓN
            </div>
            <div class="panel panel-body">
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Razón Social</label>
                        <input type="text" class="form-control" name="razon_social" 
                            value="<?= $proveedor->getRazon_social(); ?>" placeholder="Ingresar Razón Social">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Condición de IVA</label>
                        <select class="form-control" id="condicion_iva" name="condicion_iva">
                            <option value="<?php if(isset($condicion_iva)){ echo ($condicion_iva->getId()); }?>" hidden="">  
                                <?php if(isset($condicion_iva)){ echo($condicion_iva->getNombre()); } else {echo ("Seleccionar");}?>
                            </option>
                            <option value="-1">NO DEFINIDO</option>
                            <?php foreach ($condiciones_iva as $condicion_iva) : ?>
                                <option value="<?php echo ($condicion_iva->getId()); ?>"><?php echo ($condicion_iva->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Banco</label>
                        <input type="text" class="form-control" name="banco" 
                            value="<?= $proveedor->getBanco(); ?>" placeholder="Ingresar Banco">
                    </div>
                </div>
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Dirección de Facturación</label>
                        <input type="text" class="form-control" name="direccion_facturacion" 
                            value="<?= $proveedor->getDireccion_facturacion(); ?>" placeholder="Ingresar Dirección de Facturación">
                    </div>
                    <div class="form-group col-md-4">
                        <label>CUIT/CUIL</label>
                        <input type="text" class="form-control" name="cuit_cuil"
                        value="<?= $proveedor->getCuit_cuil(); ?>" placeholder="Ingresar CUIT/CUIL">
                    </div>
                    <div class="form-group col-md-4">
                        <label>CBU</label>
                        <input type="text" class="form-control" name="cbu"
                            value="<?= $proveedor->getCbu(); ?>" placeholder="Ingresar CBU">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos de Facturacion -->


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modificar proveedor</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea modificar los datos este proveedor?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default">Aceptar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>

    </div>
</div>

</form>

<!-- Fin: Cliente Nuevo -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal"><img src="<?= $this->basePath('img/crm/aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm" role="button"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('proveedores/ficha', ['action' => 'ficha', 'id' => $id]) ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->
