<?php
$this->headTitle('Detalles del Proveedor');
$id_cliente = $this->proveedor->getId();

if (isset($_SESSION['MENSAJES']['ficha_cliente'])) {
    if ($_SESSION['MENSAJES']['ficha_cliente']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['ficha_cliente_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['ficha_cliente_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['ficha_cliente'] = null;
    $_SESSION['MENSAJES']['ficha_cliente_msj'] = null;
}
?>

<!-- <link rel="stylesheet" type="text/css" href="public/DataTables/datatables.min.css"/>
<script type="text/javascript" charset="utf8" src="DataTables/datatables.min.js"></script> -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script>
    $(document).ready( function () {
        $('#table_id').DataTable({
            "order": [ 0, 'desc' ],

            "language": {
            "url": "/json/spanish.json"
            }
        });
    } );
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb secondary-color navbar-menu-font">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/proveedores">Proveedores</a></li>
            <li class="breadcrumb-item"><a href="/proveedores/listado">Listado</a></li>
            <li class="breadcrumb-item active" aria-current="page">Ficha Proveedor</li>
        </ol>
    </nav>
</div>

<!-- Inicio: Datos de Proveedor -->
<div class="container margen">
    <div class="row">
        <!-- Datos de Perfil -->
        <div class="col-md-7">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    DATOS DE PERFIL
                </div>
                <div class="panel-body padding-top-cero" style="min-height: 325px;">
                    <div class="ficha-cliente-p img-centrar ">
                        <div>
                            <figure>
                                <a href="<?= $this->url(
                                                'proveedores/editar',
                                                ['tipo' => 'proveedor', 'id' => (int)$persona->getId()]
                                            ) ?>" role="button">
                                    <img src="<?= $this->basePath('img/crm/perfil.png') ?>" class="img-circle img-responsive img-texto-derecha" width="150px" height="150px" style="margin-left:0px;">
                                </a>
                                <figcaption class="text-center"></figcaption>
                            </figure><br>
                        </div>
                        <div class="ficha-cliente-label padding-md">
                            <h4>
                                <?= $persona->getNombre(); ?>
                            </h4>
                            <p><i>
                                    <?php echo ($proveedor->getNombreCategoriaProveedor()); ?></i></p>
                            <p><span class="glyphicon glyphicon-earphone"></span>&nbsp;&nbsp;
                                <?php echo ($persona->getTelefono()); ?>
                            </p>
                            <p><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;
                                <?php echo ($persona->getEmail()); ?>
                            </p>
                            <p><span><img src="<?= $this->basePath('img/crm/skype.png') ?>" width="15" height="15"></span>
                                &nbsp;
                                <?php echo ($proveedor->getSkype()); ?>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6 ficha-cliente-p margen-bot-cero">
                            <p><label>Empresa:</label>
                                <?= $proveedor->getEmpresa(); ?>
                            </p>
                            <p><label>Actividad:</label>
                                <?= $proveedor->getActividad(); ?>
                            </p>
                            <p><label>Cargo:</label>
                                <?= $proveedor->getCargo(); ?>
                            </p>
                        </div>
                        <div class="col-sm-6 ficha-cliente-p">
                            <p><label>Fecha Compra:</label>
                                <?php
                                if (!is_null($proveedor->getFechaCompra())) {
                                    echo ($proveedor->getFechaCompra()->format('d/m/Y'));
                                }
                                ?>
                            </p>
                            <p><label>Último Pago:</label>
                                <?php
                                if (!is_null($proveedor->getFechaUltimoPago())) {
                                    echo ($proveedor->getFechaUltimoPago()->format('d/m/Y'));
                                }
                                ?>
                            </p>
                            <p><label>Último Contacto:</label>
                                <?php
                                if (!is_null($proveedor->getFechaUltimoContacto())) {
                                    echo ($proveedor->getFechaUltimoContacto()->format('d/m/Y'));
                                }
                                ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Datos Generales -->
        <div class="col-md-5">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    DATOS GENERALES
                </div>
                <div class="panel-body" style="min-height: 325px;">
                    <div class="ficha-cliente-p margen">
                        <p><label>Razón Social:</label>
                            <?= $proveedor->getRazon_social(); ?>
                        </p>
                        <p><label>Dirección de Facturación:</label>
                            <?= $proveedor->getDireccion_facturacion(); ?>
                        </p>
                        <p><label>Ciudad:</label>
                            <?php echo ($proveedor->getCiudad()); ?>
                        </p>
                        <p><label>Provincia:</label>
                            <?php echo ($proveedor->getNombreProvinciaProveedor()); ?>
                        </p>
                        <p><label>País:</label>
                            <?php echo ($proveedor->getNombrePaisProveedor()); ?>
                        </p>
                        <br>
                        <p><label>Condición de IVA:</label>
                            <?= $proveedor->getNombreCondicionIva(); ?>
                        </p>
                        <p><label>Banco:</label>
                            <?= $proveedor->getBanco(); ?>
                        </p>
                        <p><label>CBU:</label>
                            <?= $proveedor->getCbu(); ?>
                        </p>
                        <p><label>CUIT/CUIL:</label>
                            <?= $proveedor->getCuit_cuil(); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Datos de Proveedor -->

<!-- Inicio: Actividades -->
<div class="container margen">
    <div class="container row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                REGISTRO DE EVENTOS
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseActividades" aria-expanded="true" aria-controls="collapseActividades">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-down btn-collapse" id="actividades" onclick="cambiaIconoCollapse(event)"></i></span>
                </a>
            </div>
            <div class="panel-body padding-top-cero">
                <div class="collapse in" id="collapseActividades">
                    <div class="row padding-bot-md">
                        <!-- Transacciones -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-default" style="font-weight: bold;">Transacciones</button>
                            <a role="button" class="btn btn-default" data-toggle="collapse" 
                                data-parent="#accordion" href="#drop" aria-expanded="true" aria-controls="drop">
                                <span class="glyphicon glyphicon-chevron-down" ></span>
                            </a>
                        </div>
                        <!-- Acción Comercial -->
                        <div class="btn-group">
                            <button role="button" class="btn btn-default" style="font-weight: bold;">Acción Comercial</button>
                            <a href="<?= $this->url('evento', ['action' => 'add', 'tipo' => 'proveedor', 'id' => $persona->getId()]) ?>"
                                class="btn btn-default">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </a>
                        </div>
                        <!-- Eliminar Evento -->
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default" style="font-weight: bold;">Eliminar Evento</button>
                            <a role="button" class="btn btn-default" data-toggle="modal" data-target="#eventoModal">
                                <span class="glyphicon glyphicon-minus" ></span>
                            </a>
                        </div> 
                    </div>

                    <!-- Transaccion-->
                    <div class="row">
                        <div class="collapse" id="drop">
                            <ul class="list-inline" style="margin-left: 20px;">
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Presupuesto
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Pedido
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Remito
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Factura
                                        </div>
                                    </a>
                                </li>
                            </ul>
                            <ul class="list-inline" style="margin-left: 20px;">
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Pago
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Nota de Crédito
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Nota de Débito
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="padding-cero">
                                        <div class="col img-centrar">
                                            <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm">
                                            Nota de Crédito Cond. Pago
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <table id="table_id" class="display">
                        <thead>
                            <tr>
                                <th class="" id="fila">Fecha</th>
                                <th class="">Responsable</th>
                                <th class="">Tipo</th>
                                <th class="detalle-width">Detalle</th>
                                <th class=""></th>
                            </tr>
                        </thead>
                        <tbody role="button" class="">
                            <?php foreach ($eventos as $evento) : ?>
                            <tr id="<?= $evento->getId() ?>" onclick="seleccionarFila(event)">
                                <td id="<?= $evento->getId() ?>" class="">
                                    <?php
                                    if (!is_null($evento->getFecha())) {
                                        echo ($evento->getFecha()->format('Y/m/d'));
                                    }
                                    ?>
                                </td>
                                <td id="<?= $evento->getId() ?>" class="">
                                    <?php echo ($evento->getUsuarioEjecutivo()); ?>
                                </td>
                                <td id="<?= $evento->getId() ?>" class="">
                                    <?php
                                    if (!is_null($evento->getTipo())) {
                                        echo ($evento->getTipo());
                                    } else {
                                        echo ('No definido');
                                    }
                                    ?>
                                </td>
                                <td id="<?= $evento->getId() ?>" class="table-scroll-description">
                                    <?php echo (nl2br($evento->getDescripcion())); ?>
                                </td>
                                <td id="<?= $evento->getId() ?>" class="">
                                    <button name="<?= $evento->getId() ?>" id="<?= $evento->getId() ?>" type="button"
                                        class="btn btn-default btn-sm" data-toggle="modal" data-target="#vpEventoModal<?= $evento->getId() ?>">
                                        <span class="glyphicon glyphicon-eye-open" ></span>
                                    </button>
                                </td>
                                
                                <!-- Modal Vista Previa Evento -->
                                <div id="vpEventoModal<?= $evento->getId() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title"> <?php 
                                                    if (!is_null($evento->getFecha())) {
                                                        echo($evento->getFecha()->format('Y/m/d') . " - " 
                                                            . $evento->getTipo());
                                                    } ?> 
                                                </h4>
                                            </div>
                                            <div class="modal-body">
                                                <?php echo(nl2br($evento->getDescripcion())); ?>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Actividades -->

<!-- Modal Ciente -->
<div class="modal fade" id="exampleModal<?= $proveedor->getId() ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Eliminar cliente</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    ¿Está seguro que desea eliminar el cliente:
                    "
                    <?= $this->escapeHtml($persona->getNombre()) ?>"
                    ?<br>
                    <?php
                    if ($persona->getEstado() == "S") {
                        echo ('Se establecerá como Inactivo.');
                    } else {
                        echo ('Se establecerá como Activo.');
                    }
                    ?>
                </p>
            </div>
            <div class="modal-footer">
                <a href="<?= $this->url('proveedores/modificarEstado', ['action' => 'modificarEstado', 'id' => (int)$proveedor->getId()]) ?>" type="button">
                    <span class="btn btn-default">Aceptar</span></a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Evento -->
<div class="modal fade" id="eventoModal" tabindex="-1" role="dialog" aria-labelledby="eventoModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="eventoModalLabel">Eliminar evento</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar los eventos seleccionados?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" onclick="eliminaEventos()">Aceptar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <!-- Modificar Datos -->
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('proveedores/editar', ['tipo' => 'proveedor', 'id' => (int)$persona->getId()]) ?>" role="button">
                    <img src="<?= $this->basePath('img/crm/proveedor_update_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Modificar</label><br>
                <label>Datos</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a role="button" name="<?= $proveedor->getId() ?>" id="<?= $proveedor->getId() ?>" data-toggle="modal" data-target="#exampleModal<?= $proveedor->getId() ?>">
                    <img src="<?php
                                if ($persona->getEstado() == " S") {
                                    echo ($this->basePath('img/crm/proveedor_remove_v.png'));
                                } else {
                                    echo ($this->basePath('img/crm/proveedor_add_v.png'));
                                }
                                ?>" class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <?php
                if ($persona->getEstado() == "S") {
                    echo ('<label>Eliminar</label><br>'
                        . '<label>Proveedor</label>');
                } else {
                    echo ('<label>Agregar</label><br>'
                        . '<label>Proveedor</label>');
                }
                ?>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>   
                <a href="<?= $volver ?>" role="button">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-proveedor-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones --> 