<!-- scripts -->
<script src="/js/proveedores.js"></script>

<?php
$this->headTitle('Detalles del Proveedor');
// if (isset($_SESSION['MENSAJES']['ficha_cliente'])) {
//     if ($_SESSION['MENSAJES']['ficha_cliente']) {
//         echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['ficha_cliente_msj'] . "', 'success');});</script>";
//     } else {
//         echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['ficha_cliente_msj'] . "', 'error');});</script>";
//     }
//     $_SESSION['MENSAJES']['ficha_cliente'] = null;
//     $_SESSION['MENSAJES']['ficha_cliente_msj'] = null;
// }

$id_persona = $persona->getId();
$tipo_persona = strtolower($persona->getTipo());
?>

<!-- <link rel="stylesheet" type="text/css" href="public/DataTables/datatables.min.css"/>
<script type="text/javascript" charset="utf8" src="DataTables/datatables.min.js"></script> -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<script>
    $(document).ready( function () {
        $('#table_id').DataTable({
            "order": [ 0, 'desc' ],

            "language": {
            "url": "/json/spanish.json"
            }
        });
    } );
    var tipo_persona= "<?= $tipo_persona ?>";
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/proveedores">Proveedores</a></li>
            <li class="breadcrumb-item"><a href="/proveedores/listado">Listado</a></li>
            <li class="breadcrumb-item active" aria-current="page">Ficha Proveedor</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
        style="margin:0px;">
            <li class="pull-right"><a href="/proveedores/listado" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<!-- Inicio: Datos de Proveedor -->
<div class="container margen">
    <div class="row">
        <!-- Datos de Perfil -->
        <div class="col-md-7">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    DATOS DE PERFIL
                </div>
                <div class="panel-body padding-top-cero" style="min-height: 325px;">
                    <div class="ficha-cliente-p img-centrar ">
                        <div>
                            <figure>
                                <a href="<?= $this->url(
                                                'proveedores/editar',
                                                ['tipo' => 'proveedor', 'id' => (int)$persona->getId()]
                                            ) ?>" role="button">
                                    <img src="<?= $this->basePath('img/crm/perfil.png') ?>" class="img-circle img-responsive img-texto-derecha" width="150px" height="150px" style="margin-left:0px;">
                                </a>
                                <figcaption class="text-center"></figcaption>
                            </figure><br>
                        </div>
                        <div class="ficha-cliente-label padding-md">
                            <h4>
                                <?= $persona->getNombre(); ?>
                            </h4>
                            <p><i><?php echo ("Nro. Proveedor: " . str_pad($persona->getId(), 4, "0", STR_PAD_LEFT) . " - " . $proveedor->getNombreCategoriaProveedor()); ?></i></p>
                            <p><span class="glyphicon glyphicon-earphone"></span>&nbsp;&nbsp;
                                <?php echo ($persona->getTelefono()); ?>
                            </p>
                            <p><span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;
                                <?php echo ($persona->getEmail()); ?>
                            </p>
                            <p><span><img src="<?= $this->basePath('img/crm/skype.png') ?>" width="15" height="15"></span>
                                &nbsp;
                                <?php echo ($proveedor->getSkype()); ?>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6 ficha-cliente-p margen-bot-cero">
                            <p><label>Empresa:</label>
                                <?= $proveedor->getEmpresa(); ?>
                            </p>
                            <p><label>Actividad:</label>
                                <?= $proveedor->getActividad(); ?>
                            </p>
                            <p><label>Cargo:</label>
                                <?= $proveedor->getCargo(); ?>
                            </p>
                        </div>
                        <div class="col-sm-6 ficha-cliente-p">
                            <p><label>Primera Compra:</label>
                                <?php
                                if (!is_null($proveedor->getFechaCompra())) {
                                    echo ($proveedor->getFechaCompra()->format('d/m/Y'));
                                }
                                ?>
                            </p>
                            <p><label>Último Pago:</label>
                                <?php
                                if (!is_null($proveedor->getFechaUltimoPago())) {
                                    echo ($proveedor->getFechaUltimoPago()->format('d/m/Y'));
                                }
                                ?>
                            </p>
                            <p><label>Último Contacto:</label>
                                <?php
                                if (!is_null($proveedor->getFechaUltimoContacto())) {
                                    echo ($proveedor->getFechaUltimoContacto()->format('d/m/Y'));
                                }
                                ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Datos Generales -->
        <div class="col-md-5">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    DATOS GENERALES
                </div>
                <div class="panel-body" style="min-height: 325px;">
                    <div class="ficha-cliente-p margen">
                        <p><label>Razón Social:</label>
                            <?= $persona->getRazon_social(); ?>
                        </p>
                        <p><label>Dirección de Facturación:</label>
                            <?= $persona->getDireccion_facturacion(); ?>
                        </p>
                        <p><label>Ciudad:</label>
                            <?php echo ($proveedor->getCiudad()); ?>
                        </p>
                        <p><label>Provincia:</label>
                            <?php echo ($proveedor->getNombreProvinciaProveedor()); ?>
                        </p>
                        <p><label>País:</label>
                            <?php echo ($proveedor->getNombrePaisProveedor()); ?>
                        </p>
                        <br>
                        <p><label>Condición de IVA:</label>
                            <?= $persona->getNombreCondicionIva(); ?>
                        </p>
                        <p><label>Tipo de Factura:</label> <?= $persona->getNombreTipoFactura(); ?></p>
                        <p><label>Banco:</label>
                            <?= $persona->getBanco(); ?>
                        </p>
                        <p><label>CBU:</label>
                            <?= $persona->getCbu(); ?>
                        </p>
                        <p><label>CUIT/CUIL:</label>
                            <?= $persona->getCuit_cuil(); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- Datos Adicionales -->
<div class="container row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                DATOS ADICIONALES
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseDatosAdicionales" aria-expanded="true"
                    aria-controls="collapseDatosAdicionales">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-menu-hamburger btn-collapse"
                            id="d_adicionales" ></i></span>
                </a>
            </div>

            <div class="collapse" id="collapseDatosAdicionales">
                <div class="panel panel-body">
                    <table id="tabla_evento" class="table table-condensed table-hover">
                        <thead>
                            <tr>
                                <th class="th-sm">Dato o Referencia</th>
                                <th class="th-sm">Descripción</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($datos_adicionales as $dato_adicional) :
                                $url = 'clientes/ficha';
                                $referencia = $dato_adicional->getId_referencia_persona();
                                if(is_null($referencia)){
                                    $referencia = "";
                                } else {
                                    $referencia = $dato_adicional->getId_referencia_persona()->getId();
                                    if($dato_adicional->getId_referencia_persona()->getTipo() == "PROVEEDOR"){
                                        $url = 'proveedores/ficha';
                                    }
                                }; ?>
                            <tr>
                                <td>
                                    <!-- Dato -->
                                    <?php if($referencia == "") {echo ($dato_adicional->getDato_adicional());} ?>
                                    <!-- Referencia -->
                                    <a href="<?= $this->url($url, ['action' => 'ficha', 'id' => $referencia]); ?>" 
                                        <?php if($referencia == ""){echo ("hidden");} ?> target="_blank">
                                        <label role="button"><?= $dato_adicional->getDato_adicional() ?></label> 
                                        <span class="glyphicon glyphicon-share"></span>
                                    </a>
                                </td>
                                <!-- Descripcion -->
                                <td><?php echo ($dato_adicional->getDescripcion()); ?></td>
                                <td>
                                    <div class="pull-right">
                                        <a class="btn btn-default btn-sm"
                                            href="<?= $this->url('datoadicional/editar', ['action' => 'edit', 'id' => $dato_adicional->getId()]); ?>">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>
                                        <button name="<?= $dato_adicional->getId() ?>"
                                            id="<?= $dato_adicional->getId() ?>" type="button"
                                            class="btn btn-default btn-sm" data-toggle="modal"
                                            data-target="#datoAdicionalModal<?= $dato_adicional->getId() ?>">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </div>
                                </td>
                                <!-- Modal Dato Adicional -->
                                <div id="datoAdicionalModal<?= $dato_adicional->getId() ?>" class="modal fade"
                                    role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close"
                                                    data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Eliminar dato adicional</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    ¿Está seguro que desea eliminar el dato adicional:
                                                    "<?= $this->escapeHtml($dato_adicional->getDato_adicional()) ?>"
                                                    de forma permanente?
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="<?= $this->url('datoadicional/borrar', ['action' => 'delete', 'id' => $dato_adicional->getId()]); ?>"
                                                    type="button">
                                                    <span class="btn btn-default">Aceptar</span></a>

                                                <button type="button" class="btn btn-default"
                                                    data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <br>
                    <a href="<?= $this->url('datoadicional/agregar', ['action' => 'add', 'id' => $persona->getId()]); ?>"
                        type="button">
                        <span class="btn btn-default">
                            <span class="glyphicon glyphicon-plus"></span> Dato Adicional
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Registro de Eventos -->
<div class="container margen">
    <div class="container row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                REGISTRO DE EVENTOS
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseActividades" aria-expanded="true" aria-controls="collapseActividades">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-menu-hamburger btn-collapse" id="actividades"></i></span>
                </a>
            </div>
            <div class="panel-body padding-top-cero">
                <div class="collapse in" id="collapseActividades">
                    <div class="row padding-bot-md">
                        <!-- Transacciones -->
                        <div class="btn-group padding-md">
                            <button type="button" class="btn btn-default" style="font-weight: bold;"
                                onclick="mostrarTransacciones(<?= $id_persona ?>)">Transacciones</button>
                            <a role="button" class="btn btn-default" data-toggle="collapse" 
                                data-parent="#accordion" href="#drop" aria-expanded="true" aria-controls="drop">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </a>
                        </div>
                        <!-- Acción Comercial -->
                        <div class="btn-group padding-md">
                        <button role="button" class="btn btn-default" style="font-weight: bold;"
                                onclick="mostrarAccionesComerciales(<?= $id_persona ?>)">Acción Comercial</button>
                            <a href="<?= $this->url('evento', ['action' => 'add', 'tipo' => 'proveedor', 'id' => $persona->getId()]) ?>"
                                class="btn btn-default">
                                <span class="glyphicon glyphicon-plus" ></span>
                            </a>
                            <a role="button" id="eliminar_evento" class="btn btn-default" data-toggle="modal" data-target="#eventoModal">
                                <span class="glyphicon glyphicon-minus" ></span>
                            </a>
                        </div>
                        <!-- Cuenta Corriente -->
                        <div class="btn-group padding-md pull-right">
                            <button type="button" class="btn btn-default" style="font-weight: bold;"
                                onclick="mostrarCuentaCorriente(<?= $id_persona ?>)">Cuenta Corriente</button>
                        </div>
                    </div>

                    <!--Menu Transaccion-->
                    <div class="row padding-lg">
                        <div class="collapse" id="drop">
                            <ul class="list-inline padding-sm" style="margin-left: 20px;">
                                <li>
                                    <a href="<?= $this->url("presupuesto/agregar", ['id' => $persona->getId()]); ?>" class="transaccion-font" style="">
                                        <span class="glyphicon glyphicon-copy" ></span>&nbsp; Solicitud de Presupuesto
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->url("pedido/agregar", ['id' => $persona->getId()]); ?>"
                                    class="transaccion-font">
                                        <span class="glyphicon glyphicon-shopping-cart" ></span>&nbsp; Orden de Compra
                                    </a>
                                </li>
                                <li>
                                    <a  href="<?= $this->url("remito/agregar", ['id' => $persona->getId()]); ?>"class="transaccion-font">
                                        <span class="glyphicon glyphicon-check" ></span>&nbsp; Remito
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->url("factura/agregar", ['id' => $persona->getId()]); ?>" class="transaccion-font">
                                        <span class="glyphicon glyphicon-list-alt"></span>&nbsp; Factura
                                    </a>
                                </li>
                                <li>
                                <a href="<?= $this->url("cobro/agregar", ['id' => $persona->getId()]); ?>"
                                        class="transaccion-font">
                                        <span class="glyphicon glyphicon-credit-card"></span>&nbsp; Pago
                                    </a>
                                </li>
                            </ul>
                            <ul class="list-inline padding-sm" style="margin-left: 20px;">
                                <li>
                                    <a href="#" class="transaccion-font">
                                        <span class="glyphicon glyphicon-exclamation-sign" ></span>&nbsp; Devolución
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="transaccion-font">
                                        <span class="glyphicon glyphicon-tags" ></span>&nbsp; Nota de Crédito
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="transaccion-font">
                                        <span class="glyphicon glyphicon-tags" ></span>&nbsp; Nota de Débito
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="transaccion-font">
                                        <span class="glyphicon glyphicon-tags"></span>&nbsp; Nota de Crédito C/Pago
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div id="eventos">
                        <script>
                        mostrarAccionesComerciales(<?= $id_persona ?>);
                        </script>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Actividades -->

<!-- Modal Ciente -->
<div class="modal fade" id="exampleModal<?= $proveedor->getId() ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Eliminar cliente</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    ¿Está seguro que desea eliminar el proveedor:
                    "
                    <?= $this->escapeHtml($persona->getNombre()) ?>"
                    ?<br>
                    <?php
                    if ($persona->getEstado() == "S") {
                        echo ('Se establecerá como Inactivo.');
                    } else {
                        echo ('Se establecerá como Activo.');
                    }
                    ?>
                </p>
            </div>
            <div class="modal-footer">
                <a href="<?= $this->url('proveedores/modificarEstado', ['action' => 'modificarEstado', 'id' => (int)$proveedor->getId()]) ?>" type="button">
                    <span class="btn btn-default">Aceptar</span></a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Evento -->
<div class="modal fade" id="eventoModal" tabindex="-1" role="dialog" aria-labelledby="eventoModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="eventoModalLabel">Eliminar evento</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="eliminar_evento_1">¿Está seguro que desea eliminar las eventos seleccionados?</p>
                <p id="eliminar_evento_0" hidden>No hay evento/s seleccionados</p>
            </div>
            <div class="modal-footer">
                <button id="eliminar_evento_aceptar" class="btn btn-default" onclick="eliminaEventos()">Aceptar</button>
                <button id="eliminar_evento_cerrar" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <!-- Modificar Datos -->
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('proveedores/editar', ['tipo' => 'proveedor', 'id' => (int)$persona->getId()]) ?>" role="button">
                    <img src="<?= $this->basePath('img/crm/proveedor_update_v.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Modificar</label><br>
                <label>Datos</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a role="button" name="<?= $proveedor->getId() ?>" id="<?= $proveedor->getId() ?>" data-toggle="modal" data-target="#exampleModal<?= $proveedor->getId() ?>">
                    <img src="<?php
                                if ($persona->getEstado() == "S") {
                                    echo ($this->basePath('img/crm/proveedor_remove_v.png'));
                                } else {
                                    echo ($this->basePath('img/crm/proveedor_add_v.png'));
                                }
                                ?>" class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <?php
                if ($persona->getEstado() == "S") {
                    echo ('<label>Eliminar</label><br>'
                        . '<label>Proveedor</label>');
                } else {
                    echo ('<label>Agregar</label><br>'
                        . '<label>Proveedor</label>');
                }
                ?>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>   
                <a href="<?= $volver ?>" role="button">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-proveedor-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones --> 