<?= $this->doctype() ?>

<html lang="es">
    <head>

        <title>HUELLA CRM</title>
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/> 
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <!-- Le styles -->
        <?=
        $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/VetIcon.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/crm.css'))
        ?>

        <!-- Scripts -->
        <?=
        $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
        <script src="/js/functions.js"></script>
        <script src="/js/ajax.js"></script>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Custom functions file -->
        <script src="/js/sweetalert.js"></script>
        <!-- Sweet Alert Script -->
        <script src="/js/sweetalert.min.js"></script>
        <!-- Sweet Alert Styles -->
        <link href="/css/sweetalert.css" rel="stylesheet">

        
    </head>

    <article>

    <body class="homepage">
        
    <article>

        <!-- Navigation -->
        <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span> Acciones <i class="fa fa-bars"></i>
                    </button>
                    
                    <a class="navbar-brand page-scroll" data-toggle="collapse" data-parent="#accordion" 
                        href="#menu" aria-expanded="true" aria-controls="menu">Huella CRM
                    </a>

                </div>


                <div class="collapse pull-left" id="menu">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="hidden"><a href="#page-top"></a></li>
                        <li><a class="page-scroll" href="<?= $this->url('menu'); ?>"><small>Inicio</small></a></li>
                        <li><a class="page-scroll" href="<?= $this->url('gestionClientes'); ?>"><small>Clientes</small></a></li>
                        <li><a class="page-scroll" href="<?= $this->url('gestionProveedores'); ?>"><small>Proveedores</small></a></li>
                        <li><a class="page-scroll" href="<?= $this->url('gestionEmpresa'); ?>"><small>Empresa</small></a></li>
                        <li><a class="page-scroll" href="<?= $this->url('herramientas'); ?>"><small>Herramientas</small></a></li>
                    </ul>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="hidden"><a href="#page-top"></a></li>
                        <li><a class="page-scroll" href="<?= $this->url('menu'); ?>">Inicio</a></li>
                        <li><a class="page-scroll" href="<?= $this->url('gestionClientes'); ?>">Clientes</a></li>
                        <li><a class="page-scroll" href="<?= $this->url('gestionProveedores'); ?>">Proveedores</a></li>
                        <li><a class="page-scroll" href="<?= $this->url('gestionEmpresa'); ?>">Empresa</a></li>
                        <li><a class="page-scroll" href="<?= $this->url('herramientas'); ?>">Herramientas</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <main class="margen-main">
            <div id="content">
                <?= $this->content; ?>
            </div> 
        </main>

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-6 align-left">
                        <section>
                            <p><i class="fa fa-copyright" aria-hidden="true">Tandil - Provincia de Buenos Aires - Argentina</i></p>
                            <p><small><i class="copyright" aria-hidden="true">Coryright &copy; Software Huella 2019 - Todos los derechos reservados</i></small></p>
                        </section>
                    </div>
                </div>
            </div>
        </footer>

    </article>

    </body>
</html>
