<?= $this->doctype() ?>

<html lang="es">
    <head>

        <title>HUELLA CRM</title>
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/> 
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <!-- Le styles -->
        <?=
        $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/VetIcon.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/crm.css'))
        ?>

        <!-- Scripts -->
        <?=
        $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
        <script src="/js/functions.js"></script>
        <script src="/js/ajax.js"></script>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Custom functions file -->
        <script src="/js/sweetalert.js"></script>
        <!-- Sweet Alert Script -->
        <script src="/js/sweetalert.min.js"></script>
        <!-- Sweet Alert Styles -->
        <link href="/css/sweetalert.css" rel="stylesheet">

    </head>
    
</html>

<?= $this->content; ?>
