<?= $this->doctype() ?>

<html lang="es">
    <head>
        <title>HUELLA CRM</title>
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/> 
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <!-- Le styles -->
        <?=
        $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/VetIcon.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/crm.css'))
        ?>

        <!-- Scripts -->
        <?=
        $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
        <script src="/js/functions.js"></script>
        <script src="/js/ajax.js"></script>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Custom functions file -->
        <script src="/js/sweetalert.js"></script>
        <!-- Sweet Alert Script -->
        <script src="/js/sweetalert.min.js"></script>
        <!-- Sweet Alert Styles -->
        <link href="/css/sweetalert.css" rel="stylesheet">

    </head>
    
    <body class="homepage">
        <article>
            <!-- Header -->
            <div id="header" class="padding-sm">
                <div class="container" style="display: flex; align-items: flex-end;">

                    <div class="container pull-left">
                        <a href="<?= $this->url('home'); ?>"><img src= <?=$this->basePath("/img/crm/logo_huella_negocios.png")?> 
                            class="img-rounded img-responsive img-texto-derecha" style="width: 157px; height: 75px;"
                            ></a>
                    </div>
                    
                    <div class="container">
                        <p>
                            <a href="<?= $this->url('menu'); ?>">HOME</a>
                            .
                            <a href="<?= $this->url('gestionClientes'); ?>">CLIENTES</a>
                            .
                            <a href="<?= $this->url('gestionProveedores'); ?>">PROVEEDORES</a>
                            .
                            <a href="<?= $this->url('gestionEmpresa'); ?>">EMPRESA</a>
                            .
                            <a href="<?= $this->url('herramientas'); ?>">HERRAMIENTAS</a>
                        </p>
                    </div>


                    <div class="container">
                        <div class="col-md-4 pull-right">
                            Usuario: <label><?= $this->identity() ?></label>
                        </div>
                        <div class="col-md-4 pull-right">
                            Empresa: <label>**************</label>
                        </div>
                    </div>
                </div>
            </div>

            <main>
                <div id="content">
                    <?= $this->content; ?>
                </div> 
            </main>
    
            <!--Footer-->
            <div id="footer-layout" >
                <div class="container ">
                    <div class="row align-center">
                        <div class="col-xs-6 align-left">
                            <section>
                                <p><i class="fa fa-copyright" aria-hidden="true">Tandil - Provincia de Buenos Aires - Argentina</i></p>
                                <p><small><i class="fa fa-copyright" aria-hidden="true">Coryright Software Huella 2019 - Todos los derechos reservados</i></small></p>
                            </section>
                        </div>
                        <div class="col-xs-1">
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </body>
</html>
