<?= $this->doctype() ?>

<html lang="es">
    <head>
        <title>HUELLA CRM</title>
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/> 
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/VetIcon.png'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/crm.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
        <script src="/js/functions.js"></script>
        <script src="/js/ajax.js"></script>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Custom functions file -->
        <script src="/js/sweetalert.js"></script>
        <!-- Sweet Alert Script -->
        <script src="/js/sweetalert.min.js"></script>
        <!-- Sweet Alert Styles -->
        <link href="/css/sweetalert.css" rel="stylesheet">

    </head>
    <body class="homepage">

        <article>

            <!-- Header -->
            <div id="header" >
                <div class="container" >
                    <!-- Logo -->
                    <h2><a href="<?= $this->url('application', ['action' => 'index']); ?>" id="logo">Huella CRM</a></h2>
                    <span class="byline">Sistema de Administración de Clientes, Stock y Ventas </span>
                </div>
            </div>

            <main>
                <div id="content">
                    <!--Cuerpo-->
                    <?= $this->content; ?>
                </div> 
                
            </main>
            


            <!--inicio footer-->
            <div id="footer-layout" >
                <div class="container ">
                    <div class="row align-center">

                        <div class="col-xs-3"></div>
                        <div class="col-xs-2 align-right">
                            <img src="http://www.softhuella.com.ar/wp-content/uploads/logo-footer1.jpg" class="img-responsive footer-logo" alt="" width="100" height="80">
                        </div>
                        <div class="col-xs-6 align-left">
                            <section>
                                <p>
                                    <a href=""<?= $this->url('application', ['action' => 'index']); ?>">HOME</a>
                                    .
                                    <a href="<?= $this->url('clientes'); ?>">CLIENTES</a>
                                    .
                                    <a href="<?= $this->url('licencia', ['action' => 'index']); ?>">LICENCIAS</a>
                                    .
                                    <a href="<?= $this->url('ventas'); ?>">VENTAS</a>
                                    .
                                    <a href="<?= $this->url('gestion'); ?>">GESTION</a>
                                    .
                                    <a href="<?= $this->url('application', ['action' => 'backup']); ?>">BACKUP</a>
                                </p>
                                <p>
                                     <a>
                                    <span>Tandil - Provincia de Buenos Aires - Argentina</span>	 
                                </a>
                                </p>
                               
                            </section>
                        </div>
                        <div class="col-xs-1">
                        </div>
                    </div>
                </div>
            </div>
            <!--    </div>-->

            <!--fin footer-->

        </article>
    </body>
</html>
