<?= $this->doctype() ?>

<html lang="es">
    <head>
        <?php
        $this->headScript()->appendFile($this->basePath('js/jquery.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/jquery-2.2.4.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/bootstrap.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/jquery.dropotron.min.js', 'text/javascript'));
        $this->headLink()->appendStylesheet($this->basePath('css/style.css'));
        $this->headLink()->appendStylesheet($this->basePath('css/bootstrap-theme.min.css'));
        $this->headLink()->appendStylesheet($this->basePath('css/bootstrap.min.css'));
        $this->headLink()->appendStylesheet($this->basePath('css/crm.css'));
        echo ($this->headLink());
        echo ($this->headScript());
        ?>
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/> 
        <script src="/js/functions.js"></script>
        <script src="/js/ajax.js"></script>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Custom functions file -->
        <script src="/js/sweetalert.js"></script>
        <!-- Sweet Alert Script -->
        <script src="/js/sweetalert.min.js"></script>
        <!-- Sweet Alert Styles -->
        <link href="/css/sweetalert.css" rel="stylesheet">

    </head>
    <body class="homepage">
        <article>

            <main>
                <?= $this->content; ?>
            </main>
    
            <!--inicio footer-->
            <div id="footer-simple" >
                <div class="container ">
                    <div class="row align-center">                        
                        <div class="col-xs-6 align-left">
                            <section>
                                <p><i class="fa fa-copyright" aria-hidden="true">Tandil - Provincia de Buenos Aires - Argentina</i></p>
                                <p><small><i class="fa fa-copyright" aria-hidden="true">Coryright Software Huella 2019 - Todos los derechos reservados</i></small></p>
                            </section>
                        </div>
                        <div class="col-xs-1">
                        </div>
                    </div>
                </div>
            </div>
            <!--fin footer-->
        </article>
    </body>
</html>
