<?= $this->doctype() ?>

<html lang="es">
    <head>

        <?php
        $this->headScript()->appendFile($this->basePath('js/jquery.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/skel.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/jquery-2.2.4.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/skel-layers.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/init.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/bootstrap.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/jquery.dropotron.min.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/functions.js', 'text/javascript'));

        $this->headLink()->appendStylesheet($this->basePath('css/style.css'));
        $this->headLink()->appendStylesheet($this->basePath('css/skel.css'));
        $this->headLink()->appendStylesheet($this->basePath('css/bootstrap.min.css'));

        echo ($this->headLink());

        echo ($this->headScript());
        ?>
        <meta http-equiv="Content-Type" content="text/html" charset=utf-8"/> 
    </head>
    <body class="homepage">
<?= $this->content; ?>
    </body>
</html>
