<!-- scripts -->
<script src="/js/item.js"></script>

<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css"
    rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js">
</script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<link href="http://twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet">
<link href="css/bootstrap.icon-large.min.css" rel="stylesheet">


<script>
$(document).ready(function() {
    $('#tabla_ventas').DataTable({
        "order": [0, 'desc'],

        "language": {
            "url": "/json/spanish.json"
        }
    });

    $('#tabla_cobros').DataTable({
        "order": [0, 'desc'],

        "language": {
            "url": "/json/spanish.json"
        }
    });
});
// var idPersona = <?= $id_persona ?>;
</script>

<script type="text/javascript">
$(function() {
    $('#datetimepicker1').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker2').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker3').datetimepicker({
        format: 'DD/MM/YYYY'
    });
});
</script>
<!-- php -->

<!-- Document -->
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/clientes">Clientes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Cuenta Corriente</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<div class="container margen">

    <div class="row">
        <!-- * * * * * * * * * * * * * * * DATATABLE VENTAS * * * * * * * * * * * * * * * -->
        <div class="col-lg-6">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    VENTAS
                </div>
                <div class="panel-body">
                    <table id="tabla_ventas" class="display">
                        <thead>
                            <tr>
                                <th class="">Fecha</th>
                                <th class="">Tipo</th>
                                <th class="">Nro</th>
                                <th class="">Importe</th>
                            </tr>
                        </thead>
                        <tbody id="cuerpo_eventos" role="button" class="">
                            <?php foreach ($ventas as $venta) :
                                        $idTransaccion = $venta->getId();
                                        $tipoTransaccion = $venta->getTipoActividad();
                                        ?>
                            <tr id="<?= $venta->getId() ?>" class="vpEvento">
                                <!-- FECHA -->
                                <td id="<?= $venta->getId() ?>">
                                    <?php
                                                if (!is_null($venta->getFecha())) {
                                                    echo ($venta->getFecha()->format('Y/m/d'));
                                                }
                                                ?></td>
                                <!-- TIPO -->
                                <td id="<?= $venta->getId() ?>" class="">
                                    <?php
                                                if (!is_null($venta->getTipoActividad())) {
                                                    echo (ucfirst($venta->getTipoActividad()));
                                                } else {
                                                    echo ('No definido');
                                                }
                                                ?>
                                </td>
                                <!-- NRO -->
                                <td><?= str_pad($venta->getNroTipoTransaccion(), 4, "0", STR_PAD_LEFT) ?></td>
                                <!-- IMPORTE -->
                                <td><?= ("$ " . number_format($venta->getMonto(), 2, ",", ".")); ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- * * * * * * * * * * * * * * * DATATABLE COBROS * * * * * * * * * * * * * * * -->
        <div class="col-lg-6">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    COBROS
                </div>
                <div class="panel-body">
                    <table id="tabla_cobros" class="display">
                        <thead>
                            <tr>
                                <th class="">Fecha</th>
                                <th class="">Tipo</th>
                                <th class="">Nro</th>
                                <th class="">Importe</th>
                            </tr>
                        </thead>
                        <?php foreach ($cobros as $cobro) :
                                    $idTransaccion = $cobro->getId();
                                    $tipoTransaccion = $cobro->getTipoActividad();
                                    ?>
                        <tr id="<?= $cobro->getId() ?>" class="vpEvento">
                            <!-- FECHA -->
                            <td id="<?= $cobro->getId() ?>">
                                <?php
                                            if (!is_null($cobro->getFecha())) {
                                                echo ($cobro->getFecha()->format('Y/m/d'));
                                            }
                                            ?>
                            </td>
                            <!-- TIPO -->
                            <td id="<?= $cobro->getId() ?>" class="">
                                <?php
                                            if (!is_null($cobro->getTipoActividad())) {
                                                echo (ucfirst($cobro->getTipoActividad()));
                                            } else {
                                                echo ('No definido');
                                            }
                                            ?>
                            </td>
                            <!-- NRO -->
                            <td><?= str_pad($cobro->getNroTipoTransaccion(), 4, "0", STR_PAD_LEFT) ?></td>
                            <!-- IMPORTE -->
                            <td><?= ("$ " . number_format($cobro->getMonto(), 2, ",", ".")); ?></td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- * * * * * * * * * * * * * * * RESUMEN * * * * * * * * * * * * * * * -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading text-center titulo-espaciado">
                    RESUMEN
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- TOTAL VENTAS -->
        <div class="col-md-4">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-body">
                    <div class="row form-row">
                        <div class="form-group col-md-12">
                            <label>Total en Ventas</label>
                            <input type="text" class="form-control" name="" id="" value="" readonly>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-12">
                            <label>Total Facturado</label>
                            <input type="text" class="form-control" name="" id="" value="" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- TOTAL CC -->
        <div class="col-md-4">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-body">
                    <div class="row form-row">
                        <div class="form-group col-md-12">
                            <label>Saldo pendiente de Cobro</label>
                            <input type="text" class="form-control" name="" id="" value="" readonly>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-12">
                            <label>Pendiente a Facturar</label>
                            <input type="text" class="form-control" name="" id="" value="" readonly>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-12">
                            <label>Cuenta Corriente Global</label>
                            <input type="text" class="form-control" name="" id="" value="" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- TOTAL COBROS -->
        <div class="col-md-4">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-body">
                    <div class="row form-row">
                        <div class="form-group col-md-12">
                            <label>Total en Cobros</label>
                            <input type="text" class="form-control" name="" id="" value="" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
