<?php
$this->headTitle('Edit Ejecutivo');
$form->get('nombre')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Ingresar Nombre',
    'value' => $persona->getNombre()
]);
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'nombre@ejemplo.com',
    'value' => $persona->getEmail()
]);
$form->get('usuario')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Ingresar Usuario',
    'value' => $ejecutivo->getUsuario()
]);
$form->get('clave')->setAttributes([
    'class' => 'form-control',
    'value' => $ejecutivo->getClave()
    ]);
$form->get('submit')
        ->setAttributes(['class' => 'btn btn-info'])
        ->setValue('Guardar');
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                EDITAR EJECUTIVO
            </div>
            <div class="panel-body">
            <div class="form-row">
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('nombre')); ?>
                <?= $this->formElement($form->get('nombre')); ?>
                <?= $this->formElementErrors($form->get('nombre')); ?>
            </div>
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?> 
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('usuario')); ?>
                <?= $this->formElement($form->get('usuario')); ?>
                <?= $this->formElementErrors($form->get('usuario')); ?> 
            </div>
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('clave')); ?>
                <?= $this->formElement($form->get('clave')); ?>
                <?= $this->formElementErrors($form->get('clave')); ?> 
            </div>
        </div>
            </div>
        </div>
    </div>
</div>

<div class="container">   
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Editar ejecutivo</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea editar los datos de este ejecutivo?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>    
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->

<?= $this->form()->closeTag(); ?> 

