<?= $this->doctype();
if (isset($_SESSION['MENSAJES']['ejecutivo'])) {
    if ($_SESSION['MENSAJES']['ejecutivo']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['ejecutivo_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['ejecutivo_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['ejecutivo'] = null;
    $_SESSION['MENSAJES']['ejecutivo_msj'] = null;
}
?>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <script type="text/javascript" src="crm/ejecutivo.js"></script>
    </head>

    <!-- Inicio: Tabla Ejecutivos -->
    <div class="container margen">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading text-center">LISTADO EJECUTIVOS</div>

            </div>
            <!-- Datos de Usuarios Adicionales -->
            <div class="table-responsive">
                <table class="table table-hover table-striped" id="t-ejecutivos">
                    <thead>
                        <tr>
                            <th class="th-sm" onclick="sortTableString(1, 'tabla_evento')">
                                <i class="fa fa-sort float-right" aria-hidden="true"></i> Apellido
                            </th>
                            <th class="th-sm">Nombre</th>
                            <th class="th-sm">Email</th>
                            <th class="th-sm">Usuario</th>
                            <th class="th-sm"">Clave</th>
                            <th></th>     
                        </tr>
                    </thead>
                    <tbody> 
                        <?php
                        if (isset($ejecutivos)) {
                            foreach ($ejecutivos as $ejecutivo) {
                                echo ('<tr>');
                                echo ('<td>');
                                echo ($ejecutivo->getApellido());
                                echo ('</td>');
                                echo ('<td>');
                                echo ($ejecutivo->getNombre());
                                echo ('</td>');
                                echo ('<td>');
                                echo ($ejecutivo->getMail());
                                echo ('</td>');
                                echo ('<td>');
                                echo ($ejecutivo->getUsuario());
                                echo ('</td>');
                                echo ('<td>');
                                echo ($ejecutivo->getClave());
                                echo ('</td>');
                                ?>    
                            <td class="table-items-right">
                                <a class="btn btn-default" href="<?= $this->url('ejecutivos/editar', ['action' => 'edit', 'id' => $ejecutivo->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> 
                                </a>
                                <button name="<?= $ejecutivo->getId() ?>" id="<?= $ejecutivo->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $ejecutivo->getId() ?>">
                                    <span class="glyphicon glyphicon-remove" ></span
                                </button>
                            </td>
                            <!-- Modal -->
                            <div id="myModal<?= $ejecutivo->getId() ?>" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Eliminar ejecutivo</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>
                                                ¿Está seguro que desea desactivar el ejecutivo
                                                "<?= $this->escapeHtml($ejecutivo->getNombre()) ?>
                                                <?= $this->escapeHtml($ejecutivo->getApellido()) ?>"?
                                            </p>
                                        </div>
                                        <div class="modal-footer">
                                            <a class="btn btn-default" href="<?= $this->url('ejecutivos/borrar', ['action' => 'delete', 'id' => $ejecutivo->getId()]); ?>">
                                                Aceptar
                                            </a>
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </td>
                            <?php
                            echo ('</tr>');
                        }
                        ?>
                        </tbody>
                    </table>
                    <?php
                    echo $this->paginationControl($ejecutivos, 'Sliding', // All, Elastic, Jumping, Sliding
                            'search_pagination_ejecutivo.phtml', $this->url('ejecutivos/page', ['action' => 'index', 'id' => 1]));
                }
                ?>
            </div>
        </div>
    </div>
    <!-- Fin: Tabla Ejecutivos -->

    <!-- Inicio: Panel Botones -->
    <div class="container margen">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row img-centrar">
                        <div class="col ficha-cliente-p img-centrar">
                            <div>
                                <a href="<?= $this->url('ejecutivos/agregar'); ?>"><img src="<?= $this->basePath('img/crm/ActividadAgregar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                            </div>
                            <div class="ficha-cliente-label">
                                <label>Agregar</label><br>
                                <label>Ejecutivo</label>
                            </div>
                        </div>
                        <div class="col ficha-cliente-p img-centrar">
                            <div>
                                <a href='<?= $this->url("ejecutivos/inactivos") ?>'><img src="<?= $this->basePath('img/crm/ClienteEliminar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                            </div>
                            <div class="ficha-cliente-label">
                                <label>Ejecutivos</label><br>
                                <label>Inactivos</label>
                            </div>
                        </div>
                        <div class="col ficha-cliente-p img-centrar">
                            <div>
                                <a href="<?= $this->url('gestion') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                            </div>
                            <div class="ficha-cliente-label">
                                <label>Volver</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin: Panel Botones -->