<?= $this->doctype();
if (isset($_SESSION['MENSAJES']['ejecutivo'])) {
    if ($_SESSION['MENSAJES']['ejecutivo']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['ejecutivo_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['ejecutivo_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['ejecutivo'] = null;
    $_SESSION['MENSAJES']['ejecutivo_msj'] = null;
}
 ?>
 <div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('herramientas'); ?>">Herramientas</a></li>
            <li class="breadcrumb-item active" aria-current="page">Ejecutivos</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a  href="<?= $this->url('herramientas'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <script type="text/javascript" src="crm/ejecutivo.js"></script>
    </head>

    <!-- Inicio: Tabla Ejecutivos -->
    <div class="container margen">
        <div class="row">            
            <div class="panel panel-default sombra-ficha">
                <!-- Header -->
                <div class="panel-heading text-center titulo-espaciado">
                    LISTADO EJECUTIVOS
                    <a data-toggle="collapse" data-parent="#accordion" href="#add_ejecutivo" 
                        aria-expanded="true" aria-controls="add_ejecutivo">
                        <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                    </a>
                </div>
                <div class="panel panel-body">
                    <div class="container">
                         <div class="collapse" id="add_ejecutivo">
                            <form method="post">
                                <div class="row form-row">
                                    <div class="form-group form-inline">
                                        <input type="text" class="form-control ejecutivo-lg" name="nombre" placeholder="Nombre y Apellido" required="">
                                        <input type="text" class="form-control ejecutivo-lg" name="email" placeholder="Email" required="">
                                        <input type="text" class="form-control ejecutivo-md" name="usuario" placeholder="Usuario" required="">
                                        <input type="password" class="form-control ejecutivo-md" name="clave" placeholder="Clave" required="">
                                    </div>
                                </div>
                                <div class="row form-row">
                                     <div class="form-group">
                                        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                                            <span class="glyphicon glyphicon-plus" ></span> Agregar Ejecutivo
                                        </button>
                                     </div>
                                </div>
                                <!-- Modal -->
                                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="exampleModalLabel">Agregar ejecutivo</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>¿Está seguro que desea agregar este ejecutivo?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-default">Aceptar</button>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>     
                        </div>  
                    </div>
                    <!-- Tabla -->
                    <div class="table-responsive">
                        <table class="table table-hover table-striped" id="t-ejecutivos">
                            <thead>
                                <tr>
                                    <th class="th-sm">Ejecutivo</th>
                                    <th class="th-sm">Email</th>
                                    <th class="th-sm">Usuario</th>
                                    <th class="th-sm">Clave</th>
                                    <th></th>     
                                </tr>
                            </thead>
                            <tbody> 
                                <?php
                                if (isset($ejecutivos)) {
                                    foreach ($ejecutivos as $ejecutivo) {
                                        $persona = $ejecutivo->getPersona();
                                        echo ('<tr>');
                                        echo ('<td>');
                                        echo ($persona->getNombre());
                                        echo ('</td>');
                                        echo ('<td>');
                                        echo ($persona->getEmail());
                                        echo ('</td>');
                                        echo ('<td>');
                                        echo ($ejecutivo->getUsuario());
                                        echo ('</td>');
                                        echo ('<td>');
                                        echo ($ejecutivo->getClave());
                                        echo ('</td>');
                                        ?>    
                                    <td>
                                        <div class="pull-right">
                                            <a class="btn btn-default btn-sm" href="<?= $this->url('ejecutivos/editar', ['action' => 'edit', 'id' => $ejecutivo->getId()]); ?>">
                                                <span class="glyphicon glyphicon-pencil" ></span> 
                                            </a>
                                            <button name="<?= $ejecutivo->getId() ?>" id="<?= $ejecutivo->getId() ?>" type="button" class="btn btn-default btn-sm" 
                                                data-toggle="modal" data-target="#myModal<?= $ejecutivo->getId() ?>">
                                                <span class="glyphicon glyphicon-trash" ></span>
                                            </button>
                                        </div>
                                    </td>
                                    <!-- Modal -->
                                    <div id="myModal<?= $ejecutivo->getId() ?>" class="modal fade" role="dialog">
                                        <div class="modal-dialog">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Eliminar ejecutivo</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        ¿Está seguro que desea desactivar el ejecutivo
                                                        "<?= $this->escapeHtml($persona->getNombre()) ?>"?
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="<?= $this->url('ejecutivos/borrar', ['action' => 'delete', 'id' => $ejecutivo->getId()]); ?>" type="button">
                                                    <span class="btn btn-default">Aceptar</span></a>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </td>
                                    <?php
                                    echo ('</tr>');
                                }
                                ?>
                            </tbody>
                        </table>
                        
                    </div>
                </div>
            </div>
            <?php
                echo $this->paginationControl($ejecutivos, 'Sliding', // All, Elastic, Jumping, Sliding
                        'search_pagination_ejecutivo.phtml', $this->url('ejecutivos/page', ['action' => 'index', 'id' => 1]));
            }
            ?>
            
        </div>
    </div>
    <!-- Fin: Tabla Ejecutivos -->

    <!-- Inicio: Panel Botones -->
    <div class="container margen">
        <div class="row img-centrar">
            <div class="col ficha-cliente-p img-centrar">
                <div>
                <a href="<?= $this->url('ejecutivos/inactivos'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                        class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                    </a>
                </div>
                <div class="ficha-cliente-label">
                    <label>Inactivos</label>
                </div>
            </div>
            <div class="col ficha-cliente-p img-centrar">
                <div>
                    <a href="<?= $volver ?>">
                        <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" 
                        class="img-rounded img-responsive img-texto-derecha zoom">
                    </a>
                </div>
                <div class="ficha-cliente-label">
                    <label>Volver</label>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin: Panel Botones -->