<?php
$this->headTitle('Editar Categoria');

$form->get('nombre')->setAttributes([
    'class' => 'form-control'
]);

$form->prepare();
?>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">EDITAR CATEGORÍA</div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>
                   <div class="form-group">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <?= $this->formElement($form->get('nombre')); ?>
                        <?= $this->formElementErrors($form->get('nombre')); ?>                  
                    </div>
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="submit" class="btn btn-default">Cancelar</button>
                    <?= $this->form()->closeTag(); ?>
                </div>    
            </div>   
        </div>
    </div>
</div>
    

