<script src="js/functions.js"></script>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">Listado de categorías</div>
        </div>
    </div>
</div>
<div class="container">
    <form method="post">
        <div class="row form-row">
            <div class="form-group col-md-4">
                <input type="text" class="form-control" name="nombre" placeholder="Ingresar Categoría">
            </div>
            <div class="form-group col-md-4">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                    <span class="glyphicon glyphicon-plus" ></span> Agregar Categoría
                </button>
            </div>
        </div>
        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Agregar categoría</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Está seguro que desea agregar esta categoría?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default">Aceptar</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="tabla_categoriacliente" class="table table-bordred table-striped">
                    <thead>
                        <tr>
                            <th class="th-sm" onclick="sortTableString(1, 'tabla_categoriacliente')">Categoría
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if (isset($categorias_pag)) {
                            foreach ($categorias_pag as $categoriacliente) :
                                ?>
                                <tr>
                                    <td><?php echo ($categoriacliente->getNombre()); ?></td>
                                    <td class="table-items-right">
                                        <a class="btn btn-default" href="<?= $this->url('categoriacliente/editar', ['action' => 'edit', 'id' => $categoriacliente->getId()]); ?>">
                                            <span class="glyphicon glyphicon-pencil" ></span> 
                                        </a>
                                        <button name="<?= $categoriacliente->getId() ?>" id="<?= $categoriacliente->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $categoriacliente->getId() ?>">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>
                                    </td>
                                    <!-- Modal -->
                            <div id="myModal<?= $categoriacliente->getId() ?>" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Borrar cliente</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>
                                                ¿Está seguro que desea eliminar la categoría: 
                                                "<?= $this->escapeHtml($categoriacliente->getNombre()) ?>"?
                                            </p>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="<?= $this->url('categoriacliente/borrar', ['action' => 'remove', 'id' => $categoriacliente->getId()]); ?>" class="btn btn-default">
                                                Aceptar
                                            </a>
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php
                    echo $this->paginationControl($categorias_pag, 'Sliding', // All, Elastic, Jumping, Sliding
                            'search_pagination_cat.phtml', $this->url('categoriacliente/page', ['action' => 'index', 'id' => 1]));
                }
                ?>
            </div>
        </div>  
    </div>
</div>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('gestion') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->