<?php
if (isset($_SESSION['MENSAJES']['categoria_cliente'])) {
    if ($_SESSION['MENSAJES']['categoria_cliente']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['categoria_cliente_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['categoria_cliente_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['categoria_cliente'] = null;
    $_SESSION['MENSAJES']['categoria_cliente_msj'] = null;
}
?>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Categoria -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO CATEGORÍAS
                <a data-toggle="collapse" data-parent="#accordion" href="#add_categoria" 
                aria-expanded="true" aria-controls="add_categoria">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
        <div class="panel panel-body">
            <div class="collapse" id="add_categoria">
                <form method="post">
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control form-margen" name="nombre" placeholder="Ingresar Categoría">
                        </div>
                        <div class="form-group col-md-4">
                            <button type="button" class="btn btn-default form-margen" data-toggle="modal" data-target="#myModal">
                                <span class="glyphicon glyphicon-plus" ></span> Agregar Categoría
                            </button>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div id="myModalAdd" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Agregar categoría</h4>
                                </div>
                                <div class="modal-body">
                                    <p>¿Está seguro que desea agregar esta categoría?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-default">Aceptar</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tabla_categoriacliente" class="table table-bordred table-striped">
                            <thead>
                                <tr>
                                    <th class="th-sm" onclick="sortTableString(1, 'tabla_categoriacliente')">Categoría
                                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($categorias_pag)) {
                                    foreach ($categorias_pag as $categoriacliente) :
                                        ?>
                                        <tr>
                                            <td><?php echo ($categoriacliente->getNombre()); ?></td>
                                            <td class="table-items-right">
                                                <a class="btn btn-default" href="<?= $this->url('categoriacliente/editar', ['action' => 'edit', 'id' => $categoriacliente->getId()]); ?>">
                                                    <span class="glyphicon glyphicon-pencil" ></span> 
                                                </a>
                                                <button name="<?= $categoriacliente->getId() ?>" id="<?= $categoriacliente->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $categoriacliente->getId() ?>">
                                                    <span class="glyphicon glyphicon-remove" ></span>
                                                </button>
                                            </td>
                                            <!-- Modal -->
                                            <div id="myModal<?= $categoriacliente->getId() ?>" class="modal fade" role="dialog">
                                                <div class="modal-dialog">
                                                    <!-- Modal content-->
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                            <h4 class="modal-title">Borrar cliente</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <p>
                                                                ¿Está seguro que desea eliminar la categoría: 
                                                                "<?= $this->escapeHtml($categoriacliente->getNombre()) ?>"?
                                                            </p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <a href="<?= $this->url('categoriacliente/borrar', ['action' => 'remove', 'id' => $categoriacliente->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                                                            <span class="btn btn-default">Aceptar</span></a>
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>  
                </div>
            </div>
        </div>                            
    </div>
    <?php
        echo $this->paginationControl($categorias_pag, 'Sliding', // All, Elastic, Jumping, Sliding
                'search_pagination_cat.phtml', $this->url('categoriacliente/page', ['action' => 'index', 'id' => 1]));
    }
    ?>
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionClientes') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->