<!-- scripts -->
<script src="/js/bienes-transacciones.js"></script>
<script src="/js/item.js"></script>



<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css"
    rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

<script>
$(function() {
    $('#datetimepicker1').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker2').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker3').datetimepicker({
        format: 'DD/MM/YYYY'
    });
});
</script>

<!-- Script --> <!-- PROBLEMAS CON EL DATETIMEPICKER -- JQUERY TIENE QUE SER MENOR A 2.2 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- jQuery UI -->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<link href="css/bootstrap.icon-large.min.css" rel="stylesheet">
<!-- <link href="http://twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet"> -->

<script>
$(document).ready(function() {
    $('#table_bienes').DataTable({
        "order": [0, 'desc'],

        "language": {
            "url": "/json/spanish.json"
        }
    });
});
</script>

<!-- php -->
<?php
$date = date('d-m-Y');
$url = "/clientes/listado/ficha/" . $persona->getId();
$responsable = $this->identity();

var_dump(json_decode($json_bienes, true));

?>

<!-- json desde el controller, necesito otro con todos los bienes (nombre + valor) -->
<script>
    
    var json_items = <?= $json_bienes ?>;

    // data2 = [{"value":"2","label":"Sonarika"},{"value":"7","label":"Rahul singh"},{"value":"8","label":"Shreya"},{"value":"10","label":"Rohit singh"},{"value":"19","label":"Gaurav"}];

</script>

<style>

* {
    box-sizing: border-box;
}


/*the container must be positioned relative:*/
.autocomplete {
    position: relative;
    display: inline-block;
}

.autocomplete-items {
    position: absolute;
    border: 1px solid #d4d4d4;
    border-bottom: none;
    border-top: none;
    z-index: 99;
    /*position the autocomplete items to be the same width as the container:*/
    top: 100%;
    left: 0;
    right: 0;
}

.autocomplete-items div {
    padding: 10px;
    cursor: pointer;
    background-color: #fff;
    border-bottom: 1px solid #d4d4d4;
}

/*when hovering an item:*/
.autocomplete-items div:hover {
    background-color: #e9e9e9;
}

/*when navigating through the items using the arrow keys:*/
.autocomplete-active {
    background-color: DodgerBlue !important;
    color: #ffffff;
}
</style>


<!-- Document -->
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/clientes">Clientes</a></li>
            <li class="breadcrumb-item"><a href="/clientes/listado">Listado</a></li>
            <li class="breadcrumb-item"><a href="<?= $url ?>">Ficha</a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar Pedido</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<form method="post">
    <div class="container margen">
        <!-- Datos de Pedido -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    PEDIDO
                </div>
                <div class="panel-body">
                    <!-- Fecha + Datos de Persona -->
                    <div class="row form-row">
                        <div class="form-group col-md-2">
                            <label>Fecha de Venta</label>
                            <div class='input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" name="fecha_transaccion" value="<?= $date ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Cliente</label>
                            <input type="text" class="form-control" name="persona" id="persona"
                                value="<?= $persona->getNombre() ?>" readonly>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Razón Social</label>
                            <div class="form-inline">
                                <input type="text" class="form-control" name="razon_social" id="razon_social"
                                    value="<?php if (!is_null($tipoPersona)) {
                                    echo ($tipoPersona->getRazon_social());
                                } ?>" style="width: 60%; min-width: 300px;" readonly>
                                <button type="button" class="btn btn-default">Consumidor Final</button>
                            </div>
                        </div>
                    </div>
                    <!-- Datos de Transaccion -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Número de Transacción</label>
                            <input type="text" class="form-control" name="numero_transaccion" id="numero_transaccion"
                                value="<?= $numTransacciones ?>" readonly style="max-width: 250px;">
                        </div>
                        <div class="form-group col-md-3">
                            <label>Número de Pedido</label>
                            <input type="text" class="form-control" name="numero_pedido" id="numero_pedido"
                                value="<?= $numPedido ?>" style="max-width: 250px;">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Número de Presupuesto</label>
                            <div class="form-inline">
                                <input type="text" class="form-control" name="numero_presupuesto"
                                    id="numero_presupuesto" value="" readonly>
                                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search">
                                    </span> Buscar</button>
                            </div>
                        </div>
                        <input type="hidden" id="responsable" name="responsable" value=<?= $responsable ?>>
                        <input type="hidden" id="url" name="url" value=<?= $url ?>>
                    </div>
                </div>
            </div>
        </div>
        <!-- Listado de Items -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    LISTADO DE PRODUCTOS & SERVICIOS
                </div>

                <!-- Autocompletado -->
                
                <div class="container" style="padding-top:10px;">
                    <form method="post" autocomplete="off">
                        <div class="autocomplete form-group form-inline">
                            <input type="text" class="form-control" name="myCountry" id="myInput" placeholder="Código">
                            <input type="text" class="form-control" name="myCountry" id="myInput2" placeholder="Producto & Servicio">

                            <input type="text" class="form-control" name="descripcion" id="descripcion" 
                                placeholder="Descripción" style="width: 310px;">
                            <input type="number" class="form-control" name="cantidad" id="cantidad" min="1" max="99" value="" placeholder="Cantidad"
                                    onkeypress="return justNumbers(event)" onclick="calculaSubtotal()" onkeyup="calculaSubtotal()"
                                    style="width: 110px;">
                        </div>
                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Agregar</button>
                    </form>
                </div>

                <!-- ************************************************************************** -->
                <script>
                    
                function autocompleteW3S(inp, arr) {
                    /*the autocomplete function takes two arguments,
                    the text field element and an array of possible autocompleted values:*/
                    var currentFocus;
                    /*execute a function when someone writes in the text field:*/
                    inp.addEventListener("input", function(e) {
                        var a, b, i, val = this.value;
                        /*close any already open lists of autocompleted values*/
                        closeAllLists();
                        if (!val) {
                            return false;
                        }
                        currentFocus = -1;

                        /*create a DIV element that will contain the items (values):*/
                        a = document.createElement("DIV");
                        a.setAttribute("id", this.id + "autocomplete-list");
                        a.setAttribute("class", "autocomplete-items");
                        /*append the DIV element as a child of the autocomplete container:*/
                        this.parentNode.appendChild(a);
                        
                        /*for each item in the array...*/
                        for (i = 0; i < arr.length; i++) {
                            /*check if the item starts with the same letters as the text field value:*/

                            if (arr[i]["label"].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                                /*create a DIV element for each matching element:*/
                                b = document.createElement("DIV");
                                /*make the matching letters bold:*/
                                b.innerHTML = "<strong>" + arr[i]["label"].substr(0, val.length) + "</strong>";
                                b.innerHTML += arr[i]["label"].substr(val.length);
                                /*insert a input field that will hold the current array item's value:*/
                                b.innerHTML += "<input type='hidden' value='" + arr[i]["label"] + "'>";
                                /*execute a function when someone clicks on the item value (DIV element):*/
                                b.addEventListener("click", function(e) {
                                    /*insert the value for the autocomplete text field:*/
                                    inp.value = this.getElementsByTagName("input")[0].value;
                                    /*close the list of autocompleted values,
                                    (or any other open lists of autocompleted values:*/
                                    closeAllLists();
                                });
                                a.appendChild(b);
                            }
                        }
                    });

                    /*execute a function presses a key on the keyboard:*/
                    inp.addEventListener("keydown", function(e) {
                        var x = document.getElementById(this.id + "autocomplete-list");
                        if (x) x = x.getElementsByTagName("div");
                        if (e.keyCode == 40) {
                            /*If the arrow DOWN key is pressed,
                            increase the currentFocus variable:*/
                            currentFocus++;
                            /*and and make the current item more visible:*/
                            addActive(x);
                        } else if (e.keyCode == 38) { //up
                            /*If the arrow UP key is pressed,
                            decrease the currentFocus variable:*/
                            currentFocus--;
                            /*and and make the current item more visible:*/
                            addActive(x);
                        } else if (e.keyCode == 13) {
                            /*If the ENTER key is pressed, prevent the form from being submitted,*/
                            e.preventDefault();
                            if (currentFocus > -1) {
                                /*and simulate a click on the "active" item:*/
                                if (x) x[currentFocus].click();
                            }
                        }
                    });

                    function addActive(x) {
                        /*a function to classify an item as "active":*/
                        if (!x) return false;
                        /*start by removing the "active" class on all items:*/
                        removeActive(x);
                        if (currentFocus >= x.length) currentFocus = 0;
                        if (currentFocus < 0) currentFocus = (x.length - 1);
                        /*add class "autocomplete-active":*/
                        x[currentFocus].classList.add("autocomplete-active");
                    }

                    function removeActive(x) {
                        /*a function to remove the "active" class from all autocomplete items:*/
                        for (var i = 0; i < x.length; i++) {
                            x[i].classList.remove("autocomplete-active");
                        }
                    }

                    function closeAllLists(elmnt) {
                        /*close all autocomplete lists in the document,
                        except the one passed as an argument:*/
                        var x = document.getElementsByClassName("autocomplete-items");
                        for (var i = 0; i < x.length; i++) {
                            if (elmnt != x[i] && elmnt != inp) {
                                x[i].parentNode.removeChild(x[i]);
                            }
                        }
                    }
                    /*execute a function when someone clicks in the document:*/
                    document.addEventListener("click", function(e) {
                        elementId = e.target.id;
                        $("#myInput").autocomplete({
                        // Obtengo data (data deberia ser data = total_bienes (con nombre y id))
                        source: function(request, response ) {
                            data = json_items;
                            response(data);
                        },
                        // Completo los input, y retorno el id
                        select: function (event, ui) {
                            $('#myInput').val(ui.item.label); // display the selected text
                            $('#descripcion').val(ui.item.value); // save selected id to input
                            return false;
                        }
                    });


                        closeAllLists(e.target);
                    });
                }

                /*An array containing all the country names in the world:*/
                // var codigos = ["SH100", "CH444", "NV999", "SS200"];
                // var nombres = ["Shampoo", "Ccocolate", "Novillo", "Soporte de Sistemas"];

                /*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
                autocompleteW3S(document.getElementById("myInput"), json_items);
                autocompleteW3S(document.getElementById("myInput2"), json_items);

                
                </script>
                <!-- ************************************************************************************** -->
                <!-- Tabla de Items -->

                <div class="panel panel-body" id="contenido_bienes">
                    <script>
                    var obj = <?php echo ($json); ?>;
                    var idPersona = <?php echo ($persona->getId()); ?>;
                    addItems(obj, "pedido", idPersona);
                    </script>
                    <br>
                    <a href="<?= $this->url('bienes', ['action' => 'index', 'transaccion' => 'pedido', 'accion' => 'agregar', 'id' => $persona->getId()]); ?>"
                        type="button">
                        <span class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Agregar Item</span>
                    </a>
                </div>
            </div>
        </div>

        <!-- Datos -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    DATOS ECONÓMICOS
                </div>
                <div class="panel-body">
                    <!-- Totales -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Descuento Total ($)</label>
                            <input type="text" class="form-control" name="descuento_total" id="descuento_total" value=0
                                readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>IVA Total ($)</label>
                            <input type="text" class="form-control" name="iva_total" id="iva_total" value=0 readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Subtotal</label>
                            <input type="text" class="form-control" name="subtotal_general" id="subtotal_general"
                                value=0 readonly>
                        </div>
                    </div>
                    <!-- Forma de Pago + Fecha -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Moneda</label>
                            <select class="form-control" id="moneda" name="moneda">
                                <option value="" hidden="">Seleccionar Moneda</option>
                                <option value="-1">NO DEFINIDO</option>
                                <?php foreach ($categorias as $categoria) : ?>
                                <option value="<?= $categoria->getId(); ?>">
                                    <?= $categoria->getNombre(); ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Forma de Pago</label>
                            <select class="form-control" id="forma_pago" name="forma_pago">
                                <option value="-1" hidden="">Seleccionar Forma de Pago</option>
                                <option value="1">Contado</option>
                                <option value="2">Tarjeta</option>
                                <?php foreach ($categorias as $categoria) : ?>
                                <option value="<?= $categoria->getId(); ?>">
                                    <?= $categoria->getNombre(); ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div id="div_bonificacion" class="form-group col-md-2">
                            <label>% Bonificación</label>
                            <input type="text" class="form-control" name="bonificacion_general"
                                id="bonificacion_general" value="0.00" onkeypress="return justNumbers(event);"
                                onkeyup="calcularSubcampos()">
                        </div>
                        <div id="div_recargo" class="form-group col-md-2">
                            <label>% Recargo</label>
                            <input type="text" class="form-control" name="recargo_general" id="recargo_general"
                                value="0.00" onkeypress="return justNumbers(event);" onkeyup="calcularSubcampos()">
                        </div>
                    </div>
                    <!-- Total -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Total</label>
                            <input type="text" class="form-control" name="total_general" id="total_general" value=0
                                readonly>
                        </div>
                        <div class="form-group col-md-2">
                            <label>Fecha de Vencimiento</label>
                            <div class='input-group date' id='datetimepicker2'>
                                <input type='text' class="form-control" name="fecha_transaccion" value="<?= $date ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script>
                    calcularSubcampos();
                    </script>
                </div>
            </div>
        </div>

        <!-- Datos -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    DATOS DE ENVÍO
                </div>
                <div class="panel-body">
                    <!-- Entrega y Factura al Momento -->
                    <div class="row form-row">
                        <div class="form-check col-md-4">
                            <input type="checkbox" value="" id="EntregaDomicilioFacturacion"
                                name="EntregaDomicilioFacturacion" data-toggle="collapse" data-parent="#accordion"
                                data-target="#collapseEntregaDomicilioFacturacion" aria-expanded="true"
                                aria-controls="collapseEntregaDomicilioFacturacion">
                            <label class="form-check-label" for="EntregaDomicilioFacturacion">Entrega en Domicilio de
                                Facturación</label>
                        </div>
                        <div class="form-check col-md-4">
                            <input type="checkbox" class="form-check-input" name="entrega_momento" id="entrega_momento">
                            <label class="form-check-label" for="entrega_momento">Entrega al momento de la Venta</label>
                        </div>
                        <div class="form-check col-md-4">
                            <input type="checkbox" class="form-check-input" name="factura_momento" id="factura_momento">
                            <label class="form-check-label" for="factura_momento">Factura al momento de la Venta</label>
                        </div>
                    </div>
                    <!-- Forma de Pago + Fecha -->
                    <div class="row form-row">
                        <div class="form-group col-md-12">

                            <div class="row form-row collapse" id="collapseEntregaDomicilioFacturacion">
                                <br>
                                <div class="form-group col-md-3">
                                    <label>Fecha de Entrega</label>
                                    <div class='input-group date' id='datetimepicker3'>
                                        <input type='text' class="form-control" name="fecha_entrega"
                                            value="<?= $date ?>" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group col-md-3">
                                    <label>Forma de Envío</label>
                                    <select class="form-control" id="forma_envio" name="forma_envio">
                                        <option value="" hidden="">Seleccionar Forma de Envío</option>
                                        <option value="-1">NO DEFINIDO</option>
                                        <?php foreach ($categorias as $categoria) : ?>
                                        <option value="<?= $categoria->getId(); ?>">
                                            <?= $categoria->getNombre(); ?>
                                        </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar pedido</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea agregar este pedido?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>

</form>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $url ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->

<div class="container">
<br><br><br><br><br><br><br><br>

<!-- TABLA DE INPUTS -->
<table>
  <tr>
    <td>Single selection</td>
    <td><input type='text' id='autocomplete' ></td>
  </tr>

  <tr>
    <td>Selected User id</td>
    <td><input type='text' id='selectuser_id' /></td>
  </tr>

</table>

<script>

$( function() {

// AUTOCOMPLETE: al ingresar un caracter tiene que devolver un json con los posibles valores.
// $response[] = array("value"=>"..","label"=>"..");

// Single Select
$( "#autocomplete" ).autocomplete({
    // Obtengo data (data deberia ser data = total_bienes (con nombre y id))
    source: function(request, response ) {
        data = json_items;
        response(data);
    },
    // Completo los input, y retorno el id
    select: function (event, ui) {
        $('#autocomplete').val(ui.item.label); // display the selected text
        $('#selectuser_id').val(ui.item.value); // save selected id to input
        return false;
    }
});


// Single Select con AJAX
// $( "#autocomplete" ).autocomplete({
//   source: function( request, response ) {
//    $.ajax({
//             "dataType": "text",
//             "type": "POST",
//             "data": "temp",
//             "url": '/pedido/ajax/autocompletar/',

//             "success": function (msg) {
//                 data = json_items;
//                 response(data);
//             },
            
//             "error": function (msg) {
//                 console.log("1-error!");
//             }

//         }).done(function (msg) {
//             console.log("1-done!");
//         })
//   },
//   select: function (event, ui) {
//    // Set selection
//    $('#autocomplete').val(ui.item.label); // display the selected text
//    $('#selectuser_id').val(ui.item.value); // save selected id to input
//    return false;
//   }
//  });


});

function split( val ) {
  return val.split( /,\s*/ );
}

function extractLast( term ) {
  return split( term ).pop();
}

</script>

</div>

