<!-- scripts -->
<script src="/js/bienes-transacciones.js"></script>
<script src="/js/item.js"></script>
<script src="/js/opciones-transacciones.js"></script>
<script language="javascript" src="https://momentjs.com/downloads/moment.js"></script>
<script language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js">
</script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">
<script type="text/javascript">
$(function() {
    $('#datetimepicker1').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker2').datetimepicker({
        format: 'DD/MM/YYYY'
    });
    $('#datetimepicker3').datetimepicker({
        format: 'DD/MM/YYYY'
    });
});
</script>
<!-- Script --> <!-- PROBLEMAS CON EL DATETIMEPICKER -- JQUERY TIENE QUE SER MENOR A 2.2 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- jQuery UI -->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<link href="css/bootstrap.icon-large.min.css" rel="stylesheet">
<!-- <link href="http://twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet"> -->

<script>
$(document).ready(function() {
    $('#table_bienes').DataTable({
        "order": [0, 'desc'],

        "language": {
            "url": "/json/spanish.json"
        }
    });
});
</script>

<!-- php -->
<?php
$date = date('d-m-Y');
$url = "/clientes/listado/ficha/" . $persona->getId();
$responsable = $this->identity();
?>

<!-- json desde el controller, necesito otro con todos los bienes (nombre + valor) -->
<script>
    var json_items = <?= $json_bienes ?>;
    var output;
</script>

<!-- Document -->
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/clientes">Clientes</a></li>
            <li class="breadcrumb-item"><a href="/clientes/listado">Listado</a></li>
            <li class="breadcrumb-item"><a href="<?= $url ?>">Ficha</a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar Pedido</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<form method="post">
    <div class="container margen">
        <!-- Datos de Pedido -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    PEDIDO
                </div>
                <div class="panel-body">
                    <!-- Fecha + Datos de Persona -->
                    <div class="row form-row">
                        <div class="form-group col-md-2">
                            <label>Fecha de Venta</label>
                            <div class='input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" name="fecha_transaccion" value="<?= $date ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <label>Cliente</label>
                            <input type="text" class="form-control" name="persona" id="persona"
                                value="<?= $persona->getNombre() ?>" readonly>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Razón Social</label>
                            <div class="form-inline">
                                <input type="text" class="form-control" name="razon_social" id="razon_social"
                                    value="<?php if (!is_null($tipoPersona)) {
                                    echo ($tipoPersona->getRazon_social());
                                } ?>" style="width: 60%; min-width: 300px;" readonly>
                                <button type="button" class="btn btn-default">Consumidor Final</button>
                            </div>
                        </div>
                    </div>
                    <!-- Datos de Transaccion -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Número de Transacción</label>
                            <input type="text" class="form-control" name="numero_transaccion" id="numero_transaccion"
                                value="<?= $numTransacciones ?>" readonly style="max-width: 250px;">
                        </div>
                        <div class="form-group col-md-3">
                            <label>Número de Pedido</label>
                            <input type="text" class="form-control" name="numero_pedido" id="numero_pedido"
                                value="<?= $numPedido ?>" style="max-width: 250px;">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Número de Presupuesto</label>
                            <div class="form-inline">
                                <input type="text" class="form-control" name="numero_presupuesto"
                                    id="numero_presupuesto" value="" readonly>
                                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search">
                                    </span> Buscar</button>
                            </div>
                        </div>
                        <input type="hidden" id="responsable" name="responsable" value="<?= $responsable ?>">
                        <input type="hidden" id="url" name="url" value="<?= $url ?>">
                    </div>
                </div>
            </div>
        </div>
        <!-- Listado de Items -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    LISTADO DE PRODUCTOS Y SERVICIOS
                </div>

                <!-- Form Autocompletado -->
                <div class="container" style="padding-top:10px;">
                    <form method="post" autocomplete="off">
                        
                        <input type="hidden" class="form-control" name="item_id" id="item_id">
                        
                        <div class="autocomplete form-group col-sm-2 margin-padding-xs">
                            <label>Código</label>
                            <input type="text" class="form-control" name="item_codigo" id="item_codigo" placeholder="Código">
                        </div>
                        <div class="autocomplete form-group col-sm-2 margin-padding-xs">
                            <label>Producto Y Servicio</label>
                            <input type="text" class="form-control" name="item_nombre" id="item_nombre" placeholder="Producto Y Servicio">
                        </div>
                        <div class="form-group col-sm-2 margin-padding-xs">
                            <label>Stock Disponible</label>
                            <input type="text" class="form-control" name="item_stock" id="item_stock" placeholder="Stock Disponible">
                        </div>
                        <div class="form-group col-sm-2 margin-padding-xs">
                            <label>Cantidad</label>
                            <input type="number" class="form-control" name="cantidad" id="cantidad" min="1" max="99" value="" placeholder="Cantidad"
                                onkeypress="return justNumbers(event)" onclick="calculaSubtotal()" onkeyup="calculaSubtotal()"
                                >
                        </div>
                        <div class="form-group col-sm-1 margin-padding-xs">
                            <label>&nbsp;</label>
                            <button type="button" class="btn btn-default" onclick="addItemToTable()">
                                <span class="glyphicon glyphicon-plus"></span> Agregar
                            </button>
                        </div>   
                </div>
                <!-- Detalles de Producto Y Servicio -->
                <div class="container" style="">
                    <label>
                        <input type="checkbox" value="" data-toggle="collapse" data-parent="#accordion"
                            data-target="#collapseDetalles" aria-expanded="true"
                            aria-controls="collapseDetalles" name="Detalles" id="Detalles">
                        Mostrar Detalles
                    </label>
                    <div class="container row collapse" id="collapseDetalles">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Descripción</th>
                                    <th>Categoría</th>
                                    <th>Precio</th>
                                    <th>% Descuento</th>
                                    <th>Precio c/Dto.</th>
                                    <th>% IVA</th>
                                    <th>Precio c/IVA</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td id="item_descripcion"></td>
                                    <td id="item_categoria"></td>
                                    <td id="item_precio"></td>
                                    <td id="item_descuento"></td>
                                    <td id="item_descuento_precio"></td>
                                    <td id="item_iva"></td>
                                    <td id="item_iva_precio"></td>
                                    <td id="item_subtotal"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <script src="/js/autocomplete.js"></script>
               
                <!-- Tabla de Items -->
                <div class="panel panel-body" id="contenido_bienes">
                    <script>
                    var obj = <?php echo ($json); ?>;
                    var idPersona = <?php echo ($persona->getId()); ?>;
                    addItems(obj, "pedido", idPersona);
                    </script>
                    <br>
                    <a href="<?= $this->url('bienes', ['action' => 'index', 'transaccion' => 'pedido', 'accion' => 'agregar', 'id' => $persona->getId()]); ?>"
                        type="button">
                        <span class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar Item</span>
                    </a>
                </div>
            </div>
        </div>

        <!-- Datos -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    DATOS ECONÓMICOS
                </div>
                <div class="panel-body">
                    <!-- Totales -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Descuento Total ($)</label>
                            <input type="text" class="form-control" name="descuento_total" id="descuento_total" value="0"
                                readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>IVA Total ($)</label>
                            <input type="text" class="form-control" name="iva_total" id="iva_total" value="0" readonly>
                        </div>
                        <div class="form-group col-md-3">
                            <label>Subtotal</label>
                            <input type="text" class="form-control" name="subtotal_general" id="subtotal_general"
                                value="0" readonly>
                        </div>
                    </div>
                    <!-- Forma de Pago + Fecha -->
                    <div class="row form-row">
                    <div class="form-group col-md-3" id="monedas">
                            <label>Moneda</label>
                            <script>
                                var monedas = <?php echo ($monedasJson); ?>;
                                completarMonedas(monedas);
                            </script>
                        </div>
                        <div class="form-group col-md-3" id="formasPago">
                            <label>Forma de Pago</label>
                            <script>
                                var formasPago = <?php echo ($formasPagoJson); ?>;
                                completarFormasPago(formasPago);
                            </script>
                        </div>
                        <div id="div_bonificacion" class="form-group col-md-2">
                            <label>% Bonificación</label>
                            <input type="text" class="form-control" name="bonificacion_general"
                                id="bonificacion_general" value="0.00" onkeypress="return justNumbers(event);"
                                onkeyup="calcularSubcampos()">
                        </div>
                        <div id="div_recargo" class="form-group col-md-2">
                            <label>% Recargo</label>
                            <input type="text" class="form-control" name="recargo_general" id="recargo_general"
                                value="0.00" onkeypress="return justNumbers(event);" onkeyup="calcularSubcampos()">
                        </div>
                        <script>
                            setBonificacionRecargo();
                        </script>
                    </div>
                    <!-- Total -->
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <label>Total</label>
                            <input type="text" class="form-control" name="total_general" id="total_general" value="0"
                                readonly>
                        </div>
                        <div class="form-group col-md-2">
                            <label>Fecha de Vencimiento</label>
                            <div class='input-group date' id='datetimepicker2'>
                                <input type='text' class="form-control" name="fecha_transaccion" value="<?= $date ?>" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script>
                    calcularSubcampos();
                    </script>
                </div>
            </div>
        </div>

        <!-- Datos -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    DATOS DE ENVÍO
                </div>
                <div class="panel-body">
                    <!-- Entrega y Factura al Momento -->
                    <div class="row form-row">
                        <div class="form-check col-md-4">
                            <input type="checkbox" value="" id="EntregaDomicilioFacturacion"
                                name="EntregaDomicilioFacturacion" data-toggle="collapse" data-parent="#accordion"
                                data-target="#collapseEntregaDomicilioFacturacion" aria-expanded="true"
                                aria-controls="collapseEntregaDomicilioFacturacion">
                            <label class="form-check-label" for="EntregaDomicilioFacturacion">Entrega en Domicilio de
                                Facturación</label>
                        </div>
                        <div class="form-check col-md-4">
                            <input type="checkbox" class="form-check-input" name="entrega_momento" id="entrega_momento">
                            <label class="form-check-label" for="entrega_momento">Entrega al momento de la Venta</label>
                        </div>
                        <div class="form-check col-md-4">
                            <input type="checkbox" class="form-check-input" name="factura_momento" id="factura_momento">
                            <label class="form-check-label" for="factura_momento">Factura al momento de la Venta</label>
                        </div>
                    </div>
                    <!-- Forma de Pago + Fecha -->
                    <div class="row form-row">
                        <div class="form-group col-md-12">

                            <div class="row form-row collapse" id="collapseEntregaDomicilioFacturacion">
                                <br>
                                <div class="form-group col-md-3">
                                    <label>Fecha de Entrega</label>
                                    <div class='input-group date' id='datetimepicker3'>
                                        <input type='text' class="form-control" name="fecha_entrega"
                                            value="<?= $date ?>" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group col-md-3" id="formasEnvio">
                                    <label>Formas de Envío</label>
                                    <script>
                                    var formasEnvio = <?php echo ($formasEnvioJson); ?>;
                                    completarFormasEnvio(formasEnvio);
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar pedido</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea agregar este pedido?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>

</form>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $url ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->


