<?php
$this->headTitle('Agregar TipoEvento');
$form->get('nombre')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);
$form->get('version')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Agregar TipoEvento</h1>
            <h4>
                Por favor ingrese los datos de la nueva tipoevento
            </h4>
            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('nombre')); ?>
                        <?= $this->formElement($form->get('nombre')); ?>
                        <?= $this->formElementErrors($form->get('nombre')); ?>                  
                    </div>
                    <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->form()->closeTag(); ?>
                </div>    
            </div>  
        </div>
    </div>
</div>







    



