<?php
$this->headTitle('Editar Tipo de Evento');
$form->get('nombre')->setAttributes([
    'class' => 'form-control',
    'value' => $tipoevento->getNombre()
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

$categoria_eve = $tipoevento->getCategoria_evento();
?>

<?php

$url1 = ""; $url2=""; $url3="";
$label1=""; $label2=""; $label3="";
if ($tipoPersona=="proveedor"){
    $url1 = '/proveedores';
    $label1= "Proveedores";
    $url2 = "/proveedores/actividades";
    $label2 = "Eventos";
    $url3 = "/proveedores/actividades/proveedor";
}elseif ($tipoPersona=="cliente"){
    $url1= "/clientes";
    $label1 = "Clientes";
    $url2= "/clientes/actividades";
    $label2= "Eventos";
    $url3 = "/clientes/actividades/cliente";
}else{
    $url = "/home";
}

?>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $url1 ?>"><?php echo ($label1);?></a></li>
            <li class="breadcrumb-item"><a href="<?= $url2 ?>">Eventos</a></li>
            <li class="breadcrumb-item"><a href="<?= $url3 ?>">Listado</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
        style="margin:0px;">
            <li class="pull-right"><a href="<?php $url2 ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<?= $this->form()->openTag($form); ?>

<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
            EDITAR EVENTO
            </div>
            <div class="panel-body">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Evento</label>
                        <input type="text" class="form-control" name="nombre"
                            value="<?= $tipoevento->getNombre(); ?>">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Categoría</label>
                        <select class="form-control" id="categoria" name="categoria">
                            <option value="<?php if(isset($categoria_eve)){ echo ($categoria_eve->getId()); }?>" hidden="">  
                                <?php if(isset($categoria_eve)){ echo($categoria_eve->getNombre()); } else {echo ("Seleccionar Categoria");}?>
                            </option>
                            <option value="-1">No definido</option>
                            <?php foreach ($categoriaeventos as $categoria) : ?>
                                <option value="<?php echo ($categoria->getId()); ?>"><?php echo ($categoria->getNombre()); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Descripción</label>
                        <input type="text" class="form-control" name="descripcion"
                            value="<?= $tipoevento->getDescripcion(); ?>">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inicio: Modal -->
<div class="container">   
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Editar evento</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea editar los datos del evento?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>    
</div>
<!-- Fin: Modal -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>

        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $volver?>" > <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" 
                    class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->

<?= $this->form()->closeTag(); ?>

    

