<?php
if (isset($_SESSION['MENSAJES']['tipo_evento'])) {
    if ($_SESSION['MENSAJES']['tipo_evento']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['tipo_evento_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['tipo_evento_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['tipo_evento'] = null;
    $_SESSION['MENSAJES']['tipo_evento_msj'] = null;
}
?>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Tipo-Evento -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
                LISTADO TIPO DE ACTIVIDADES
                <a data-toggle="collapse" data-parent="#accordion" href="#add_tipo_evento" 
                    aria-expanded="true" aria-controls="add_tipo_evento">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
        <div class="panel panel-body">
            <div class="container collapse" id="add_tipo_evento">
                <form method="post">
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control form-margen" name="nombre" placeholder="Ingresar tipo de Actividad">
                        </div>
                        <div class="form-group col-md-4">
                            <button type="button" class="btn btn-default form-margen" data-toggle="modal" data-target="#myModal">
                                <span class="glyphicon glyphicon-plus" ></span> Agregar tipo de actividad
                            </button>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Agregar tipo de actividad</h4>
                                </div>
                                <div class="modal-body">
                                    <p>¿Está seguro que desea agregar este tipo de actividad?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-default">Aceptar</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tabla_tipoevento" class="table table-bordred table-striped">
                            <thead>
                                <tr>
                                    <th class="th-sm" onclick="sortTableString(1, 'tabla_tipoevento')">Tipo de Actividad
                                        <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($tipoeventos_pag)) {
                                    foreach ($tipoeventos_pag as $tipoevento) :
                                        ?>
                                        <tr>
                                            <td><?php echo ($tipoevento->getNombre()); ?></td>
                                            <td class="table-items-right">
                                                <a class="btn btn-default" href="<?= $this->url('tipoevento/editar', ['action' => 'edit', 'id' => $tipoevento->getId()]); ?>">
                                                    <span class="glyphicon glyphicon-pencil" ></span> 
                                                </a>
                                                <button name="<?= $tipoevento->getId() ?>" id="<?= $tipoevento->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $tipoevento->getId() ?>">
                                                    <span class="glyphicon glyphicon-remove" ></span>
                                                </button>
                                            </td>
                                            <!-- Modal -->
                                    <div id="myModal<?= $tipoevento->getId() ?>" class="modal fade" role="dialog">
                                        <div class="modal-dialog">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Borrar cliente</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        ¿Está seguro que desea eliminar el tipo de actividad: 
                                                        "<?= $this->escapeHtml($tipoevento->getNombre()) ?>"?
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="<?= $this->url('tipoevento/borrar', ['action' => 'remove', 'id' => $tipoevento->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                                                    <span class="btn btn-default">Aceptar</span></a>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>  
                 </div>
            </div>
        </div>
                <?php
                echo $this->paginationControl($tipoeventos_pag, 'Sliding', // All, Elastic, Jumping, Sliding
                        'search_pagination_tipo.phtml', $this->url('tipoevento/page', ['action' => 'index', 'id' => 1]));
                }
                ?>          
    </div>
</div>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionClientes') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->