<?php
if (isset($_SESSION['MENSAJES']['tipo_evento'])) {
    if ($_SESSION['MENSAJES']['tipo_evento']) {
        echo "<script>jQuery(function(){swal('OK!', '" . $_SESSION['MENSAJES']['tipo_evento_msj'] . "', 'success');});</script>";
    } else {
        echo "<script>jQuery(function(){swal('ERROR!', '" . $_SESSION['MENSAJES']['tipo_evento_msj'] . "', 'error');});</script>";
    }
    $_SESSION['MENSAJES']['tipo_evento'] = null;
    $_SESSION['MENSAJES']['tipo_evento_msj'] = null;
}
?>
<!--Bloqueo de pantalla + animacion-->
<div id="bloquea" class="cargando" style="display:none;"></div>
<div class="" id="loader"></div>
<!-- Inicio: Tabla Tipo-Evento -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO DE EVENTOS
                <a data-toggle="collapse" data-parent="#accordion" href="#add_tipo_evento" 
                    aria-expanded="true" aria-controls="add_tipo_evento">
                    <span class="pull-right clickable"><i class="glyphicon glyphicon-plus btn-collapse"></i></span>
                </a>
            </div>
        <div class="panel panel-body">
            <div class="collapse" id="add_tipo_evento">
                <form method="post">
                    <div class="row form-row">
                        <div class="form-group col-md-4">
                            <label>Acción Comercial</label>
                            <input type="text" class="form-control form-margen" name="nombre" placeholder="Tipo de Actividad">
                        </div>
                        <div class="form-group col-md-4" hidden>
                        <label>Categoría</label>
                            <select class="form-control form-margen" id="accion_comercial" name="categoria">
                                <option value="15" hidden="">Acción comercial</option>
                                <option value="-1">NO DEFINIDO</option>
                                <?php foreach ($categoriaeventos as $categoria) : ?>
                                    <option value="<?php echo ($categoria->getId()); ?>"><?php echo ($categoria->getNombre()); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                        <label>Descripción</label>
                            <input type="text" class="form-control form-margen" name="descripcion" placeholder="Descripción">
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="form-group col-md-3">
                            <button type="button" class="btn btn-default form-margen" data-toggle="modal" data-target="#myModal">
                                <span class="glyphicon glyphicon-plus" ></span>
                                Agregar Acción Comercial
                            </button>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Agregar evento</h4>
                                </div>
                                <div class="modal-body">
                                    <p>¿Está seguro que desea agregar este evento?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-default">Aceptar</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tabla_tipoevento" class="table table-bordred table-striped">
                            <thead>
                                <tr>
                                    <th class="th-sm" onclick="sortTableString(1, 'tabla_tipoevento')">
                                        Evento <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                    </th>
                                    <th class="th-sm" onclick="sortTableString(1, 'tabla_tipoevento')">
                                        Categoría <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                    </th>
                                    <th class="th-sm" onclick="sortTableString(1, 'tabla_tipoevento')">
                                        Descripción <i class="fa fa-sort float-right" aria-hidden="true"></i>
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($tipoeventos_pag)) {
                                    foreach ($tipoeventos_pag as $tipo) :
                                        ?>
                                        <tr>
                                            <td><?php echo ($tipo->getNombre()); ?></td>
                                            <td><?php echo ($tipo->getNombreCategoriaEvento()); ?></td>
                                            <td><?php echo ($tipo->getDescripcion()); ?></td>
                                            <td class="table-items-right">
                                                <a class="btn btn-default" href="<?= $this->url('actividades/editar', ['action' => 'edit', 'tipo'=>$tipoPersona, 'id' => $tipo->getId()]); ?>">
                                                    <span class="glyphicon glyphicon-pencil" ></span> 
                                                </a>
                                                <button   <?php if ((($tipo->getCategoria_evento())!=null) and 
                                                ($tipo->getCategoria_evento()->getId()==16)){echo ("disabled");} ?>
                                                name="<?= $tipo->getId() ?>" id="<?= $tipo->getId() ?>"
                                                type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $tipo->getId() ?>"
                                                >
                                                    <span class="glyphicon glyphicon-remove" ></span>
                                                </button>
                                            </td>
                                            <!-- Modal -->
                                    <div id="myModal<?= $tipo->getId() ?>" class="modal fade" role="dialog">
                                        <div class="modal-dialog">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Eliminar evento</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        ¿Está seguro que desea eliminar el evento: 
                                                        "<?= $this->escapeHtml($tipo->getNombre()) ?>"?
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="<?= $this->url('actividades/borrar', ['action' => 'remove', 'id' => $tipo->getId()]); ?>" onclick="bloqueaPantalla()" type="button">
                                                    <span class="btn btn-default">Aceptar</span></a>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>  
                 </div>
            </div>
        </div>
                <?php
                echo $this->paginationControl($tipoeventos_pag, 'Sliding', // All, Elastic, Jumping, Sliding
                        'search_pagination_tipo.phtml', $this->url('actividades/page', ['action' => 'index', 'tipo'=>$tipoPersona, 'id' => 1]));
                }
                ?>          
    </div>
</div>
<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <?php if ($tipoPersona=="cliente"){ ?>
                    <a href="<?= $this->url('gestionClientes/gestionEventosClientes') ?>">
                <?php } elseif ($tipoPersona == "proveedor"){ ?>
                    <a href="<?= $this->url('gestionProveedores/gestionEventosProveedores') ?>">

                <?php } ?>              
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" 
                    class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
    </div>
</div>
<!-- Fin: Panel Botones -->