<?php
$this->headTitle('Editar provincia');
$form->get('nombre_provincia')->setAttributes([
    'class' => 'form-control'
]);
$form->get('pais')->setAttributes([
    'class' => 'form-control'
]);


$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading titulo-espaciado">Editar País</div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-8">
                    <?= $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('nombre_provincia')); ?>
                        <?= $this->formElement($form->get('nombre_provincia')); ?>
                        <?= $this->formElementErrors($form->get('nombre_provincia')); ?>                  
                    </div>

                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="submit" class="btn btn-default">Cancelar</button>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
