<head>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>




</head>
<body>
    <div class="container">
        <div class="row">


            <div class="col-md-12">
                <div class="table-responsive">


                    <table id="mytable" class="table table-bordred table-striped">

                        <thead>

                            <tr>
                                <th>id</th>
                                <th>Nombre</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>

                            <?php foreach ($provincias as $provincia) : ?>
                                <tr>
                                        <td><?php echo($provincia->getId_provincia()); ?></td>
                                        <td><?php echo($provincia->getId()); ?></td>
                                        <td><?php echo ($provincia->getNombre_provincia()); ?></td>
                                        <td> <a class="btn btn-info" href="<?= $this->url('provincia', ['action' => 'edit', 'id' => $provincia->getId_provincia()]);?>">
                                            <span class="glyphicon glyphicon-pencil" ></span> Edit</td>
                                        </a>
                                        <td><a class="btn btn-default" href="<?= $this->url('provincia', ['action' => 'remove', 'id' => $provincia->getId_provincia()]);?>">
                                        
                                            <span class="glyphicon glyphicon-asterisk"></span> Eliminar </td>
                                    
                                    
                                    
                                 <?php //   <td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></button></p></td> 
                                   // <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                                ?>
                                 </tr>
                            <?php endforeach; ?>




                    </table>
                </div>
            </div>  
        </div>
    </div>

    <p>
        <a class="btn btn-default" href="
           <?= $this->url('provincia', ['action' => 'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Licencia
        </a>
    </p>

    

</body>
</html>