<script src="js/functions.js"> </script>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                    <table id="mytable" class="table table-bordred table-striped">
                        <thead>
                            <tr>
                                <th>Provincia</th>
                                <th>Pais</th>
                                <th>Eliminar</th>
                            </tr>
                            <?php foreach ($provincias as $provincia) : ?>
                                <tr>
                                        <td><?php echo($provincia->getNombre_provincia()); ?></td>
                                        <td><?php echo($provincia->getPais()->getNombre()); ?></td>
<td> <a class="btn btn-default" href="<?= $this->url('provincia', ['action' => 'edit', 'id' => $provincia->getId()]); ?>"> <span class="glyphicon glyphicon-pencil" ></span> </a>                            
                             <button name="<?= $provincia->getId() ?>" id="<?= $provincia->getId() ?>" type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove" ></span</button></td>
                                 <?php //   <td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></button></p></td> 
                                   // <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
                                ?>
                                 </tr>
                            <?php endforeach; ?>
                    </table>
                </div>
            </div>  
        </div>
    <p>
        <a class="btn btn-default" href="
           <?= $this->url('provincia', ['action' => 'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Licencia
        </a>
    </p>
    </div>
