<?php
$title = 'Agregar Cliente';
$this->headTitle($title);
?>

<form method="post">

<div class="container margen">

    <!-- Datos del Producto -->
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                DATOS PARTICULARES DEL PRODUCTO
            </div>
            <div class="panel-body">
                <!-- 1ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre</label>
                        <input type="text" class="form-control" name="nombre" placeholder="Ingresar nombre">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Presentación</label>
                        <input type="text" class="form-control" name="presentacion" placeholder="Ingresar presentación">
                    </div>
                </div>
                <!-- 2da fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Descripción</label>
                        <input type="text" class="form-control" name="descripcion" placeholder="Ingresar descripción">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Marca</label>
                        <input type="text" class="form-control" name="marca" placeholder="Ingresar marca">
                    </div>
                </div>
                <!-- 3ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Categoría</label>
                        <select class="form-control" id="categoria" name="categoria">
                            <option value="" hidden="">Seleccionar Categoría</option>
                            <option value="1">...</option>
                            <option value="2">...</option>
                            <option value="-1">NO DEFINIDO</option>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Proveedor</label>
                        <select class="form-control" id="proveedor" name="proveedor">
                            <option value="" hidden="">Seleccionar Proveedor</option>
                            <option value="1">...</option>
                            <option value="2">...</option>
                            <option value="-1">NO DEFINIDO</option>
                        </select>
                    </div>
                </div>
                <!-- 4ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Código de Producto</label>
                        <input type="text" class="form-control" name="codigo_producto" placeholder="Ingresar código de producto">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Stock</label>
                        <input type="text" class="form-control" name="stock" placeholder="Ingresar stock inicial">
                    </div>
                </div>
                <!-- 5ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Código de Barras</label>
                        <input type="text" class="form-control" name="codigo_barras" placeholder="Ingresar código de barras">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Reposición</label>
                        <input type="text" class="form-control" name="reposicion" placeholder="Ingresar nivel de reposición">
                    </div>
                </div>
            </div>
        </div>   
    </div>
    <!-- Fin Datos del Producto -->

    <!-- Precios del Producto -->
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                DATOS MONETARIOS DEL PRODUCTO
            </div>
            <div class="panel-body">
                <!-- 1ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Precio de Compra</label>
                        <input type="text" class="form-control" name="precio_compra" id="precio_compra" 
                            value=0 onkeypress="return justNumbers(event);" onkeyup="calculaCostoTotalCompra()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Costos Directos</label>
                        <input type="text" class="form-control" name="costos_directos" id="costos_directos"
                            value=0 onkeypress="return justNumbers(event);" onkeyup="calculaCostoTotalCompra()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Gastos Directos</label>
                        <input type="text" class="form-control" name="gastos_directos" id="gastos_directos"
                            value=0 onkeyup="calculaCostoTotalCompra()">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Costo Total de Compra</label>
                        <input type="text" class="form-control" name="costo_total_compra" id="costo_total_compra"
                            value=0 disabled>
                    </div>
                </div>
                <!-- 2da fila -->
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>Contrib. Marginal ($)</label>
                        <input type="text" class="form-control" name="cm_valor" id="cm_valor" value=0
                            onkeypress="return justNumbers(event);" onkeyup="calculaCMValor()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Contrib. Marginal (%)</label>
                        <input type="text" class="form-control" name="cm_porcentual" id="cm_porcentual" value=0
                            onkeypress="return justNumbers(event);" onkeyup="calculaCMPorcentual()">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio de Venta</label>
                        <input type="text" class="form-control" name="precio_venta" id="precio_venta" value=0
                            onkeypress="return justNumbers(event);" onkeyup="calculaPrecioVenta()">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio Venta con Dto.</label>
                        <input type="text" class="form-control" name="precio_venta_dto" id="precio_venta_dto" value=0 disabled>
                    </div>
                </div>
                <!-- 3ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>% Descuento</label>
                        <input type="text" class="form-control" name="descuento" id="descuento" value=0
                            onkeypress="return justNumbers(event);" onkeyup="calculaDescuentoIVA()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>% IVA</label>
                        <select class="form-control" name="iva" id="iva"
                        onkeypress="return justNumbers(event);" onchange="calculaDescuentoIVA()">
                            <option value="0" hidden="">Seleccionar IVA</option>
                            <option value="0">Exento</option>
                            <option value="10.5">10.5</option>
                            <option value="21">21</option>
                            <option value="27">27</option>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Total IVA $</label>
                        <input type="text" class="form-control" name="iva_total" id="iva_total" value=0>
                    </div>
                </div>
                <!-- 4ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Precio Publico + IVA</label>
                        <input type="text" class="form-control" name="precio_publico_iva" id="precio_publico_iva" value=0 disabled>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio Publico +IVA con Dto.</label>
                        <input type="text" class="form-control" name="precio_publico_iva_dto" id="precio_publico_iva_dto" value=0 disabled>
                    </div>
                </div>
            </div>
        </div>   
    </div>
    <!-- Fin Precios del Producto -->

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar cliente</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea agregar este cliente?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin Modal -->
</div>

<!-- Fin: Cliente Nuevo -->

</form>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar"> 
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>                   
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionClientes') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>       
</div>
<!-- Fin: Panel Botones -->


