
<?php
$this->headTitle('Agregar Producto');

$form->get('nombre_producto')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);

$form->get('version_producto')->setAttributes([
    'class' => 'form-control',
    'value' => ''
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Producto Nuevo</div>
        </div>
    </div>
</div>

<?= $this->form()->openTag($form); ?>
<div class="container"> 
    <div class="row">
        <div class="row form-row">
            <div class="form-group col-md-4">
                <?= $this->formLabel($form->get('nombre_producto')); ?>
                <?= $this->formElement($form->get('nombre_producto')); ?>
                <?= $this->formElementErrors($form->get('nombre_producto')); ?> 
            </div>
            <div class="form-group col-md-2">
                <label>Moneda</label>
                <select class="form-control" id="categoria" name="moneda">
                    <option>Pesos ARG</option>
                    <option>USD</option>
                </select>
            </div>
        </div>

        <div class="row form-row">
            <div class="form-group col-md-4">
                <label>Precio de lista</label>
                <input type="text" class="form-control" placeholder="Precio de lista">
            </div>
            <div class="form-group col-md-4">
                <label>Costo producto adicional</label>
                <input type="text" class="form-control" placeholder="Costo producto adicional">
            </div>
            <div class="form-group col-md-2">
                <label>Descuento %</label>
                <input type="text" class="form-control" placeholder="Descuento %">
            </div>
            <div class="form-group col-md-2">
                <label>IVA %</label>
                <input type="text" class="form-control" placeholder="IVA %">
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Borrar cliente</h4>
                </div>
                <div class="modal-body">
                    <p>
                        ¿Estas seguro de que quieres agregar el producto?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>   
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a data-toggle="modal" data-target="#myModal"><img src="<?= $this->basePath('img/crm/Aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Guardar</label>
                        </div>
                    </div>

                    <div class="col ficha-cliente-p img-centrar">
                        <div>
                            <a href="<?= $this->url('producto') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->

<?= $this->form()->closeTag(); ?>