<!-- scripts -->
<script src="/js/producto.js"></script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios">Productos y Servicios</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios/productos">Productos</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios/productos/listado">Listado</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Producto</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/productos/listado" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<?php
$bien = $producto->getBien();



$categoria = $bien->getCategoria();
$iva = $bien->getIva();
$proveedor = $bien->getProveedor();

?>
<form method="post">
<div class="container margen">
    <!-- Datos del Producto -->
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS PARTICULARES DEL PRODUCTO
            </div>
            <div class="panel-body">
                <!-- 1ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre</label>
                        <input type="text" class="form-control" name="nombre"
                            value="<?= $bien->getNombre(); ?>">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Unidad de Medida</label>
                        <input type="text" class="form-control" name="unidad" value="<?= $bien->getUnidad_medida() ?>">
                    </div>
                </div>
                <!-- 2da fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Descripción</label>
                        <input type="text" class="form-control" name="descripcion"
                            value="<?= $bien->getDescripcion(); ?>">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Marca</label>
                        <input type="text" class="form-control" name="marca"
                            value="<?= $bien->getMarca(); ?>">
                    </div>
                </div>
                <!-- 3ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Categoría</label>
                        <select class="form-control" id="categoria" name="categoria">
                             <option value="<?php if(isset($categoria)){ echo ($categoria->getId()); }?>" hidden="">  
                                <?php if(isset($categoria)){ echo $categoria->getNombre(); } else {echo ("Seleccionar Categoría");}?>
                            </option>
                            <option value="-1">No definido</option>
                            <?php foreach ($categorias as $categoria) : ?>
                                <option value="<?= $categoria->getId(); ?>">
                                    <?= $categoria->getNombre(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Proveedor</label>
                        <select class="form-control" id="proveedor" name="proveedor" required>
                                <option value="<?php if(isset($proveedor)){ echo ($proveedor->getId()); }?>" hidden="">  
                                    <?php if(isset($proveedor)){ echo $proveedor->getPersona()->getNombre(); } else {echo ("Seleccionar Proveedor");}?>
                                </option>
                                <option value="-1">No definido</option>
                                <?php foreach ($proveedores as $proveedor) : ?>
                                    <option value="<?= $proveedor->getId(); ?>">
                                        <?= $proveedor->getPersona()->getNombre(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </select>
                    </div>
                </div>
                <!-- 4ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Código de Producto</label>
                        <input type="text" class="form-control" name="codigo"
                            value="<?= $bien->getCodigo(); ?>">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Stock</label>
                        <input type="text" class="form-control" name="stock"
                            value="<?= $bien->getStock(); ?>"  onkeypress="return justNumbers(event);">
                    </div>
                </div>
                <!-- 5ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-6">
                        <label>Código de Barras</label>
                        <input type="text" class="form-control" name="codigo_barras"
                            value="<?= $bien->getCodigo_barras(); ?>">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Reposición</label>
                        <input type="text" class="form-control" name="reposicion"
                            value="<?= $producto->getReposicion(); ?>">
                    </div>
                </div>
            </div>
        </div>   
    </div>
    <!-- Fin Datos del Producto -->

    <!-- Precios del Producto -->
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading titulo-espaciado">
                DATOS ECONÓMICOS DEL PRODUCTO
            </div>
            <div class="panel-body">
                <!-- 1ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Precio de Compra</label>
                        <input type="text" class="form-control" name="precio_compra" id="precio_compra" 
                            value="<?= $producto->getPrecio_compra(); ?>" 
                            onkeypress="return justNumbers(event);" onkeyup="calculaCostoTotalCompra()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Costos Directos</label>
                        <input type="text" class="form-control" name="costos_directos" id="costos_directos"
                            value="<?= $producto->getCostos_directos(); ?>" 
                            onkeypress="return justNumbers(event);" onkeyup="calculaCostoTotalCompra()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Gastos Directos</label>
                        <input type="text" class="form-control" name="gastos_directos" id="gastos_directos"
                            value="<?= $producto->getGastos_directos(); ?>" 
                            onkeypress="return justNumbers(event);" onkeyup="calculaCostoTotalCompra()">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Costo Total de Compra</label>
                        <input type="text" class="form-control" name="precio_compra_total" id="precio_compra_total"
                            value="<?= $producto->getPrecio_compra_total(); ?>" readonly>
                    </div>
                </div>
                <!-- 2da fila -->
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>Contrib. Marginal ($)</label>
                        <input type="text" class="form-control" name="cm_valor" id="cm_valor"
                            value="<?= $producto->getContribucion_marginal_valor(); ?>"
                            onkeypress="return justNumbers(event);" onkeyup="calculaCMValor()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>Contrib. Marginal (%)</label>
                        <input type="text" class="form-control" name="cm_porcentual" id="cm_porcentual"
                            value="<?= $producto->getContribucion_marginal_porcentual(); ?>"
                            onkeypress="return justNumbers(event);" onkeyup="calculaCMPorcentual()">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio de Venta</label>
                        <input type="text" class="form-control" name="precio_venta" id="precio_venta"
                            value="<?= $bien->getPrecio(); ?>"
                            onkeypress="return justNumbers(event);" onkeyup="calculaPrecioVenta()">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio Venta con Dto.</label>
                        <input type="text" class="form-control" name="precio_publico_dto" id="precio_publico_dto"
                            value="<?= $bien->getPrecio_final_dto(); ?>" readonly>
                    </div>
                </div>
                <!-- 3ra fila -->
                <div class="row form-row">
                    <div class="form-group col-md-2">
                        <label>% Descuento</label>
                        <input type="text" class="form-control" name="descuento" id="descuento"
                            value="<?= $bien->getDescuento(); ?>"
                            onkeypress="return justNumbers(event);" onkeyup="calculaDescuentoIVA()">
                    </div>
                    <div class="form-group col-md-2">
                        <label>% IVA</label>
                        <select class="form-control" name="iva" id="iva"
                        onkeypress="return justNumbers(event);" onchange="calculaDescuentoIVA()">
                            <option value="<?php if(isset($iva)){ echo ($iva->getId()); } else {echo (0);}?>" hidden="">  
                                    <?php if(isset($iva)){ echo $iva->getValor(); } else {echo ("Seleccionar Iva");}?>
                            </option>
                            <?php foreach ($ivas as $iva) : ?>
                                <option value="<?php  echo  ($iva->getId()); ?>">
                                <?php echo ($iva->getValor()) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Total IVA $</label>
                        <input type="text" class="form-control" name="iva_total" id="iva_total"
                            value="<?= $bien->getIva_gravado(); ?>" readonly >
                    </div>
                </div>
                <!-- 4ta fila -->
                <div class="row form-row">
                    <div class="form-group col-md-4">
                        <label>Precio Publico + IVA</label>
                        <input type="text" class="form-control" name="precio_publico_iva" id="precio_publico_iva"
                            value="<?= $bien->getPrecio_final_iva(); ?>" readonly>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Precio Publico +IVA con Dto.</label>
                        <input type="text" class="form-control" name="precio_publico_iva_dto" id="precio_publico_iva_dto"
                            value="<?= $bien->getPrecio_final_iva_dto(); ?>" readonly>
                    </div>
                </div>
            </div>
        </div>   
    </div>
    <!-- Fin Precios del Producto -->

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Editar Producto</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea editar este producto?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin Modal -->
</div>

<!-- Fin: Cliente Nuevo -->

</form>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar"> 
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>" class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>                   
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionProductosServicios/gestionProductos/listado') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>       
</div>
<!-- Fin: Panel Botones -->


