<script src="js/functions.js"></script>
<!-- Inicio: Tabla Productos -->
<div class="container margen">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading text-center">
                LISTADO DE PRODUCTOS
            </div>
            <div class="panel-body">
                <table id="tabla_evento" class="table table-bordred table-hover table-condensed">            
                    <thead>
                        <tr>
                            <th class="th-sm">Nombre</th>
                            <th class="th-sm">Descripción</th>
                            <th class="th-sm">Categoria</th>
                            <th class="th-sm" style="width:60px;">Stock</th>
                            <th class="th-sm" style="width:110px;">Precio Venta</th>
                            <th class="th-sm" style="width:110px;">Stock en $.</th> <!-- precio_venta * stock -->
                            <th style="width:90px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (isset($productos_pag)) { 
                            foreach ($productos_pag as $producto) : ?>
                                <tr>
                                    <td><?php echo ($producto->getNombre()); ?></td>
                                    <td><?php echo ($producto->getDescripcion()); ?></td>
                                    <td><?php echo ($producto->getCategoriaNombre()); ?></td>
                                    <td><?php echo ($producto->getStock()); ?></td>
                                    <td><?php echo money_format("$ %n", $producto->getPrecio_venta()); ?></td>
                                    <td><?php echo money_format("$ %n", $producto->getPrecio_venta() * $producto->getStock()); ?></td>
                                    <td> <a class="btn btn-default pull-right" href="<?= $this->url('gestionEmpresa/gestionProductos/editar', ['action' => 'edit', 'id' => $producto->getId()]); ?>">
                                            <span class="glyphicon glyphicon-pencil" ></span> 
                                        </a>
                                        <button name="<?= $producto->getId() ?>" id="<?= $producto->getId() ?>"
                                            type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#myModal<?= $producto->getId() ?>">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>
                                    </td>
                                    <!-- Modal -->
                                    <div id="myModal<?= $producto->getId() ?>" class="modal fade" role="dialog">
                                        <div class="modal-dialog">
                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Borrar producto</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        Estas seguro de borrar la producto?
                                                        "<?= $this->escapeHtml($producto->getNombre()) ?>"
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="<?= $this->url('gestionEmpresa/gestionProductos/eliminar', ['action' => 'remove', 'id' => $producto->getId()]); ?>" class="btn btn-default">Borrar</a>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php echo $this->paginationControl($productos_pag, 'Sliding', // All, Elastic, Jumping, Sliding
                        'search_pagination_producto.phtml', $this->url('producto/page', ['action' => 'index', 'id' => 1]));
        } ?> 
    </div>
</div>
<!-- Fin: Tabla Productos -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="panel-heading">
        <div class="row img-centrar">
            <div class="col ficha-cliente-p img-centrar">
                <div>
                    <a href="<?= $this->url('gestionEmpresa/gestionProductos/agregar'); ?>">
                        <img src="<?= $this->basePath('img/crm/producto_add_n.png') ?>"
                            class="img-rounded img-responsive img-texto-derecha img-submenu">
                    </a>
                </div>
                <div class="ficha-cliente-label">
                    <label>Agregar</label><br>
                    <label>Producto</label>
                </div>
            </div>
            
            <div class="col ficha-cliente-p img-centrar">
                <div>
                    <a href="<?= $this->url('gestionEmpresa/gestionProductos') ?>">
                        <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                            class="img-rounded img-responsive img-texto-derecha">
                    </a>
                </div>
                <div class="ficha-cliente-label">
                    <label>Volver</label>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->