<script src="js/functions.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function() {
        $('#tabla_productos').DataTable({
            "order": [0, 'desc'],

            "language": {
                "url": "/json/spanish.json"
            }
        });
    });
</script>

<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios">Productos y Servicios</a></li>
            <li class="breadcrumb-item"><a href="/productosservicios/productos">Productos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Listado</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/productos" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<div class="container margen">
    <div class="row">
        <div class="panel panel-default sombra-ficha">
            <div class="panel-heading text-center titulo-espaciado">
                LISTADO PRODUCTOS
            </div>
            <div class="panel-body">
                <table id="tabla_productos" class="display">            
                    <thead>
                        <tr>
                            <th class="th-sm">Código</th>
                            <th class="th-sm">Nombre</th>
                            <th class="th-sm">Descripción</th>
                            <th class="th-sm">Categoria</th>
                            <th class="th-sm">Stock</th>
                            <th class="th-sm">Precio Venta</th>
                            <th class="th-sm">Stock en $.</th> <!-- precio_venta * stock -->
                            <th style="width:10%;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (isset($productos)) { 
                            foreach ($productos as $producto) : 
                                $bien = $producto->getBien();
                        ?>
                            <tr>
                                <td><?= $bien->getCodigo() ?></td>
                                <td><?= $bien->getNombre() ?></td>
                                <td><?= $bien->getDescripcion() ?></td>
                                <td><?= $bien->getCategoriaNombre() ?></td>
                                <td><?= $bien->getStock() ?></td>
                                <td><?php echo money_format("$ %n", $bien->getPrecio()); ?></td>
                                <td><?php echo money_format("$ %n", $bien->getPrecio() * $bien->getStock()); ?></td>
                                <td>
                                    <div class="pull-right">
                                        <a class="btn btn-default btn-sm" href="<?= $this->url('gestionProductosServicios/gestionProductos/editar',
                                                                                ['action' => 'edit', 'tipo'=>'producto','id' => $producto->getId()]); ?>">
                                            <span class="glyphicon glyphicon-pencil" ></span> 
                                        </a>
                                        <button name="<?= $producto->getId() ?>" id="<?= $producto->getId() ?>"
                                            type="button" class="btn btn-default btn-sm" data-toggle="modal" 
                                                            data-target="#myModal<?= $producto->getId() ?>">
                                            <span class="glyphicon glyphicon-trash" ></span>
                                        </button>
                                    </div>
                                </td>
                                <!-- Modal -->
                                <div id="myModal<?= $producto->getId() ?>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Borrar producto</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Estas seguro de borrar la producto?
                                                    "<?= $this->escapeHtml($producto->getNombre()) ?>"
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="<?= $this->url('gestionProductosServicios/gestionProductos/eliminar', ['action' => 'remove', 'id' => $producto->getId()]); ?>" class="btn btn-default">Borrar</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </tr>
                        <?php endforeach;} ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Tabla Productos -->

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionProductosServicios/gestionProductos/agregar', ['tipo'=>'producto']); ?>">
                    <img src="<?= $this->basePath('img/crm/producto_add_n.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha img-submenu zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Agregar</label><br>
                <label>Producto</label>
            </div>
        </div>
        
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionProductosServicios/gestionProductos') ?>">
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                        class="img-rounded img-responsive img-texto-derecha zoom">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->