
<!-- php -->
<?php
$date = date('d-m-Y');
$url = "";
$label = "";
if ($transaccion == "pedido") {
    $url = "/pedido/add/" . $id_persona;
    $label = "Agregar Pedido";
}
?>
<script src="/js/bienes.js"></script>

<!-- Document -->
<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10" style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/clientes">Clientes</a></li>
            <li class="breadcrumb-item"><a href="/clientes/listado">Listado</a></li>
            <li class="breadcrumb-item"><a href=<?= $url ?>> <?= $label ?> </a></li>
            <li class="breadcrumb-item active" aria-current="page">Agregar Servicio</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2" style="margin:0px;">
            <li class="pull-right"><a href="/productosservicios/servicios" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<!-- Formulario -->
<form id="busqueda"method="post">
    <div class="container margen">
        <!-- Datos de Pedido -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    AGREGAR ITEM
                </div>
                <div class="panel-body">
                    <!-- Datos de Transaccion -->
                    <div class="row form-row">
                        <div class="form-group col-sm-3">
                            <label>Tipo de Item</label>
                            <select class="form-control" id="tipo" name="tipo" required>
                                <option value="-1">Seleccionar</option>
                                <option value="Producto">Producto</option>
                                <option value="Servicio">Servicio</option>
                                <option value="Licencia">Licencia</option>
                            </select>
                        </div>
                        <div class="form-group col-sm-8">
                            <label>Buscar Item</label>
                            <div class="form-inline">
                                <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombre" style="width: 60%;">
                                <button type="submit" class="btn btn-default" id="busqueda">
                                <i class="glyphicon glyphicon-search"></i> Buscar
                                </button>
                                <!-- <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     
        <!-- Tabla de Items -->
        <div class="row form-row">
            <div class="panel panel-default sombra-ficha">
                <div class="panel-heading titulo-espaciado">
                    LISTADO DE ITEMS
                </div>

                <div class="" id="">
                    <div class="container" id="contenido_bienes">
                        <script>
                            var obj = <?php echo ($bienes); ?>;
                            addItems(obj);
                        </script>
                    </div>
                </div>
            </div>
        </div>

        <!-- Datos -->
        <form method="post">
            <div class="row form-row">
                <div class="panel panel-default sombra-ficha">
                    <div class="panel-heading titulo-espaciado">
                        DETALLE
                    </div>
                    <div class="panel-body">
                        <!-- Detalle -->
                        <div class="row form-row">
                            <div class="form-group col-md-2">
                                <label>Cantidad</label>
                                <input type="number" class="form-control" name="cantidad" id="cantidad" 
                                    min="1" max="99" value="">
                            </div>
                            <div class="form-group col-md-3">
                                <label>Bonificación</label>
                                <input type="text" class="form-control" name="bonificacion" id="bonificacion" >
                            </div>
                            <div class="form-group col-md-3">
                                <label>IVA</label>
                                <input type="text" class="form-control" name="iva" id="iva" >
                            </div>
                            <div class="form-group col-md-3">
                                <label>Subtotal</label>
                                <input type="text" class="form-control" name="subtotal" id="subtotal" >
                            </div>
                            <input type="number" name="idbien" id="idbien" hidden="">
                        </div>
                    </div>
                </div>
            </div>

    </div>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar pedido</h4>
                </div>
                <div class="modal-body">
                    <p>¿Está seguro que desea agregar este pedido?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default" id="agregar">Aceptar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>



<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a data-toggle="modal" data-target="#myModal">
                    <img src="<?= $this->basePath('img/crm/aceptar.png') ?>" 
                    class="img-rounded img-responsive img-texto-derecha img-submenu-sm zoom" role="button">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Guardar</label>
            </div>
        </div>
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href=<?= $url ?> >
                    <img src="<?= $this->basePath('img/crm/volver_b.png') ?>" class="img-rounded img-responsive img-texto-derecha zoom"></a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>

</form>
<!-- Fin: Panel Botones --> 