<!-- MODULE APPLICATION -->
<div class="container margen" >         
    <form method="post">
        
    <div class="container margen">
        <div class="row">
            <div class="row img-centrar">
                <div class="col ficha-cliente-p img-centrar">
                  <a href="<?= $this->url('backup'); ?>" type="button">
                    <span class="btn btn-default">
                        <span class="glyphicon glyphicon-plus" ></span> Exportar como xls
                    </span>
                </a> 
                </div>
                <div class="col ficha-cliente-p img-centrar">
                    <div class="col ficha-cliente-p img-centrar">
                  <a href="<?= $this->url('backup2'); ?>" type="button">
                    <span class="btn btn-default">
                        <span class="glyphicon glyphicon-plus" ></span> Exportar como csv
                    </span>
                </a> 
                </div>
                </div>
                <div class="col ficha-cliente-p img-centrar">
                    <a href="backup.php" type="button"><span class="btn btn-default">Cancelar Backup</span></a> 
                </div>
            </div>
        </div>
    </div>
    </form>
</div>
