<?php 
header("Pragma: public");
header("Expires: 0");
$filename = "Backup_Clientes.xls";
//header("Content-type: application/x-msdownload; charset=utf8");
header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
header("Content-Disposition: attachment; filename=$filename");
header("Pragma: no-cache");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
?>

<table>
    <tbody>
        <?php foreach ($resultado as $cliente): 
        if(strlen($cliente->getEmail())>2){ ?>
            <tr>
                <td><?php echo(utf8_decode($cliente->getNombre())); ?></td>
                <td><?php echo(utf8_decode($cliente->getApellido()));?></td>
                <td><?php echo(utf8_decode($cliente->getTelefono()));?></td>
                <td><?php echo(utf8_decode($cliente->getEmail()));?></td>
                <td><?php echo(utf8_decode($cliente->getNombreCategoriaCliente()));?></td>
                <td><?php echo($cliente->getEstadoNombre());?></td>
            </tr>
        <?php } endforeach;?>
    </tbody>
</table>

