<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('gestionClientes/gestionActividadesClientes/tipoevento'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Listado</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionClientes/gestionActividadesClientes/categoriaevento'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Categorias</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionClientes'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/carrito_excel_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Exportar a Excel</small>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('gestionClientes') ?>">
                            <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                                class="img-rounded img-responsive img-texto-derecha">
                        </a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>