<!-- MODULE APPLICATION -->
<div class="container margen text-center" >         
    <nav id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('categoriacliente'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonCategorias.png') ?>" class="img-rounded img-responsive">
                </a>
            </li>
            <li>
                <a href="<?= $this->url('profesioncliente'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonProfeciones.png') ?>" class="img-rounded img-responsive">
                </a>
            </li>
            <li>
                <a href="<?= $this->url('tipoevento'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonActividades.png') ?>" class="img-rounded img-responsive">
                </a>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>