<div class="container margen">
    <div class="panel panel-default">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE PRODUCTOS & SERVICIOS
        </div>
        <div class="panel-body">
            <div class="ficha-cliente-p margen">
                <div class="container margen text-center" >         
                    <nav class="navbar" id="nav" >
                        <ul>
                            <li>
                                <figure>
                                    <a href="<?= $this->url('gestionProductosServicios/gestionLicencias'); ?>" > 
                                        <img src="<?= $this->basePath('img/crm/billete_n.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar">
                                    </a>
                                    <figcaption>Licencias</figcaption>
                                </figure>
                            </li>
                            <li>
                                <figure>
                                    <a href="<?= $this->url('gestionProductosServicios/gestionProductos'); ?>" > 
                                        <img src="<?= $this->basePath('img/crm/producto_n.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar">
                                    </a>
                                    <figcaption>Productos</figcaption>
                                </figure>
                            </li>
                            <li>
                                <figure>
                                    <a href="<?= $this->url('gestionProductosServicios/gestionServicios'); ?>" > 
                                        <img src="<?= $this->basePath('img/crm/servicio_n.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar">
                                    </a>
                                    <figcaption>Servicios</figcaption>
                                </figure>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="container margen text-center" >
        <nav id="nav" >
            <ul>
                <li>
                    <div class="img-centrar">
                        <div>
                            <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" 
                            class="img-rounded img-responsive img-texto-derecha"></a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </li>

            </ul>
        </nav>
    </div> 
</div>