<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE CLIENTES
        </div>
        <div class="panel-body">
            <div class="container margen text-center">         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/listado'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Listado de Clientes</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url("gestionClientes/agregar", ['tipo'=>'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/cliente_add_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Agregar Cliente</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/gestionEventosClientes'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Eventos</figcaption>
                            </figure>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/categorias', ['tipo'=>'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorías de Cliente</small>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/profesion'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Profesiones de Cliente</figcaption>
                            <figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/eventos', ['tipo'=>'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Resumen de Eventos</small>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/backup'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/cliente_excel_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>&nbsp;&nbsp;Exportar a Excel&nbsp;&nbsp;</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
