<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Empresa</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('home'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN EMPRESA
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionEmpresa/eventos'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Eventos Generales</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionEmpresa/configuracion'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Configuración</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionEmpresa/backup'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>"
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Exportar</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>