<!-- MODULE APPLICATION -->
<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/proveedor_v.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Listado</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/proveedor_v.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Agregar Proveedor</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/consulta_v.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Categorias</small>
            </li>
        </ul>
        <ul>
            <li>
                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/producto_v.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Productos</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/servicio_v.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Servicios</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/consulta_v.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Exportar a Excel</small>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>