<!-- MODULE APPLICATION -->
<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores/listado'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/proveedor_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Listado</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/proveedor_add_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Agregar Proveedor</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Actividades</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/consulta_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Categorias</figcaption>
                </figure>
            </li>
        </ul>
        <ul>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/producto_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Productos</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/servicio_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Servicios</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/proveedor_excel_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Exportar a Excel</figcaption>
                </figure>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('menu') ?>"><img src="<?= $this->basePath('img/crm/volver_b.png') ?>" 
                        class="img-rounded img-responsive img-texto-derecha"></a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>