<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE EVENTOS
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/gestionEventosProveedores/tipoeventoProveedor', ['tipo'=>'proveedor']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Listado de Eventos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/gestionEventosProveedores/categorias', ['tipo'=>'evento']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorias de Eventos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_excel_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Exportar a Excel</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="container margen text-center" >
        <nav id="nav" >
            <ul>
                <li>
                    <div class="img-centrar">
                        <div>
                            <a href="<?= $this->url('gestionProveedores') ?>">
                                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                                    class="img-rounded img-responsive img-texto-derecha zoom">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</div>