<!-- MODULE APPLICATION -->
<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('categoriacliente'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonCategorias.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <!-- <small>Cat. Cliente</small> -->
            </li>
            <li>
                <a href="<?= $this->url('profesioncliente'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonProfesiones.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <!-- <small>Prof. Cliente</small> -->
            </li>
            <li>
                <a href="<?= $this->url('tipoevento'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonTipoActividad.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <!-- <small>Tipo Actividad</small> -->
            </li>
       
            <li>
                <a href="<?= $this->url('ejecutivos'); ?>">
                    <img src="<?= $this->basePath('img/crm/BotonEjecutivos.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <!-- <small>Ejecutivos</small> -->
            </li>
            <li>
                <a href="<?= $this->url('empresa'); ?>">
                    <img src="<?= $this->basePath('img/crm/BotonEmpresa.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <!-- <small>Empresa</small> -->
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>