<!-- MODULE APPLICATION -->
<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('gestionClientes/listado'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Listado</small>
            </li>
            <li>
                <a href="<?= $this->url("gestionClientes/agregar", ["action" => "add"]); ?>" > 
                    <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Agregar Cliente</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionClientes/profesioncliente'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Profesiones</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionClientes'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Exportar a Excel</small>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>