<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('gestionEmpresa/gestionLicencias/listado'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/billete_n.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Listado</small>
            </li>
            <li>
                <a href="<?= $this->url("gestionEmpresa/gestionLicencias/agregar", ["action" => "add"]); ?>" > 
                    <img src="<?= $this->basePath('img/crm/billete_add_n.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Agregar Licencia</small>
            </li>
            <li>
                <a href="<?= $this->url("gestionEmpresa/gestionLicencias/agregar", ["action" => "add"]); ?>" > 
                    <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Categorías</small>
            </li>
            <li>
                <a href="<?= $this->url('gestionEmpresa/gestionLicencias/backup'); ?>" > 
                    <img src="<?= $this->basePath('img/crm/billete_excel_n.png') ?>" class="img-rounded img-responsive img-menu">
                </a>
                <small>Exportar a Excel</small>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('gestionEmpresa') ?>">
                            <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                                class="img-rounded img-responsive img-texto-derecha">
                            </a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>