<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb secondary-color navbar-menu-font">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionClientes'); ?>">Clientes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Eventos</li>
        </ol>
    </nav>
</div>

<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE EVENTOS
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/gestionEventosClientes/tipoeventoCliente', ['tipo'=>'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Listado de Eventos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure hidden>
                                <a href="<?= $this->url('gestionClientes/gestionEventosClientes/categorias', ['tipo'=>'evento']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorias de Eventos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_excel_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Exportar a Excel</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>