<div class="container margen text-center" >         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProductosServicios/gestionLicencias/listado'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/billete_n.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Listado</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url("gestionProductosServicios/gestionLicencias/agregar", ['tipo'=>'licencia']); ?>" > 
                        <img src="<?= $this->basePath('img/crm/billete_add_n.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Agregar Licencia</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url("gestionProductosServicios/gestionLicencias/categorialicencia", ['tipo'=>'licencia']); ?>" > 
                        <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Categorías</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProductosServicios/gestionLicencias/backup'); ?>" > 
                        <img src="<?= $this->basePath('img/crm/billete_excel_n.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Exportar a Excel</figcaption>
                </figure>
            </li>
        </ul>
    </nav>
    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('gestionProductosServicios') ?>">
                            <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                                class="img-rounded img-responsive img-texto-derecha">
                            </a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>