<div class="container margen">
    <div class="panel panel-default">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE PRODUCTOS
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios/gestionProductos/listado'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/producto_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar">
                                </a>
                                <figcaption>Listado de Productos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url("gestionProductosServicios/gestionProductos/agregar", ['tipo' => 'producto']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/producto_add_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar">
                                </a>
                                <figcaption>Agregar Producto</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios/gestionProductos/categoriaproducto', ['tipo'=>'producto']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar">
                                </a>
                                <figcaption>Categorias de Producto</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios/gestionProductos/backup'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/producto_excel_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar">
                                </a>
                                <figcaption>Exportar a Excel</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="container margen text-center" >
        <nav id="nav" >
            <ul>
                <li>
                    <div class="img-centrar">
                        <div>
                            <a href="<?= $this->url('gestionProductosServicios') ?>">
                                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                                    class="img-rounded img-responsive img-texto-derecha">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</div>