<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE SERVICIOS
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/listado'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/servicio_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Listado de Servicios</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url("gestionProductosServicios/gestionServicios/agregar",  ['tipo'=>'servicio']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/servicio_add_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Agregar Servicio</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/categorias', ['tipo'=>'servicio']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorias de Servicio</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios/gestionServicios/backup'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/producto_excel_n.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Exportar a Excel</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="container margen text-center" >
        <nav id="nav" >
            <ul>
                <li>
                    <div class="img-centrar">
                        <div>
                            <a href="<?= $this->url('gestionProductosServicios') ?>">
                                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                                    class="img-rounded img-responsive img-texto-derecha zoom">
                            </a>
                        </div>
                        <div class="ficha-cliente-label">
                            <label>Volver</label>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</div>