<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Proveedores</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="/" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            GESTIÓN DE PROVEEDORES
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/listado', ['tipo' => 'proveedor']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/proveedor_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Listado de Proveedores</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url("proveedores/agregar", ['tipo'=>'proveedor']); ?>">
                                    <img src="<?= $this->basePath('img/crm/proveedor_add_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Agregar Proveedor</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/eventos', ['tipo'=>'proveedor']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Resumen de Eventos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('cuentacorriente', ['tipo'=>'proveedor']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Cuenta Corriente</figcaption>
                            </figure>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/categorias', ['tipo'=>'proveedor']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorias de Proveedor</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/gestionEventosProveedores', ['tipo'=>'proveedor']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Eventos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores/backup'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/proveedor_excel_v.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Exportar a Excel</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
