<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?= $this->url('gestionClientes'); ?>">Clientes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Resumen de Eventos</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="<?= $this->url('gestionClientes'); ?>" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>

<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            RESUMEN DE EVENTOS
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/eventos', ['tipo' => 'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Acciones Comerciales</small>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/gestionEventosClientes/tipoeventoCliente', ['tipo'=>'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorias Acc. Comerciales</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionClientes/transacciones', ['tipo' => 'cliente']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/consulta_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Transacciones</small>
                            </figure>
                        </li>
                        <li>
                            <figure hidden>
                                <a href="<?= $this->url('gestionClientes/gestionEventosClientes/categorias', ['tipo'=>'evento']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/carrito_a.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Categorias de Eventos</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>