<div class="container padding-cero">
    <nav aria-label="breadcrumb">
    <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-10"
    style="margin:0px;">
            <li class="breadcrumb-item"><a href="<?= $this->url('home'); ?>">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Herramientas</li>
        </ol>
        <ol id="breadcrumb_contenido" class="breadcrumb secondary-color navbar-menu-font col-xs-2"
                    style="margin:0px;">
            <li class="pull-right"><a href="/" id="volver">Volver</a></li>
        </ol>
    </nav>
</div>
<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            HERRAMIENTAS
        </div>
        <div class="panel-body">
            <div class="container margen text-center" >         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas/tipoiva'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Tipos de IVA</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas/condicioniva', ['tipo'=>'iva']); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Condición de IVA</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas/tipocomprobante'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Tipos de Comprobante</figcaption>
                            </figure>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas/ejecutivos'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Ejecutivos</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas/formaspago'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Formas de Pago</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas/formasenvio'); ?>" > 
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                    class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Formas de Envío</figcaption>
                            </figure>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>