<div id="header" >
    <div class="container" >
        <!-- Logo -->
        <h1>
            <a href="<?= $this->url('application', ['action' => 'index']); ?>" id="logo" class="titulo">Huella CRM</a>
            <small id="crm_version" style="font-size: 12px;">v1.2.0</small>
        </h1>
        <header class="major">
            <span class="byline">Sistema de Administración de Clientes, Stock y Ventas </span>
        </header>                 
        <!-- Nav -->      
        <nav class="navbar" id="nav">
            
            <ul> 
                <li>
                    <a href="<?= $this->url('menu'); ?>">
                        <img src="<?= $this->basePath('img/crm/bienvenido_g.png') ?>" 
                        class="img-rounded img-responsive img-centrar">
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>