<div class="container padding-cero">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb secondary-color navbar-menu-font">
            <li class="breadcrumb-item active" aria-current="page">Home</li>
        </ol>
    </nav>
</div>
<div class="container margen">
    <div class="panel panel-default sombra-ficha">
        <div class="panel-heading text-center titulo-espaciado">
            MENÚ PRICIPAL
        </div>
        <div class="panel-body">
            <div class="container margen text-center">         
                <nav class="navbar" id="nav" >
                    <ul>
                        <li>
                            <div class="contenedor">
                            <figure>
                                <a href="<?= $this->url('gestionClientes'); ?>">
                                    <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Clientes</figcaption>
                            </figure>
                         </div>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProveedores'); ?>">
                                    <img src="<?= $this->basePath('img/crm/proveedor_v.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Proveedores</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionProductosServicios'); ?>">
                                    <img src="<?= $this->basePath('img/crm/bolsa_n.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Productos y Servicios</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('gestionEmpresa'); ?>">
                                    <img src="<?= $this->basePath('img/crm/empresa_n.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Empresa</figcaption>
                            </figure>
                        </li>
                        <li>
                            <figure>
                                <a href="<?= $this->url('herramientas'); ?>">
                                    <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                                        class="img-rounded img-responsive img-menu img-centrar zoom">
                                </a>
                                <figcaption>Herramientas</figcaption>
                            </figure>
                        </li>
                    </ul>   
                </nav>
            </div>
        </div>
    </div>
</div>


