<!-- MODULE APPLICATION -->
<div class="container margen text-center">         
    <nav class="navbar" id="nav" >
        <ul>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionClientes'); ?>">
                        <img src="<?= $this->basePath('img/crm/cliente_a.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Clientes</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProveedores'); ?>">
                        <img src="<?= $this->basePath('img/crm/proveedor_v.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Proveedores</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionProductosServicios'); ?>">
                        <img src="<?= $this->basePath('img/crm/bolsa_n.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Productos y Servicios</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('gestionEmpresa'); ?>">
                        <img src="<?= $this->basePath('img/crm/empresa_n.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Empresa</figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <a href="<?= $this->url('herramientas'); ?>">
                        <img src="<?= $this->basePath('img/crm/herramienta_r.png') ?>" 
                        class="img-rounded img-responsive img-menu img-centrar">
                    </a>
                    <figcaption>Herramientas</figcaption>
                </figure>
            </li>
        </ul>   
    </nav>
</div>