<!-- MODULE APPLICATION -->
<div class="container margen text-center" >         
    <nav id="nav" >
        <ul>
            <li>
                <a href="<?= $this->url('application', ['action' => 'backup']); ?>" > 
                    <img src="<?= $this->basePath('img/crm/BotonBackupExcel.png') ?>" class="img-rounded img-responsive">
                </a>
            </li>
        </ul>
    </nav>

    <nav id="nav" >
        <ul>
            <li>
                <div class="img-centrar">
                    <div>
                        <a href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/crm/Volver.png') ?>" class="img-rounded img-responsive img-texto-derecha"></a>
                    </div>
                    <div class="ficha-cliente-label">
                        <label>Volver</label>
                    </div>
                </div>
            </li>

        </ul>
    </nav>
</div>