<script src="js/functions.js"></script>
<?php
$meses = ['N/A', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio',
        'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
?>
<div class="container margen">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading text-center titulo-espaciado">
                    LISTADO MOVIMIENTOS
                </div>
                <div class="panel-body">
                    <form method="post">
                        <div class="row form-row">
                            <div class="form-group col-sm-4">
                                <select class="form-control" id="tipo" name="tipo" placeholder="Tipo de evento" value="<?php if (count($parametros)>0){echo($parametros['tipo']);} ?>">
                                    <option value="" hidden="">-Seleccionar-</option>
                                    <option value="Cotizaciones">Cotizaciones</option>
                                    <option value="Soportes">Soportes</option>
                                    <option value="Ventas">Ventas</option>
                                </select>
                            </div>
                            <div class="form-group col-sm-2">
                                <input type="number" class="form-control" name="ventas_m" min="1" max="12" placeholder="Mes" value="<?php if (count($parametros)>0){echo($parametros['ventas_m']);} ?>">                        
                            </div>
                            <div class="form-group col-sm-2">
                                <input type="number" class="form-control" name="ventas_y" min="2010" max="<?php echo date("Y"); ?>" placeholder="Año" value="<?php if (count($parametros)>0){echo($parametros['ventas_y']);} ?>">                        
                            </div>
                            <div class="form-group col-sm-2">
                                <button type="submit" class="btn btn-default"> 
                                    <i class="glyphicon glyphicon-search"></i> Buscar
                                </button>  
                            </div>
                        </div>
                    </form>
                    <div class="container row">
                            Total
                            <?php
                                if(isset($parametros['tipo'])){
                                    echo($parametros['tipo']);}
                                if(isset($parametros['ventas_m'])){
                                    if(($parametros['ventas_m']) != 0){
                                        echo(' ' . $meses[$parametros['ventas_m']]);}
                                }
                                if(isset($parametros['ventas_y'])){
                                    echo(' ' . $parametros['ventas_y'] . ' ');}
                                echo(': ' . count($total));
                            ?>
                    </div>
                    <p>
                    </p>
                    <table id="tabla_evento" class="table table-bordred table-striped">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Tipo</th>
                                <th>Cliente</th>
                                <!-- <th>Categoria</th> -->
                                <th></th>
                            </tr>
                        </thead>
                        <?php foreach ($eventos as $evento) : ?>
                        <tr>
                            <td><?php if(!is_null($evento->getFecha())) {echo ($evento->getFecha()->format('d/m/Y'));} ?></td>
                            <td><?php echo ($evento->getTipo()); ?></td>
                            <td><?php echo ($evento->getNombrePersona()); ?></td>
                            <!-- <td><?phecho ($evento->getPersona()->getNombreCategoriaCliente()); ?> </td> -->

                            <td class="table-items-right">
                                <a class="btn btn-default" href="<?= $this->url('clientes/ficha', ['action' => 'ficha', 'id' => $evento->getPersona()->getId()]); ?>">
                                    <span class="glyphicon glyphicon-share-alt" ></span>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>  
    <?php
    echo $this->paginationControl($eventos, 'Sliding', // All, Elastic, Jumping, Sliding
            'search_pagination3.phtml', $this->url('pageventas', ['action' => 'index', 'id' => 1]));
    ?>     
</div>

<!-- Inicio: Panel Botones -->
<div class="container margen">
    <div class="row img-centrar">
        <div class="col ficha-cliente-p img-centrar">
            <div>
                <a href="<?= $this->url('gestionEmpresa') ?>">
                <img src="<?= $this->basePath('img/crm/volver_b.png') ?>"
                    class="img-rounded img-responsive img-texto-derecha">
                </a>
            </div>
            <div class="ficha-cliente-label">
                <label>Volver</label>
            </div>
        </div>
    </div>
</div>
<!-- Fin: Panel Botones -->