<script src="js/functions.js"> </script>

<div class="container">
    <div class="row">
        <div class="col-md-12">


            <div class="panel panel-default">
                <div class="panel-heading text-center">Listado de ventas</div>
                <div class="panel-body">
                    <form method="post">
<!--                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <input type="text" class="form-control" name="apellido_cliente" placeholder="Apellido Cliente">
                            </div>
                            <div class="form-group col-md-4">
                                <input type="text" class="form-control" name="nombre_cliente" placeholder="Nombre Cliente">
                            </div>
                            <div class="form-group col-md-2">
                                               
                            </div>

                        </div>-->


                    <div class="form-row">
<!--                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="tipo" placeholder="Tipo de evento">
                        </div>-->
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="fecha" placeholder="Fecha">
                        </div>
                        <button type="submit" class="btn btn-default"> 
                                    <i class="glyphicon glyphicon-search"></i> Buscar
                                </button>       
<!--                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="ejecutivo" placeholder="Ejecutivo">
                        </div>-->
                      </div>   
                         
                    </div>
                </form>
            </div>

                

                <table id="tabla_evento" class="table table-bordred table-striped">

                    <thead>
                        <tr>
                            <th class="th-sm"  onclick="sortTableNumeric(0,'tabla_evento')">Id
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-sm" onclick="sortTableString(1,'tabla_evento')">Fecha
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-sm"  onclick="sortTableString(2,'tabla_evento')">Tipo
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-sm"  onclick="sortTableString(3,'tabla_evento')">Cliente
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th class="th-sm"  onclick="sortTableString(4,'tabla_evento')">Ejecutivo
                                <i class="fa fa-sort float-right" aria-hidden="true"></i>
                            </th>
                            <th></th>      
                        </tr>

                    </thead>
                    <?php foreach ($eventos as $evento) : ?>
                        <tr>
                            <td><?php echo($evento->getId()); ?></td>
                            <td><?php echo ($evento->getFecha()); ?></td>
                            <td><?php echo ($evento->getTipo()); ?></td>
                            <td><?php echo ($evento->getNombreCliente()); ?></td>
                            <td><?php echo ($evento->getUsuarioEjecutivo()); ?></td>

                            <td> <a class="btn btn-default" href="<?= $this->url('evento', ['action' => 'edit', 'id' => $evento->getId()]); ?>"><span class="glyphicon glyphicon-pencil" ></span></a>

                             <button name="<?= $evento->getId() ?>" id="<?= $evento->getId() ?>" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<?= $evento->getId() ?>"><span class="glyphicon glyphicon-remove" ></span></button></td>
                            <!-- Modal -->
                        <div id="myModal<?= $evento->getId() ?>" class="modal fade" role="dialog">
                            <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Borrar Ejecutivo</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                            Estas seguro de borrar el evento?
                                            "<?= $this->escapeHtml($evento->getId()) ?>"
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="<?= $this->url('evento', ['action' => 'remove', 'id' => $evento->getId()]); ?>" class="btn btn-primary">Borrar</a>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </tr>

                    <?php endforeach; ?>
                </table>
                <?php
                echo $this->paginationControl($eventos, 'Sliding', // All, Elastic, Jumping, Sliding
                        'search_pagination3.phtml', $this->url('pageventas', ['action' => 'index', 'id' => 1]));
                ?>
            </div>
        </div>  
    </div>
</div>
